package ${package}.infrastructure.security;

import ${package}.common.core.CurrentClock;
import ${package}.application.auth.AuthService;
import ${package}.application.rbac.UserQueryService;
import ${package}.common.security.TokenService;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Authentication bean wiring (generated by engineering-platform ${asset.version}).
 */
@Configuration
public class AuthBeansConfig {

    @Value("#{environment['auth.token.expiration-seconds'] ?: 3600}")
    private long expirationSeconds;

    @Bean
    public CurrentClock currentClock() {
        return CurrentClock.system();
    }

    @Bean
    public AuthService authService(UserQueryService userQueryService, TokenService tokenService,
                                   CurrentClock currentClock) {
        return new AuthService(userQueryService, tokenService, currentClock, expirationSeconds);
    }
}
