package ${package}.infrastructure.security;

import ${package}.common.core.RequestContext;
import ${package}.common.security.TokenService;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.web.servlet.HandlerInterceptor;

/**
 * Authentication interceptor (generated by engineering-platform ${asset.version}).
 *
 * Extracts "Authorization: Bearer <token>", validates it, and puts the current
 * user id into RequestContext for the duration of the request. The context is
 * always cleared when the request finishes (no ThreadLocal leak).
 */
public class AuthInterceptor implements HandlerInterceptor {

    public static final String BEARER_PREFIX = "Bearer ";

    private final TokenService tokenService;

    public AuthInterceptor(TokenService tokenService) {
        this.tokenService = tokenService;
    }

    @Override
    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) {
        String header = request.getHeader("Authorization");
        if (header == null || !header.startsWith(BEARER_PREFIX)) {
            // unauthenticated: leave context empty; @RequirePermission decides allow/deny
            return true;
        }
        String token = header.substring(BEARER_PREFIX.length()).trim();
        Long userId = tokenService.validate(token);
        RequestContext.set(RequestContext.Context.of(null, null, String.valueOf(userId)));
        return true;
    }

    @Override
    public void afterCompletion(HttpServletRequest request, HttpServletResponse response,
                                Object handler, Exception ex) {
        RequestContext.clear();
    }
}
