package ${package}.application.auth;

import ${package}.api.auth.LoginRequest;
import ${package}.api.auth.LoginResponse;
import ${package}.common.core.CurrentClock;
import ${package}.common.core.PlatformException;
import ${package}.common.security.PasswordEncoder;
import ${package}.common.security.SecurityErrorCodes;
import ${package}.common.security.TokenService;
import ${package}.domain.entity.SysUser;
import ${package}.application.rbac.UserQueryService;

import java.time.Instant;

/**
 * Authentication application service (generated by engineering-platform ${asset.version}).
 * Lightweight V1: username + password -> token. No full Spring Security framework.
 */
public class AuthService {

    private final UserQueryService userQueryService;
    private final TokenService tokenService;
    private final CurrentClock clock;
    private final long tokenExpirationSeconds;

    public AuthService(UserQueryService userQueryService, TokenService tokenService,
                       CurrentClock clock, long tokenExpirationSeconds) {
        this.userQueryService = userQueryService;
        this.tokenService = tokenService;
        this.clock = clock;
        this.tokenExpirationSeconds = tokenExpirationSeconds;
    }

    public LoginResponse login(LoginRequest request) {
        SysUser user = userQueryService.findByUsername(request.username())
                .orElseThrow(() -> new PlatformException(SecurityErrorCodes.INVALID_CREDENTIALS));

        if (!PasswordEncoder.verify(request.password(), user.getPasswordHash())) {
            throw new PlatformException(SecurityErrorCodes.INVALID_CREDENTIALS);
        }
        if (user.getEnabled() == null || !user.getEnabled()) {
            throw new PlatformException(SecurityErrorCodes.USER_DISABLED);
        }

        String token = tokenService.issue(user.getId());
        Instant expiresAt = clock.now().plusSeconds(tokenExpirationSeconds);
        return new LoginResponse(token, user.getId(), user.getUsername(), expiresAt.getEpochSecond());
    }
}
