package ${package}.api.auth;

import jakarta.validation.constraints.NotBlank;

/**
 * Login request (generated by engineering-platform ${asset.version}).
 */
public record LoginRequest(
        @NotBlank(message = "username is required") String username,
        @NotBlank(message = "password is required") String password) {
}
