package ${package}.api.auth;

/**
 * Login response (generated by engineering-platform ${asset.version}).
 */
public record LoginResponse(
        String token,
        Long userId,
        String username,
        long expiresAtEpochSeconds) {
}
