package ${package}.common.security;

import ${package}.common.core.ErrorCode;

/**
 * Security error codes (generated by engineering-platform ${asset.version}).
 * Consumes Platform Core ErrorCode — no duplicate error model.
 */
public final class SecurityErrorCodes {

    private SecurityErrorCodes() {
    }

    public static final ErrorCode UNAUTHENTICATED =
            ErrorCode.of("UNAUTHENTICATED", "authentication required");
    public static final ErrorCode INVALID_CREDENTIALS =
            ErrorCode.of("INVALID_CREDENTIALS", "invalid username or password");
    public static final ErrorCode TOKEN_EXPIRED =
            ErrorCode.of("TOKEN_EXPIRED", "token expired");
    public static final ErrorCode TOKEN_INVALID =
            ErrorCode.of("TOKEN_INVALID", "invalid token");
    public static final ErrorCode USER_DISABLED =
            ErrorCode.of("USER_DISABLED", "user disabled");
    public static final ErrorCode PERMISSION_DENIED =
            ErrorCode.of("PERMISSION_DENIED", "permission denied");
}
