package ${package}.infrastructure.security;

import ${package}.common.core.ApiResponse;
import ${package}.common.core.ErrorCode;
import ${package}.common.core.PlatformException;
import ${package}.common.security.SecurityErrorCodes;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

/**
 * Security exception mapping (generated by engineering-platform ${asset.version}).
 * Maps PlatformException with security error codes to unified safe HTTP responses.
 * Never leaks password hash, token secret, or internal stacktrace.
 * Ordered before the generic GlobalExceptionHandler so security errors are not
 * swallowed into 500 INTERNAL_ERROR.
 */
@RestControllerAdvice
@Order(Ordered.HIGHEST_PRECEDENCE)
public class SecurityExceptionHandler {

    @ExceptionHandler(PlatformException.class)
    public ResponseEntity<ApiResponse<Void>> handlePlatformException(PlatformException ex) {
        ErrorCode code = ex.errorCode();
        HttpStatus status = httpStatusFor(code);
        ApiResponse<Void> body = ApiResponse.ofError(code, safeMessage(code, ex));
        return ResponseEntity.status(status).body(body);
    }

    private HttpStatus httpStatusFor(ErrorCode code) {
        if (code == null) {
            return HttpStatus.INTERNAL_SERVER_ERROR;
        }
        String c = code.code();
        // business "not found" semantics -> 404 (Product/User/Role/Dept/Menu/Dictionary/Permission...)
        if (c.endsWith("NOT_FOUND")) {
            return HttpStatus.NOT_FOUND;
        }
        switch (c) {
            case "UNAUTHENTICATED":
            case "INVALID_CREDENTIALS":
            case "TOKEN_INVALID":
            case "TOKEN_EXPIRED":
                return HttpStatus.UNAUTHORIZED;
            case "USER_DISABLED":
            case "PERMISSION_DENIED":
                return HttpStatus.FORBIDDEN;
            default:
                return HttpStatus.BAD_REQUEST;
        }
    }

    private String safeMessage(ErrorCode code, PlatformException ex) {
        // only the stable error message / safe detail is exposed
        if (ex != null && ex.safeDetail() != null && !ex.safeDetail().isBlank()) {
            return ex.safeDetail();
        }
        return code == null ? "internal error" : code.message();
    }
}
