package ${package}.infrastructure.security;

import ${package}.common.core.CurrentClock;
import ${package}.common.core.IdGenerator;
import ${package}.common.security.TokenService;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.InterceptorRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

/**
 * Security web configuration (generated by engineering-platform ${asset.version}).
 * Secret comes from environment reference (never committed).
 */
@Configuration
public class SecurityWebConfig implements WebMvcConfigurer {

    // Secret comes from environment reference (never committed).
    // SpEL form avoids dollar-brace collision with the template renderer.
    @Value("#{environment['auth.token.secret']}")
    private String tokenSecret;

    @Value("#{environment['auth.token.expiration-seconds'] ?: 3600}")
    private long expirationSeconds;

    @Bean
    public TokenService tokenService() {
        return new TokenService(tokenSecret, expirationSeconds, CurrentClock.system(), IdGenerator.uuid());
    }

    @Bean
    public AuthInterceptor authInterceptor(TokenService tokenService) {
        return new AuthInterceptor(tokenService);
    }

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(authInterceptor(tokenService()))
                .addPathPatterns("/api/**")
                .excludePathPatterns("/api/auth/login");
    }
}
