import { createApp } from 'vue';
import { createPinia } from 'pinia';
import ElementPlus from 'element-plus';
import 'element-plus/dist/index.css';
import App from './App.vue';
import router from './router';
import { configureRequestClient } from './api/request';
import { useAuthStore } from './stores/auth';
import { installPermissionDirective } from './permission';
import './styles/tokens.css';

// V0.5 application bootstrap (generated by engineering-platform frontend-auth asset)
const app = createApp(App);
app.use(createPinia());
app.use(router);
app.use(ElementPlus);
installPermissionDirective(app);

const auth = useAuthStore();
configureRequestClient({
  getToken: () => auth.token,
  onUnauthorized: () => {
    auth.logout();
    if (router.currentRoute.value.name !== 'login') {
      router.push({ path: '/login', query: { redirect: router.currentRoute.value.fullPath } });
    }
  },
});

app.mount('#app');
