package ${package}.common.core;

import java.time.Instant;

/**
 * Testable clock abstraction (generated by engineering-platform ${asset.version}).
 * Production: system clock. Test: fixed clock. No complex time framework.
 */
public interface CurrentClock {

    Instant now();

    static CurrentClock system() {
        return SystemClock.INSTANCE;
    }

    static CurrentClock fixed(Instant fixed) {
        return new FixedClock(fixed);
    }

    final class SystemClock implements CurrentClock {
        private static final SystemClock INSTANCE = new SystemClock();

        private SystemClock() {
        }

        @Override
        public Instant now() {
            return Instant.now();
        }
    }

    final class FixedClock implements CurrentClock {
        private final Instant fixed;

        private FixedClock(Instant fixed) {
            this.fixed = fixed;
        }

        @Override
        public Instant now() {
            return fixed;
        }
    }
}
