package ${package}.common.core;

/**
 * Stable error code (generated by engineering-platform ${asset.version}).
 * Intentionally minimal: code + message. Framework-neutral, no HTTP transport detail.
 */
public record ErrorCode(String code, String message) {

    public static ErrorCode of(String code, String message) {
        return new ErrorCode(code, message);
    }
}
