package ${package}.api.health;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.Map;

/**
 * Lightweight readiness endpoint (generated by engineering-platform ${asset.version}).
 *
 * Runtime Recipe / Browser E2E readiness probe: no actuator, no observability
 * stack — a stable, anonymous HTTP endpoint returning HTTP 200 when the
 * application context is up. `/api/health` is the only anonymous endpoint
 * besides `/api/auth/login`.
 */
@RestController
@RequestMapping("/api/health")
public class HealthController {

    @GetMapping
    public Map<String, Object> health() {
        return Map.of(
                "status", "UP",
                "service", "generated-app");
    }
}
