package ${package}.common.core;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

import java.io.IOException;

/**
 * Long-from-String deserializer (generated by engineering-platform ${asset.version}).
 *
 * API Boundary ID String Contract: request payloads carry domain IDs as JSON
 * strings (Snowflake IDs exceed JS Number.MAX_SAFE_INTEGER). This deserializer
 * parses a JSON string (or number) back into a precise Long.
 *
 * Usage on request DTO ID fields:
 *   @JsonDeserialize(using = LongIdDeserializer.class) Long departmentId
 */
public final class LongIdDeserializer extends JsonDeserializer<Long> {

    @Override
    public Long deserialize(JsonParser parser, DeserializationContext ctx) throws IOException {
        String raw = parser.getText(); // works for both JSON string and number tokens
        if (raw == null || raw.isBlank()) {
            return null;
        }
        try {
            return Long.parseLong(raw.trim());
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("invalid id value: " + raw, e);
        }
    }
}
