package ${package}.common.core;

import java.time.Instant;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Real consumption of Platform Core contracts (generated by engineering-platform ${asset.version}).
 * Proves ApiResponse / PageResult / PlatformException / CurrentClock / IdGenerator are
 * compilable and testable inside the generated project.
 */
class PlatformCoreConsumptionTest {

    @Test
    void apiResponseSuccessCarriesData() {
        ApiResponse<String> ok = ApiResponse.ofSuccess("hello");
        assertThat(ok.success()).isTrue();
        assertThat(ok.data()).isEqualTo("hello");
        assertThat(ok.error()).isNull();
    }

    @Test
    void apiResponseFailureCarriesErrorCode() {
        ErrorCode code = ErrorCode.of("AUTH_FAILED", "authentication failed");
        ApiResponse<Void> err = ApiResponse.ofError(code);
        assertThat(err.success()).isFalse();
        assertThat(err.error()).isEqualTo(code);
        assertThat(err.message()).isEqualTo("authentication failed");
    }

    @Test
    void platformExceptionCarriesErrorCode() {
        ErrorCode code = ErrorCode.of("PERMISSION_DENIED", "no permission");
        PlatformException ex = new PlatformException(code, "user lacks role admin");
        assertThat(ex.errorCode()).isEqualTo(code);
        assertThat(ex.safeDetail()).isEqualTo("user lacks role admin");
        assertThatThrownBy(() -> {
            throw ex;
        }).isInstanceOf(PlatformException.class);
    }

    @Test
    void pageQueryClampsInvalidBounds() {
        PageQuery q = PageQuery.of(0, -5);
        assertThat(q.page()).isEqualTo(PageQuery.DEFAULT_PAGE);
        assertThat(q.size()).isEqualTo(PageQuery.DEFAULT_SIZE);
        assertThat(PageQuery.of(2, 10).offset()).isEqualTo(10);
        assertThat(PageQuery.of(3, 99999).size()).isEqualTo(PageQuery.MAX_SIZE);
    }

    @Test
    void pageResultBehavior() {
        PageResult<String> r = PageResult.of(List.of("a", "b"), 5, 1, 2);
        assertThat(r.items()).hasSize(2);
        assertThat(r.total()).isEqualTo(5);
        assertThat(r.page()).isEqualTo(1);
        assertThat(r.size()).isEqualTo(2);
        PageResult<String> empty = PageResult.empty(PageQuery.defaults());
        assertThat(empty.items()).isEmpty();
        assertThat(empty.total()).isZero();
    }

    @Test
    void requestContextBasicBehavior() {
        RequestContext.clear();
        assertThat(RequestContext.requestId()).isEmpty();
        RequestContext.set(RequestContext.Context.of("req-1", "corr-1"));
        assertThat(RequestContext.requestId()).contains("req-1");
        assertThat(RequestContext.correlationId()).contains("corr-1");
        assertThat(RequestContext.metadata()).isEmpty();
        RequestContext.clear();
        assertThat(RequestContext.requestId()).isEmpty();
    }

    @Test
    void currentClockFixedReturnsFixedInstant() {
        Instant fixed = Instant.parse("2026-01-01T00:00:00Z");
        CurrentClock clock = CurrentClock.fixed(fixed);
        assertThat(clock.now()).isEqualTo(fixed);
    }

    @Test
    void idGeneratorProducesUniqueIds() {
        IdGenerator gen = IdGenerator.uuid();
        Set<String> ids = new HashSet<>();
        for (int i = 0; i < 200; i++) {
            ids.add(gen.nextId());
        }
        assertThat(ids).hasSize(200);
        assertThat(IdGenerator.monotonic("id").nextId()).startsWith("id-");
    }
}
