package ${package}.common.core;

/**
 * Platform exception carrying a stable {@link ErrorCode} (generated by engineering-platform ${asset.version}).
 * May hold an optional safe detail/context for clients. Never holds sensitive information.
 */
public class PlatformException extends RuntimeException {

    private final ErrorCode errorCode;
    private final String safeDetail;

    public PlatformException(ErrorCode errorCode) {
        this(errorCode, null, null);
    }

    public PlatformException(ErrorCode errorCode, String safeDetail) {
        this(errorCode, safeDetail, null);
    }

    public PlatformException(ErrorCode errorCode, String safeDetail, Throwable cause) {
        super(errorCode == null ? null : errorCode.message(), cause);
        this.errorCode = errorCode;
        this.safeDetail = safeDetail;
    }

    public ErrorCode errorCode() {
        return errorCode;
    }

    /** Optional safe detail for clients; never sensitive. */
    public String safeDetail() {
        return safeDetail;
    }
}
