/* Enterprise UX tokens (generated by engineering-platform frontend-auth asset)
 * V0.5 UX baseline: spacing / layout / typography / semantic states.
 * Prefer these tokens over ad-hoc px values in business pages.
 */
:root {
  /* spacing scale: 4/8/12/16/24/32 */
  --ep-space-1: 4px;
  --ep-space-2: 8px;
  --ep-space-3: 12px;
  --ep-space-4: 16px;
  --ep-space-5: 24px;
  --ep-space-6: 32px;

  /* layout */
  --ep-sidebar-width: 220px;
  --ep-sidebar-width-collapsed: 64px;
  --ep-header-height: 56px;
  --ep-content-max-width: 1200px;

  /* typography */
  --ep-font-size-sm: 12px;
  --ep-font-size-base: 14px;
  --ep-font-size-lg: 16px;
  --ep-font-size-xl: 20px;

  /* radius */
  --ep-radius-sm: 4px;
  --ep-radius-base: 6px;
  --ep-radius-lg: 8px;

  /* surface */
  --ep-surface: #f5f7fa;
  --ep-surface-elevated: #ffffff;

  /* semantic */
  --ep-color-danger: #f56c6c;
  --ep-color-success: #67c23a;
  --ep-color-warning: #e6a23c;
  --ep-color-info: #909399;
}
