// Product routes (generated by engineering-platform frontend-product-reference asset)
// Controlled registry aligned with backend menu.path (/products). The router
// (frontend-auth) loads this module via glob when the asset is present.
import type { RouteRecordRaw } from 'vue-router';

export const productRoutes: RouteRecordRaw[] = [
  {
    path: '/products',
    name: 'products',
    component: () => import('../views/product/ProductListView.vue'),
    meta: { title: 'Products', permission: 'product:item:read' },
  },
  {
    path: '/products/:id',
    name: 'product-detail',
    component: () => import('../views/product/ProductDetailView.vue'),
    meta: { title: 'Product Detail', permission: 'product:item:read' },
  },
  {
    path: '/products/:id/edit',
    name: 'product-edit',
    component: () => import('../views/product/ProductEditView.vue'),
    meta: { title: 'Edit Product', permission: 'product:item:update' },
  },
];
