<script setup lang="ts">
// AppTable (generated by engineering-platform frontend-enterprise-management asset)
// Unified data table: loading / empty / error / pagination / row actions / refresh.
// Row action layout: one primary action + a "more" dropdown for secondary ones
// (never a full row of buttons).
import { computed } from 'vue';
import { PageSize } from '../utils/table';

export interface RowAction {
  label: string;
  danger?: boolean;
  disabled?: boolean;
  onClick: () => void;
}

const props = withDefaults(
  defineProps<{
    loading?: boolean;
    error?: string | null;
    emptyText?: string;
    data: unknown[];
    total: number;
    page: number;
    size: number;
    /** Primary (high-frequency) action shown directly. */
    primaryAction?: RowAction | null;
    /** Secondary (low-frequency) actions collapsed into a "more" menu. */
    moreActions?: RowAction[];
    rowKey?: string;
  }>(),
  {
    loading: false,
    error: null,
    emptyText: 'No data',
    primaryAction: null,
    moreActions: () => [],
    rowKey: 'id',
  },
);

const emit = defineEmits<{
  refresh: [];
  'update:page': [page: number];
  'update:size': [size: number];
}>();

const hasMore = computed(() => (props.moreActions ?? []).some((a) => !a.disabled));

function onPrimaryClick(): void {
  props.primaryAction?.onClick();
}
</script>

<template>
  <div class="app-table" data-testid="app-table">
    <div v-if="error" class="app-table-error" data-testid="app-table-error">
      <el-tag type="danger">{{ error }}</el-tag>
      <el-button size="small" @click="emit('refresh')">Retry</el-button>
    </div>

    <el-table
      v-else
      v-loading="loading"
      :data="data"
      :row-key="rowKey"
      :empty-text="emptyText"
      data-testid="app-table-body"
    >
      <slot />

      <el-table-column v-if="primaryAction || hasMore" label="Actions" :width="150" fixed="right">
        <template #default>
          <el-button
            v-if="primaryAction"
            size="small"
            type="primary"
            link
            :disabled="primaryAction.disabled"
            @click="onPrimaryClick"
          >
            {{ primaryAction.label }}
          </el-button>
          <el-dropdown v-if="hasMore" trigger="click" data-testid="row-more-menu">
            <el-button size="small" link>More<el-icon class="el-icon--right"><arrow-down /></el-icon></el-button>
            <template #dropdown>
              <el-dropdown-menu>
                <el-dropdown-item
                  v-for="action in moreActions"
                  :key="action.label"
                  :disabled="action.disabled"
                  :class="{ 'is-danger': action.danger }"
                  @click="action.onClick"
                >
                  {{ action.label }}
                </el-dropdown-item>
              </el-dropdown-menu>
            </template>
          </el-dropdown>
        </template>
      </el-table-column>
    </el-table>

    <div v-if="!error && total > 0" class="app-table-pagination">
      <el-pagination
        :current-page="page"
        :page-size="size"
        :total="total"
        :page-sizes="PageSize"
        layout="total, sizes, prev, pager, next"
        @current-change="(p: number) => emit('update:page', p)"
        @size-change="(s: number) => emit('update:size', s)"
      />
    </div>
  </div>
</template>

<style scoped>
.app-table-error {
  display: flex;
  align-items: center;
  gap: var(--ep-space-3);
  padding: var(--ep-space-4);
  border: 1px solid var(--el-color-danger-light-7);
  border-radius: var(--ep-radius);
}
.app-table-pagination {
  display: flex;
  justify-content: flex-end;
  padding-top: var(--ep-space-4);
}
</style>
