<script setup lang="ts">
// EditableDetailTable (generated by engineering-platform frontend-enterprise-management asset)
// V07-WORK-003: generic master/detail editable table. Renders child rows with
// per-column editors (reference/select/date/money/number/text) plus Add Row /
// Remove Row. Column definitions come from the generated module contract —
// nothing here knows a concrete business name.
// V07-WORK-006 blocker fix: import the generic field-semantic renderers this
// template actually renders (reference -> ReferenceSelect, money -> MoneyInput).
// Import set is fixed to what the template uses — no per-module special cases.
import ReferenceSelect from './ReferenceSelect.vue';
import MoneyInput from './MoneyInput.vue';

export interface DetailColumn {
  prop: string;
  label: string;
  kind?: 'reference' | 'select' | 'date' | 'money' | 'number' | 'text';
  /** reference: target module api object + value/label fields */
  api?: { page: (q: Record<string, unknown>) => Promise<{ items?: Array<Record<string, unknown>> }> };
  valueField?: string;
  labelField?: string;
  /** select: static options (enum values from the Contract) */
  options?: Array<{ value: string | number; label: string }>;
  required?: boolean;
  width?: number;
}

const props = withDefaults(
  defineProps<{
    columns: DetailColumn[];
    modelValue: Array<Record<string, unknown>>;
    addText?: string;
    removeText?: string;
    disabled?: boolean;
  }>(),
  {
    addText: 'Add Row',
    removeText: 'Remove',
    disabled: false,
  },
);

const emit = defineEmits<{
  'update:modelValue': [rows: Array<Record<string, unknown>>];
}>();

function newRow(): Record<string, unknown> {
  const row: Record<string, unknown> = {};
  for (const col of props.columns) {
    row[col.prop] = col.kind === 'number' || col.kind === 'money' ? null : '';
  }
  return row;
}

function addRow(): void {
  emit('update:modelValue', [...props.modelValue, newRow()]);
}

function removeRow(index: number): void {
  const rows = props.modelValue.slice();
  rows.splice(index, 1);
  emit('update:modelValue', rows);
}

function setCell(index: number, prop: string, value: unknown): void {
  const rows = props.modelValue.map((row, i) => (i === index ? { ...row, [prop]: value } : row));
  emit('update:modelValue', rows);
}
</script>

<template>
  <div class="editable-detail-table" data-testid="editable-detail-table">
    <el-table :data="modelValue" border size="default" style="width: 100%">
      <el-table-column
        v-for="col in columns"
        :key="col.prop"
        :label="col.label"
        :min-width="col.width ?? 140"
      >
        <template #default="{ row, $index }">
          <ReferenceSelect
            v-if="col.kind === 'reference' && col.api"
            :api="col.api"
            :value-field="col.valueField ?? 'id'"
            :label-field="col.labelField ?? 'name'"
            :model-value="(row[col.prop] as string | number | null) ?? null"
            :placeholder="col.label"
            data-testid="detail-ref"
            @update:model-value="setCell($index, col.prop, $event)"
          />
          <el-select
            v-else-if="col.kind === 'select'"
            :model-value="(row[col.prop] as string | number | null) ?? null"
            :placeholder="col.label"
            clearable
            style="width: 100%"
            data-testid="detail-select"
            @update:model-value="setCell($index, col.prop, $event ?? null)"
          >
            <el-option
              v-for="opt in (col.options ?? [])"
              :key="String(opt.value)"
              :label="opt.label"
              :value="opt.value"
            />
          </el-select>
          <el-date-picker
            v-else-if="col.kind === 'date'"
            :model-value="(row[col.prop] as string | null) ?? null"
            type="date"
            value-format="YYYY-MM-DD"
            :placeholder="col.label"
            style="width: 100%"
            data-testid="detail-date"
            @update:model-value="setCell($index, col.prop, $event ?? null)"
          />
          <MoneyInput
            v-else-if="col.kind === 'money'"
            :model-value="(row[col.prop] as number | null) ?? null"
            :precision="2"
            data-testid="detail-money"
            @update:model-value="setCell($index, col.prop, $event)"
          />
          <el-input-number
            v-else-if="col.kind === 'number'"
            :model-value="(row[col.prop] as number | null) ?? null"
            :min="0"
            :controls="false"
            style="width: 100%"
            data-testid="detail-number"
            @update:model-value="setCell($index, col.prop, $event ?? null)"
          />
          <el-input
            v-else
            :model-value="(row[col.prop] as string | null) ?? ''"
            :placeholder="col.label"
            data-testid="detail-text"
            @update:model-value="setCell($index, col.prop, $event)"
          />
        </template>
      </el-table-column>
      <el-table-column label="" width="90" fixed="right">
        <template #default="{ $index }">
          <el-button link type="danger" data-testid="detail-remove-row" @click="removeRow($index)">
            {{ removeText }}
          </el-button>
        </template>
      </el-table-column>
    </el-table>
    <div class="editable-detail-table-actions">
      <el-button type="primary" plain data-testid="detail-add-row" @click="addRow" :disabled="disabled">
        {{ addText }}
      </el-button>
    </div>
  </div>
</template>

<style scoped>
.editable-detail-table {
  width: 100%;
}
.editable-detail-table-actions {
  margin-top: var(--ep-space-3);
  display: flex;
  justify-content: flex-end;
}
</style>
