<script setup lang="ts">
// FormDrawer (generated by engineering-platform frontend-enterprise-management asset)
// Medium-size edit surface: Drawer with header + body + stable footer.
// Drawer is the default for create/edit; complex configuration gets a page.

withDefaults(
  defineProps<{
    modelValue: boolean;
    title: string;
    width?: string;
    destroyOnClose?: boolean;
  }>(),
  { width: '520px', destroyOnClose: true },
);
const emit = defineEmits<{ 'update:modelValue': [value: boolean] }>();

function onClose(): void {
  emit('update:modelValue', false);
}
</script>

<template>
  <el-drawer
    :model-value="modelValue"
    :title="title"
    :size="width"
    :destroy-on-close="destroyOnClose"
    data-testid="form-drawer"
    @close="onClose"
  >
    <div class="form-drawer-body">
      <slot />
    </div>
  </el-drawer>
</template>

<style scoped>
.form-drawer-body {
  display: flex;
  flex-direction: column;
  min-height: 100%;
}
</style>
