<script setup lang="ts">
// MoneyText (generated by engineering-platform frontend-enterprise-management asset)
// V07-WORK-003: generic money display — thousands separators + fixed decimals.
import { computed } from 'vue';

const props = withDefaults(
  defineProps<{
    value?: number | string | null;
    precision?: number;
    emptyText?: string;
  }>(),
  {
    value: null,
    precision: 2,
    emptyText: '—',
  },
);

const display = computed(() => {
  if (props.value === null || props.value === undefined || props.value === '') {
    return props.emptyText;
  }
  const num = Number(props.value);
  if (Number.isNaN(num)) return props.emptyText;
  return num.toLocaleString('en-US', {
    minimumFractionDigits: props.precision,
    maximumFractionDigits: props.precision,
  });
});
</script>

<template>
  <span class="money-text" data-testid="money-text">{{ display }}</span>
</template>

<style scoped>
.money-text {
  font-variant-numeric: tabular-nums;
  font-weight: var(--ep-font-weight-medium);
}
</style>
