<script setup lang="ts">
// MoneyInput (generated by engineering-platform frontend-enterprise-management asset)
// V07-WORK-003: generic money input — decimal precision + thousands separators.
import { computed } from 'vue';

const props = withDefaults(
  defineProps<{
    modelValue?: number | string | null;
    precision?: number;
    placeholder?: string;
    disabled?: boolean;
    min?: number;
    max?: number;
  }>(),
  {
    modelValue: null,
    precision: 2,
    placeholder: '0.00',
    disabled: false,
    min: undefined,
    max: undefined,
  },
);

const emit = defineEmits<{
  'update:modelValue': [value: number | null];
}>();

const display = computed<number | undefined>(() => {
  if (props.modelValue === null || props.modelValue === undefined || props.modelValue === '') {
    return undefined;
  }
  const num = Number(props.modelValue);
  return Number.isNaN(num) ? undefined : num;
});

function onChange(value: number | undefined): void {
  emit('update:modelValue', value ?? null);
}
</script>

<template>
  <el-input-number
    :model-value="display"
    :precision="precision"
    :controls="false"
    :placeholder="placeholder"
    :disabled="disabled"
    :min="min"
    :max="max"
    style="width: 100%"
    data-testid="money-input"
    @update:model-value="onChange"
  />
</template>

<style scoped>
:deep(.el-input-number .el-input__inner) {
  text-align: left;
}
</style>
