<script setup lang="ts">
// ReferenceSelect (generated by engineering-platform frontend-enterprise-management asset)
// V07-WORK-003: generic remote reference selector — loads options from the target
// module page API, maps valueField/labelField, supports remote keyword search.
// V07-WORK-006 blocker fix: consume the platform canonical PageResult shape
// ({ items, total, page, size } — see types/enterprise.ts). No legacy shapes.
import { onMounted, ref, watch } from 'vue';

const props = withDefaults(
  defineProps<{
    api: {
      page: (q: Record<string, unknown>) => Promise<{ items?: Array<Record<string, unknown>> }>;
    };
    valueField?: string;
    labelField?: string;
    searchFields?: string[];
    modelValue?: string | number | null;
    placeholder?: string;
    clearable?: boolean;
    disabled?: boolean;
    size?: number;
  }>(),
  {
    valueField: 'id',
    labelField: 'name',
    searchFields: () => ['name'],
    modelValue: null,
    placeholder: 'Select',
    clearable: false,
    disabled: false,
    size: 50,
  },
);

const emit = defineEmits<{
  'update:modelValue': [value: string | number | null];
}>();

const options = ref<Array<Record<string, unknown>>>([]);
const loading = ref(false);
const error = ref<string | null>(null);
const keyword = ref('');

async function load(): Promise<void> {
  loading.value = true;
  error.value = null;
  try {
    const q: Record<string, unknown> = { page: 1, size: props.size };
    if (keyword.value) q.keyword = keyword.value;
    const data = await props.api.page(q);
    options.value = data.items ?? [];
  } catch (e) {
    error.value = e instanceof Error ? e.message : 'Failed to load options';
  } finally {
    loading.value = false;
  }
}

function onSelect(value: string | number | null): void {
  emit('update:modelValue', value);
}

function labelOf(row: Record<string, unknown>): string {
  return String(row[props.labelField] ?? row[props.valueField] ?? '');
}

function onSearch(q: string): void {
  keyword.value = q;
}

watch(keyword, () => {
  load();
});

onMounted(load);

defineExpose({ load, options });
</script>

<template>
  <el-select
    :model-value="modelValue"
    :placeholder="placeholder"
    :clearable="clearable"
    :disabled="disabled"
    :loading="loading"
    filterable
    remote
    :remote-method="onSearch"
    style="width: 100%"
    data-testid="reference-select"
    @update:model-value="onSelect"
  >
    <el-option
      v-for="opt in options"
      :key="String(opt[valueField])"
      :label="labelOf(opt)"
      :value="opt[valueField]"
    />
  </el-select>
  <div v-if="error" class="reference-select-error" data-testid="reference-select-error">{{ error }}</div>
</template>

<style scoped>
.reference-select-error {
  font-size: var(--ep-font-size-xs);
  color: var(--ep-color-danger);
  margin-top: 4px;
}
</style>
