<script setup lang="ts">
// SearchForm (generated by engineering-platform frontend-enterprise-management asset)
// Unified filter bar: common filters always visible; low-frequency filters fold
// into "More filters". Search + Reset. Pages never invent their own layout.
import { ref } from 'vue';

withDefaults(defineProps<{ more?: boolean }>(), { more: false });
const emit = defineEmits<{ search: []; reset: [] }>();

const expanded = ref(false);
</script>

<template>
  <div class="search-form" data-testid="search-form">
    <div class="search-form-fields">
      <slot name="default" />
      <slot v-if="expanded" name="more" />
    </div>
    <div class="search-form-actions">
      <el-button type="primary" data-testid="search-form-submit" @click="emit('search')">Search</el-button>
      <el-button data-testid="search-form-reset" @click="emit('reset')">Reset</el-button>
      <el-button v-if="more" text @click="expanded = !expanded">
        {{ expanded ? 'Less filters' : 'More filters' }}
        <el-icon class="el-icon--right">
          <component :is="expanded ? 'ArrowUp' : 'ArrowDown'" />
        </el-icon>
      </el-button>
    </div>
  </div>
</template>

<style scoped>
.search-form {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: var(--ep-space-4);
  padding: var(--ep-space-4);
  background: var(--ep-surface);
  border: 1px solid var(--el-border-color-lighter);
  border-radius: var(--ep-radius);
  margin-bottom: var(--ep-space-5);
}
.search-form-fields {
  display: flex;
  flex-wrap: wrap;
  gap: var(--ep-space-3);
  flex: 1;
}
.search-form-actions {
  display: flex;
  align-items: center;
  gap: var(--ep-space-2);
  white-space: nowrap;
}
</style>
