<script setup lang="ts">
// StatusTag (generated by engineering-platform frontend-enterprise-management asset)
// Unified Enabled/Disabled status expression across User/Role/Department/Menu/Dictionary.
import { computed } from 'vue';

const props = withDefaults(defineProps<{ enabled: boolean; activeText?: string; inactiveText?: string }>(), {
  activeText: 'Enabled',
  inactiveText: 'Disabled',
});

const tagType = computed(() => (props.enabled ? 'success' : 'info'));
const label = computed(() => (props.enabled ? props.activeText : props.inactiveText));
</script>

<template>
  <el-tag :type="tagType" size="small" data-testid="status-tag">
    {{ label }}
  </el-tag>
</template>
