<script setup lang="ts">
// Supplier List (generated by engineering-platform frontend-supplier-reference asset)
// Reference business module: list + search/filter + create/edit drawer + disable.
// Status/Category filters and form selects are driven by real Dictionary API.
import { onMounted, reactive, ref } from 'vue';
import { useRouter } from 'vue-router';
import PageHeader from '../../components/PageHeader.vue';
import PageContainer from '../../components/PageContainer.vue';
import SearchForm from '../../components/SearchForm.vue';
import AppTable from '../../components/AppTable.vue';
import StatusTag from '../../components/StatusTag.vue';
import ConfirmAction from '../../components/ConfirmAction.vue';
import FormDrawer from '../../components/FormDrawer.vue';
import AppForm from '../../components/AppForm.vue';
import DictionarySelect from '../../components/DictionarySelect.vue';
import PermissionButton from '../../permission/PermissionButton.vue';
import { supplierApi } from '../../api/supplier';
import type { Supplier } from '../../types/supplier';
import { errorMessage, notifySuccess, toastSuccess } from '../../utils/feedback';

const router = useRouter();
const loading = ref(false);
const listError = ref<string | null>(null);
const suppliers = ref<Supplier[]>([]);
const total = ref(0);
const page = ref(1);
const size = ref(20);

const filters = reactive({ keyword: '', status: '', category: '' });

// drawer state
const drawerOpen = ref(false);
const editing = ref<Supplier | null>(null);
const submitting = ref(false);
const formError = ref<string | null>(null);
const form = reactive({ code: '', name: '', status: 'ENABLED', category: '' });

async function load(): Promise<void> {
  loading.value = true;
  listError.value = null;
  try {
    const result = await supplierApi.page({
      page: page.value,
      size: size.value,
      keyword: filters.keyword || undefined,
      status: filters.status || undefined,
      category: filters.category || undefined,
    });
    suppliers.value = result.items;
    total.value = result.total;
  } catch (e) {
    listError.value = errorMessage(e);
  } finally {
    loading.value = false;
  }
}

function resetFilters(): void {
  filters.keyword = '';
  filters.status = '';
  filters.category = '';
  page.value = 1;
  load();
}

function openCreate(): void {
  editing.value = null;
  formError.value = null;
  Object.assign(form, { code: '', name: '', status: 'ENABLED', category: '' });
  drawerOpen.value = true;
}

function openEdit(p: Supplier): void {
  editing.value = p;
  formError.value = null;
  Object.assign(form, { code: p.code, name: p.name, status: p.status, category: p.category ?? '' });
  drawerOpen.value = true;
}

async function submit(): Promise<void> {
  submitting.value = true;
  formError.value = null;
  const body = {
    code: form.code,
    name: form.name,
    status: form.status,
    category: form.category || null,
  };
  try {
    if (editing.value) {
      await supplierApi.update(editing.value.id, body);
      notifySuccess('Supplier updated');
    } else {
      await supplierApi.create(body);
      notifySuccess('Supplier created');
    }
    drawerOpen.value = false;
    await load();
  } catch (e) {
    formError.value = errorMessage(e);
  } finally {
    submitting.value = false;
  }
}

async function doDisable(p: Supplier): Promise<void> {
  try {
    await supplierApi.disable(p.id);
    toastSuccess('Supplier disabled');
    await load();
  } catch (e) {
    toastSuccess(errorMessage(e));
  }
}

onMounted(load);
</script>

<template>
  <PageContainer full-width>
    <PageHeader title="Suppliers" description="Reference business module — supplier catalog with data-scope enforcement.">
      <template #actions>
        <PermissionButton permission="supplier:item:create" type="primary" data-testid="create-supplier" @click="openCreate">
          Create Supplier
        </PermissionButton>
      </template>
    </PageHeader>

    <SearchForm more @search="load" @reset="resetFilters">
      <el-input
        v-model="filters.keyword"
        placeholder="Search code or name"
        clearable
        style="width: 240px"
        data-testid="supplier-search-keyword"
      />
      <DictionarySelect
        v-model="filters.status"
        code="supplier_status"
        placeholder="Status"
        clearable
        data-testid="supplier-filter-status"
      />
      <template #more>
        <DictionarySelect
          v-model="filters.category"
          code="supplier_category"
          placeholder="Category"
          clearable
          data-testid="supplier-filter-category"
        />
      </template>
    </SearchForm>

    <AppTable
      :loading="loading"
      :error="listError"
      :data="suppliers"
      :total="total"
      :page="page"
      :size="size"
      @refresh="load"
      @update:page="(p: number) => { page = p; load(); }"
      @update:size="(s: number) => { size = s; page = 1; load(); }"
    >
      <el-table-column prop="code" label="Code" min-width="130" />
      <el-table-column prop="name" label="Name" min-width="180" />
      <el-table-column label="Status" width="110">
        <template #default="{ row }">
          <StatusTag :enabled="row.status === 'ENABLED'" active-text="Enabled" inactive-text="Disabled" />
        </template>
      </el-table-column>
      <el-table-column prop="category" label="Category" min-width="130">
        <template #default="{ row }">{{ row.category ?? '—' }}</template>
      </el-table-column>
      <el-table-column prop="departmentId" label="Department" width="120">
        <template #default="{ row }">{{ row.departmentId ?? '—' }}</template>
      </el-table-column>
      <el-table-column prop="createdBy" label="Created by" width="110">
        <template #default="{ row }">{{ row.createdBy ?? '—' }}</template>
      </el-table-column>
      <el-table-column label="Created at" min-width="160">
        <template #default="{ row }">{{ new Date(row.createdAt).toLocaleString() }}</template>
      </el-table-column>
      <el-table-column label="Actions" width="180" fixed="right">
        <template #default="{ row }">
          <el-button size="small" type="primary" link data-testid="supplier-detail-open" @click="router.push({ path: '/suppliers/' + row.id })">Detail</el-button>
          <el-button size="small" link data-testid="supplier-open" @click="openEdit(row)">Edit</el-button>
          <ConfirmAction
            v-if="row.status === 'ENABLED'"
            :title="'Disable ' + row.code + '?'"
            @confirm="doDisable(row)"
          >
            <PermissionButton permission="supplier:item:disable" size="small" type="danger" link data-testid="supplier-disable-trigger">Disable</PermissionButton>
          </ConfirmAction>
        </template>
      </el-table-column>
    </AppTable>

    <FormDrawer v-model="drawerOpen" :title="editing ? 'Edit Supplier' : 'Create Supplier'">
      <AppForm
        :model="form as unknown as Record<string, unknown>"
        :submitting="submitting"
        :error="formError"
        :submit-text="editing ? 'Save' : 'Create'"
        compact
        @submit="submit"
        @cancel="drawerOpen = false"
      >
        <el-form-item label="Code" :rules="[{ required: true, message: 'Code is required' }]">
          <el-input v-model="form.code" placeholder="e.g. SUP-100" data-testid="supplier-form-code" />
        </el-form-item>
        <el-form-item label="Name" :rules="[{ required: true, message: 'Name is required' }]">
          <el-input v-model="form.name" data-testid="supplier-form-name" />
        </el-form-item>
        <el-form-item label="Status">
          <DictionarySelect v-model="form.status" code="supplier_status" style="width: 100%" data-testid="supplier-form-status" />
        </el-form-item>
        <el-form-item label="Category">
          <DictionarySelect v-model="form.category" code="supplier_category" clearable style="width: 100%" data-testid="supplier-form-category" />
        </el-form-item>
        <div class="form-hint">Department and creator are set by the server from your session — never from the client.</div>
      </AppForm>
    </FormDrawer>
  </PageContainer>
</template>

<style scoped>
.form-hint {
  font-size: var(--ep-font-size-sm);
  color: var(--ep-color-info);
  padding: 0 var(--ep-space-2);
}
</style>
