<script setup lang="ts">
// Supplier Detail (generated by engineering-platform frontend-supplier-reference asset)
// Real detail workspace (not a disabled edit form): clear information hierarchy.
import { onMounted, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import PageHeader from '../../components/PageHeader.vue';
import PageContainer from '../../components/PageContainer.vue';
import StatusTag from '../../components/StatusTag.vue';
import ConfirmAction from '../../components/ConfirmAction.vue';
import PermissionButton from '../../permission/PermissionButton.vue';
import { supplierApi } from '../../api/supplier';
import type { Supplier } from '../../types/supplier';
import { errorMessage, notifySuccess, toastSuccess } from '../../utils/feedback';

const route = useRoute();
const router = useRouter();
const supplier = ref<Supplier | null>(null);
const loading = ref(false);
const error = ref<string | null>(null);
const notFound = ref(false);

async function load(): Promise<void> {
  loading.value = true;
  error.value = null;
  notFound.value = false;
  try {
    supplier.value = await supplierApi.detail(route.params.id as string);
  } catch (e) {
    error.value = errorMessage(e);
    if (e instanceof Error && 'status' in e && (e as { status: number }).status === 404) {
      notFound.value = true;
    }
  } finally {
    loading.value = false;
  }
}

async function disable(): Promise<void> {
  if (!supplier.value) {
    return;
  }
  try {
    await supplierApi.disable(supplier.value.id);
    notifySuccess('Supplier disabled');
    await load();
  } catch (e) {
    toastSuccess(errorMessage(e));
  }
}

function goBack(): void {
  router.push({ path: '/suppliers' });
}

onMounted(load);
</script>

<template>
  <PageContainer>
    <PageHeader
      :title="supplier ? supplier.code : 'Supplier Detail'"
      :description="supplier ? supplier.name : undefined"
    >
      <template #actions>
        <el-button data-testid="supplier-detail-back" @click="goBack">Back</el-button>
        <PermissionButton
          v-if="supplier"
          permission="supplier:item:update"
          data-testid="supplier-detail-edit"
          @click="router.push({ path: '/suppliers/' + supplier.id + '/edit' })"
        >
          Edit
        </PermissionButton>
        <ConfirmAction
          v-if="supplier && supplier.status === 'ENABLED'"
          :title="'Disable ' + supplier.code + '?'"
          data-testid="supplier-detail-disable-confirm"
          @confirm="disable"
        >
          <PermissionButton permission="supplier:item:disable" type="danger" plain data-testid="supplier-detail-disable">
            Disable
          </PermissionButton>
        </ConfirmAction>
      </template>
    </PageHeader>

    <div v-if="loading" class="detail-state" data-testid="supplier-detail-loading">Loading…</div>

    <el-result
      v-else-if="notFound"
      icon="warning"
      title="Supplier not found"
      sub-title="It may have been removed or is outside your data scope."
      data-testid="supplier-detail-notfound"
    >
      <template #extra>
        <el-button type="primary" @click="goBack">Back to list</el-button>
      </template>
    </el-result>

    <el-result
      v-else-if="error"
      icon="error"
      :title="error"
      data-testid="supplier-detail-error"
    >
      <template #extra>
        <el-button type="primary" data-testid="supplier-detail-retry" @click="load">Retry</el-button>
      </template>
    </el-result>

    <div v-else-if="supplier" class="supplier-detail" data-testid="supplier-detail">
      <section class="detail-section">
        <h3 class="detail-section-title">Basic information</h3>
        <dl class="detail-grid">
          <div class="detail-item"><dt>Code</dt><dd data-testid="detail-code">{{ supplier.code }}</dd></div>
          <div class="detail-item"><dt>Name</dt><dd data-testid="detail-name">{{ supplier.name }}</dd></div>
          <div class="detail-item">
            <dt>Status</dt>
            <dd><StatusTag :enabled="supplier.status === 'ENABLED'" active-text="Enabled" inactive-text="Disabled" /></dd>
          </div>
          <div class="detail-item"><dt>Category</dt><dd data-testid="detail-category">{{ supplier.category ?? '—' }}</dd></div>
        </dl>
      </section>

      <section class="detail-section">
        <h3 class="detail-section-title">Ownership</h3>
        <dl class="detail-grid">
          <div class="detail-item"><dt>Department</dt><dd data-testid="detail-department">{{ supplier.departmentId ?? '—' }}</dd></div>
          <div class="detail-item"><dt>Created by</dt><dd data-testid="detail-createdby">{{ supplier.createdBy ?? '—' }}</dd></div>
        </dl>
      </section>

      <section class="detail-section">
        <h3 class="detail-section-title">Audit</h3>
        <dl class="detail-grid">
          <div class="detail-item"><dt>Created at</dt><dd>{{ new Date(supplier.createdAt).toLocaleString() }}</dd></div>
          <div class="detail-item"><dt>Updated at</dt><dd>{{ new Date(supplier.updatedAt).toLocaleString() }}</dd></div>
        </dl>
      </section>
    </div>
  </PageContainer>
</template>

<style scoped>
.detail-state {
  padding: var(--ep-space-6);
  color: var(--ep-color-info);
}
.supplier-detail {
  display: grid;
  gap: var(--ep-space-5);
}
.detail-section {
  border: 1px solid var(--el-border-color-lighter);
  border-radius: var(--ep-radius);
  padding: var(--ep-space-5);
}
.detail-section-title {
  margin: 0 0 var(--ep-space-4);
  font-size: var(--ep-font-size-lg);
}
.detail-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: var(--ep-space-4);
  margin: 0;
}
.detail-item dt {
  font-size: var(--ep-font-size-sm);
  color: var(--ep-color-info);
  margin-bottom: var(--ep-space-1);
}
.detail-item dd {
  margin: 0;
  font-size: var(--ep-font-size-base);
}
</style>
