// Product types (generated by engineering-platform frontend-product-reference asset)
// Stable contract for the reference business module. No `any` in the typed surface.
import type { PageResult } from './enterprise';

export type { PageResult };

export interface Product {
  id: number;
  code: string;
  name: string;
  status: string; // dictionary value (product_status)
  category: string | null; // dictionary value (product_category)
  departmentId: number | null;
  createdBy: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface ProductCreateRequest {
  code: string;
  name: string;
  status: string;
  category: string | null;
}

export interface ProductUpdateRequest {
  code: string;
  name: string;
  status: string;
  category: string | null;
}

export interface ProductQuery {
  page?: number;
  size?: number;
  keyword?: string;
  status?: string;
  category?: string;
}

export type ProductPageResponse = PageResult<Product>;
