package ${package}.infrastructure.persistence;

import ${package}.application.operationlog.OperationLogPort;
import ${package}.domain.entity.SysOperationLog;
import ${package}.infrastructure.persistence.mapper.SysOperationLogMapper;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;

import java.util.List;

/**
 * MyBatis-Plus implementation of {@link OperationLogPort} (generated by engineering-platform ${asset.version}).
 * All MyBatis types stay confined here, in the infrastructure layer.
 */
public class MybatisOperationLogRepository implements OperationLogPort {

    private final SysOperationLogMapper operationLogMapper;

    public MybatisOperationLogRepository(SysOperationLogMapper operationLogMapper) {
        this.operationLogMapper = operationLogMapper;
    }

    @Override
    public void save(SysOperationLog entry) {
        operationLogMapper.insert(entry);
    }

    @Override
    public List<SysOperationLog> findLatest(int limit) {
        return operationLogMapper.selectList(new QueryWrapper<SysOperationLog>()
                .orderByDesc("id")
                .last("LIMIT " + Math.max(1, limit)));
    }
}
