package ${package}.api.operationlog;

import ${package}.application.operationlog.OperationLogPort;
import ${package}.common.core.ApiResponse;
import ${package}.common.core.PlatformException;
import ${package}.common.core.RequestContext;
import ${package}.common.security.OperationLog;
import ${package}.common.security.SecurityErrorCodes;
import ${package}.domain.entity.SysOperationLog;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * Operation log query API (generated by engineering-platform ${asset.version}).
 *
 * Read-only view of the most recent operation log entries (verification/testing
 * support). The log itself is written by OperationLogAspect via @OperationLog.
 */
@RestController
@RequestMapping("/api/operation-logs")
public class OperationLogReferenceController {

    private final OperationLogPort operationLogPort;

    public OperationLogReferenceController(OperationLogPort operationLogPort) {
        this.operationLogPort = operationLogPort;
    }

    @GetMapping("/latest")
    @OperationLog(operation = "QUERY_OPERATION_LOGS", resourceType = "OPERATION_LOG")
    public ApiResponse<List<SysOperationLog>> latest() {
        // management-style endpoint: anonymous requests are denied (401)
        RequestContext.currentUserId()
                .orElseThrow(() -> new PlatformException(SecurityErrorCodes.UNAUTHENTICATED));
        return ApiResponse.ofSuccess(operationLogPort.findLatest(20));
    }
}
