package ${package}.infrastructure.security;

import ${package}.application.operationlog.OperationLogPort;
import ${package}.common.core.RequestContext;
import ${package}.common.security.OperationLog;
import ${package}.common.security.OperationResult;
import ${package}.domain.entity.SysOperationLog;
import org.aspectj.lang.ProceedingJoinPoint;
import org.aspectj.lang.annotation.Around;
import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.reflect.MethodSignature;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import jakarta.servlet.http.HttpServletRequest;
import org.springframework.web.context.request.RequestContextHolder;
import org.springframework.web.context.request.ServletRequestAttributes;

import java.time.LocalDateTime;

/**
 * Operation log enforcement aspect (generated by engineering-platform ${asset.version}).
 *
 * Real enforcement chain:
 *   HTTP → authentication (AuthInterceptor sets RequestContext)
 *   → @OperationLog method → aspect records SUCCESS/FAILURE into sys_operation_log
 *
 * SENSITIVE-DATA SAFETY GATE (hard requirement):
 *   Only annotation metadata (operation, resourceType) + method/path +
 *   RequestContext metadata (userId/requestId/correlationId) are persisted.
 *   Request bodies, headers, parameters, response bodies, passwords, tokens,
 *   secrets, and environment variables are NEVER logged.
 *
 * FAIL-SAFE: if persistence fails, the aspect logs a warning and does NOT mask
 * the business exception or the successful return value.
 *
 * DESIGN DECISION (unauthenticated requests): an unauthenticated request has an
 * empty RequestContext (no currentUserId) — no operation log is written for it.
 * Authentication/RBAC stays authoritative; logging never weakens it.
 */
@Aspect
@Component
public class OperationLogAspect {

    private static final Logger log = LoggerFactory.getLogger(OperationLogAspect.class);

    private final OperationLogPort operationLogPort;

    public OperationLogAspect(OperationLogPort operationLogPort) {
        this.operationLogPort = operationLogPort;
    }

    @Around("@annotation(operationLog)")
    public Object record(ProceedingJoinPoint joinPoint, OperationLog operationLog) throws Throwable {
        try {
            Object result = joinPoint.proceed();
            write(joinPoint, operationLog, OperationResult.SUCCESS, null);
            return result;
        } catch (Throwable t) {
            write(joinPoint, operationLog, OperationResult.FAILURE, t);
            throw t;
        }
    }

    private void write(ProceedingJoinPoint joinPoint, OperationLog operationLog,
                       OperationResult result, Throwable failure) {
        try {
            // unauthenticated requests: empty RequestContext -> no log (design decision)
            String currentUserId = RequestContext.currentUserId().orElse(null);
            if (currentUserId == null) {
                return;
            }
            SysOperationLog entry = new SysOperationLog();
            entry.setUserId(Long.valueOf(currentUserId));
            entry.setOperation(operationLog.operation());
            entry.setResourceType(operationLog.resourceType());
            entry.setResult(result.code());
            entry.setRequestId(RequestContext.requestId().orElse(null));
            entry.setCorrelationId(RequestContext.correlationId().orElse(null));
            entry.setMethod(methodOf(joinPoint));
            entry.setPath(pathOf());
            entry.setOccurredAt(LocalDateTime.now());
            operationLogPort.save(entry);
        } catch (RuntimeException ex) {
            // fail-safe: log persistence failure must not mask business outcome
            log.warn("operation log persistence failed: {}", ex.getMessage());
        }
    }

    private String methodOf(ProceedingJoinPoint joinPoint) {
        if (joinPoint.getSignature() instanceof MethodSignature ms) {
            return ms.getMethod().getName();
        }
        if (joinPoint.getSignature() == null) {
            return "unknown";
        }
        return joinPoint.getSignature().getName();
    }

    private String pathOf() {
        var attrs = RequestContextHolder.getRequestAttributes();
        if (attrs instanceof ServletRequestAttributes servletAttrs) {
            HttpServletRequest request = servletAttrs.getRequest();
            return request.getMethod() + " " + request.getRequestURI();
        }
        return null;
    }
}
