package ${package};

import ${package}.application.operationlog.OperationLogPort;
import ${package}.common.core.RequestContext;
import ${package}.common.security.OperationLog;
import ${package}.common.security.OperationResult;
import ${package}.domain.entity.SysOperationLog;
import ${package}.infrastructure.security.OperationLogAspect;
import org.aspectj.lang.ProceedingJoinPoint;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Operation log model unit tests (generated by engineering-platform ${asset.version}).
 *
 * Covers: SUCCESS/FAILURE mapping, RequestContext metadata reuse,
 * sensitive-data exclusion (only safe metadata persisted),
 * fail-safe (persistence failure never masks business outcome),
 * unauthenticated request → no log (design decision),
 * RequestContext cleanup.
 */
class OperationLogModelUnitTest {

    @AfterEach
    void tearDown() {
        RequestContext.clear();
    }

    /** In-memory port capturing entries. */
    private static final class CapturingPort implements OperationLogPort {
        final List<SysOperationLog> entries = new ArrayList<>();
        RuntimeException failure;

        @Override
        public void save(SysOperationLog entry) {
            if (failure != null) {
                throw failure;
            }
            entries.add(entry);
        }

        @Override
        public List<SysOperationLog> findLatest(int limit) {
            return entries;
        }

        @Override
        public ${package}.common.core.PageResult<SysOperationLog> page(
                ${package}.common.core.PageQuery query, String userId, String operation,
                String resourceType, String result,
                java.time.LocalDateTime from, java.time.LocalDateTime to) {
            return ${package}.common.core.PageResult.of(entries, entries.size(),
                    query.page(), query.size());
        }
    }

    private static OperationLog opLog(String operation, String resourceType) {
        return new OperationLog() {
            @Override
            public Class<? extends java.lang.annotation.Annotation> annotationType() {
                return OperationLog.class;
            }

            @Override
            public String operation() {
                return operation;
            }

            @Override
            public String resourceType() {
                return resourceType;
            }
        };
    }

    private static ProceedingJoinPoint joinPoint() throws Throwable {
        ProceedingJoinPoint pjp = mock(ProceedingJoinPoint.class);
        when(pjp.proceed()).thenReturn("ok");
        return pjp;
    }

    private static ProceedingJoinPoint failingJoinPoint() throws Throwable {
        ProceedingJoinPoint pjp = mock(ProceedingJoinPoint.class);
        when(pjp.proceed()).thenThrow(new IllegalStateException("business boom"));
        return pjp;
    }

    // SUCCESS: business success -> SUCCESS log with RequestContext metadata
    @Test
    void successLoggedWithRequestContext() throws Throwable {
        RequestContext.set(RequestContext.Context.of("req-1", "corr-1", "42"));
        CapturingPort port = new CapturingPort();
        OperationLogAspect aspect = new OperationLogAspect(port);

        aspect.record(joinPoint(), opLog("CREATE_ORDER", "ORDER"));

        assertThat(port.entries).hasSize(1);
        SysOperationLog entry = port.entries.get(0);
        assertThat(entry.getUserId()).isEqualTo(42L);
        assertThat(entry.getOperation()).isEqualTo("CREATE_ORDER");
        assertThat(entry.getResourceType()).isEqualTo("ORDER");
        assertThat(entry.getResult()).isEqualTo(OperationResult.SUCCESS.code());
        assertThat(entry.getRequestId()).isEqualTo("req-1");
        assertThat(entry.getCorrelationId()).isEqualTo("corr-1");
        assertThat(entry.getOccurredAt()).isNotNull();
    }

    // FAILURE: business failure -> FAILURE log, exception rethrown
    @Test
    void failureLoggedAndExceptionRethrown() throws Throwable {
        RequestContext.set(RequestContext.Context.of("req-2", "corr-2", "7"));
        CapturingPort port = new CapturingPort();
        OperationLogAspect aspect = new OperationLogAspect(port);

        assertThatThrownBy(() -> aspect.record(failingJoinPoint(), opLog("CANCEL_ORDER", "ORDER")))
                .isInstanceOf(IllegalStateException.class)
                .hasMessage("business boom");

        assertThat(port.entries).hasSize(1);
        assertThat(port.entries.get(0).getResult()).isEqualTo(OperationResult.FAILURE.code());
    }

    // SENSITIVE-DATA GATE: password/token/secret never appear in the log entry
    @Test
    void sensitiveDataNeverPersisted() throws Throwable {
        RequestContext.set(RequestContext.Context.of("req-3", "corr-3", "1"));
        CapturingPort port = new CapturingPort();
        OperationLogAspect aspect = new OperationLogAspect(port);

        aspect.record(joinPoint(), opLog("LOGIN", "AUTH"));

        assertThat(port.entries).hasSize(1);
        String json = port.entries.get(0).toString();
        assertThat(json).doesNotContain("password");
        assertThat(json).doesNotContain("token");
        assertThat(json).doesNotContain("secret");
        // only safe fields present
        assertThat(json).contains("result=SUCCESS");
    }

    // FAIL-SAFE: persistence failure must not mask business success
    @Test
    void persistenceFailureDoesNotMaskBusinessOutcome() throws Throwable {
        RequestContext.set(RequestContext.Context.of("req-4", "corr-4", "9"));
        CapturingPort port = new CapturingPort();
        port.failure = new RuntimeException("db down");
        OperationLogAspect aspect = new OperationLogAspect(port);

        Object result = aspect.record(joinPoint(), opLog("SAVE_ORDER", "ORDER"));

        assertThat(result).isEqualTo("ok"); // business outcome intact
    }

    // FAIL-SAFE: persistence failure must not mask business failure either
    @Test
    void persistenceFailureDoesNotMaskBusinessFailure() throws Throwable {
        RequestContext.set(RequestContext.Context.of("req-5", "corr-5", "9"));
        CapturingPort port = new CapturingPort();
        port.failure = new RuntimeException("db down");
        OperationLogAspect aspect = new OperationLogAspect(port);

        assertThatThrownBy(() -> aspect.record(failingJoinPoint(), opLog("CANCEL_ORDER", "ORDER")))
                .isInstanceOf(IllegalStateException.class)
                .hasMessage("business boom");
    }

    // DESIGN DECISION: unauthenticated request (empty RequestContext) -> no log
    @Test
    void unauthenticatedRequestNotLogged() throws Throwable {
        CapturingPort port = new CapturingPort();
        OperationLogAspect aspect = new OperationLogAspect(port);

        Object result = aspect.record(joinPoint(), opLog("CREATE_ORDER", "ORDER"));

        assertThat(result).isEqualTo("ok");
        assertThat(port.entries).isEmpty();
    }

    // RequestContext cleanup after request (AuthInterceptor clears in afterCompletion)
    @Test
    void requestContextCleanup() {
        RequestContext.set(RequestContext.Context.of("req-6", "corr-6", "1"));
        assertThat(RequestContext.currentUserId()).isPresent();
        RequestContext.clear();
        assertThat(RequestContext.currentUserId()).isEmpty();
        assertThat(RequestContext.requestId()).isEmpty();
    }
}
