package ${package}.common.security;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Operation log annotation (generated by engineering-platform ${asset.version}).
 *
 * Marks a business operation to be recorded into sys_operation_log by
 * {@code OperationLogAspect}. Only annotation metadata (operation, resourceType)
 * plus method/path and RequestContext metadata are persisted — request bodies,
 * headers, and parameters are NEVER logged (sensitive-data safety gate).
 */
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
public @interface OperationLog {

    /** Business operation name, e.g. "CREATE_ORDER". */
    String operation();

    /** Resource type the operation acts on, e.g. "ORDER". */
    String resourceType();
}
