package ${package}.application.operationlog;

import ${package}.domain.entity.SysOperationLog;

import java.util.List;

/**
 * Operation log write/read contract (generated by engineering-platform ${asset.version}).
 *
 * Stable application-level contract. The implementation lives in the
 * infrastructure layer (MyBatis-Plus); application/business code depends only
 * on this interface — never on MyBatis persistence types.
 */
public interface OperationLogPort {

    /** Persist an operation log entry. */
    void save(SysOperationLog entry);

    /** Most recent entries, newest first (verification/testing support). */
    List<SysOperationLog> findLatest(int limit);
}
