package ${package}.api.operationlog;

import ${package}.application.operationlog.OperationLogQueryService;
import ${package}.common.core.ApiResponse;
import ${package}.common.core.PageQuery;
import ${package}.common.core.PageResult;
import ${package}.common.core.PlatformException;
import ${package}.common.core.RequestContext;
import ${package}.common.security.OperationLog;
import ${package}.common.security.RequirePermission;
import ${package}.common.security.SecurityErrorCodes;
import ${package}.domain.entity.SysOperationLog;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Operation log query API (generated by engineering-platform ${asset.version}).
 *
 * Read-only management surface: paged query with filters (user/operation/
 * resourceType/result/time range). No create/update/delete of logs.
 */
@RestController
@RequestMapping("/api/operation-logs")
public class OperationLogReferenceController {

    private final OperationLogQueryService operationLogQueryService;

    public OperationLogReferenceController(OperationLogQueryService operationLogQueryService) {
        this.operationLogQueryService = operationLogQueryService;
    }

    @GetMapping("/latest")
    @OperationLog(operation = "QUERY_OPERATION_LOGS", resourceType = "OPERATION_LOG")
    public ApiResponse<List<SysOperationLog>> latest() {
        // management-style endpoint: anonymous requests are denied (401)
        RequestContext.currentUserId()
                .orElseThrow(() -> new PlatformException(SecurityErrorCodes.UNAUTHENTICATED));
        return ApiResponse.ofSuccess(operationLogQueryService.latest(20));
    }

    @GetMapping
    @RequirePermission("system:operation-log:read")
    public ApiResponse<PageResult<SysOperationLog>> page(
            @RequestParam(defaultValue = "1") int page,
            @RequestParam(defaultValue = "20") int size,
            @RequestParam(required = false) String userId,
            @RequestParam(required = false) String operation,
            @RequestParam(required = false) String resourceType,
            @RequestParam(required = false) String result,
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
            LocalDateTime from,
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
            LocalDateTime to) {
        return ApiResponse.ofSuccess(operationLogQueryService.page(
                PageQuery.of(page, size), userId, operation, resourceType, result, from, to));
    }
}
