package ${package}.application.operationlog;

import ${package}.common.core.PageQuery;
import ${package}.common.core.PageResult;
import ${package}.domain.entity.SysOperationLog;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Operation log query application service (generated by engineering-platform ${asset.version}).
 *
 * Orchestration lives here, in the application layer. Persistence goes through
 * {@link OperationLogPort} — no MyBatis types appear in this class. Read-only:
 * no create/update/delete of logs from the management surface.
 */
public class OperationLogQueryService {

    private final OperationLogPort operationLogPort;

    public OperationLogQueryService(OperationLogPort operationLogPort) {
        this.operationLogPort = operationLogPort;
    }

    /** Most recent entries, newest first (verification/testing support). */
    public List<SysOperationLog> latest(int limit) {
        return operationLogPort.findLatest(limit);
    }

    /** Paged query with optional filters. */
    public PageResult<SysOperationLog> page(PageQuery query, String userId, String operation,
                                            String resourceType, String result,
                                            LocalDateTime from, LocalDateTime to) {
        return operationLogPort.page(query, userId, operation, resourceType, result, from, to);
    }
}
