package ${package}.application.operationlog;

import ${package}.common.core.PageQuery;
import ${package}.common.core.PageResult;
import ${package}.domain.entity.SysOperationLog;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Operation log write/read contract (generated by engineering-platform ${asset.version}).
 *
 * Stable application-level contract. The implementation lives in the
 * infrastructure layer (MyBatis-Plus); application/business code depends only
 * on this interface — never on MyBatis persistence types.
 */
public interface OperationLogPort {

    /** Persist an operation log entry. */
    void save(SysOperationLog entry);

    /** Most recent entries, newest first (verification/testing support). */
    List<SysOperationLog> findLatest(int limit);

    /** Paged query with optional filters (management read API). */
    PageResult<SysOperationLog> page(PageQuery query, String userId, String operation,
                                     String resourceType, String result,
                                     LocalDateTime from, LocalDateTime to);
}
