package ${package}.infrastructure.persistence;

import ${package}.application.operationlog.OperationLogPort;
import ${package}.infrastructure.persistence.mapper.SysOperationLogMapper;
import ${package}.infrastructure.security.OperationLogAspect;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Operation log bean wiring (generated by engineering-platform ${asset.version}).
 */
@Configuration
public class OperationLogBeansConfig {

    @Bean
    public OperationLogPort operationLogPort(SysOperationLogMapper operationLogMapper) {
        return new MybatisOperationLogRepository(operationLogMapper);
    }

    @Bean
    public OperationLogAspect operationLogAspect(OperationLogPort operationLogPort) {
        return new OperationLogAspect(operationLogPort);
    }
}
