<script setup lang="ts">
// App layout (generated by engineering-platform frontend-auth asset)
// Sidebar + Header + Main Content + Router View.
import { ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { useAuthStore } from '../stores/auth';
import { menuApi, type MenuNode } from '../api/menu';
import PermissionButton from '../permission/PermissionButton.vue';

const auth = useAuthStore();
const router = useRouter();
const collapsed = ref(false);
const menus = ref<MenuNode[]>([]);

function handleLogout(): void {
  auth.logout();
  router.push({ path: '/login' });
}

onMounted(async () => {
  try {
    menus.value = await menuApi.me();
  } catch {
    menus.value = [];
  }
});
</script>

<template>
  <el-container class="app-layout">
    <el-aside :width="collapsed ? '64px' : '220px'" class="app-sidebar">
      <div class="app-brand">{{ collapsed ? 'EP' : 'Engineering Platform' }}</div>
      <el-menu :collapse="collapsed" :default-active="$route.path" router class="app-menu">
        <template v-for="node in menus" :key="node.menu.code">
          <el-sub-menu v-if="node.menu.type === 'DIRECTORY'" :index="node.menu.code">
            <template #title>
              <span>{{ node.menu.name }}</span>
            </template>
            <el-menu-item v-for="child in node.children" :key="child.menu.code" :index="child.menu.path ?? child.menu.code">
              {{ child.menu.name }}
            </el-menu-item>
          </el-sub-menu>
          <el-menu-item v-else :index="node.menu.path ?? node.menu.code">
            {{ node.menu.name }}
          </el-menu-item>
        </template>
      </el-menu>
    </el-aside>
    <el-container>
      <el-header class="app-header">
        <div class="app-header-left">
          <el-button text @click="collapsed = !collapsed">
            {{ collapsed ? 'Expand' : 'Collapse' }}
          </el-button>
        </div>
        <div class="app-header-right">
          <span class="app-user">{{ auth.currentUser?.username }}</span>
          <PermissionButton permission="system:user:read" text @click="handleLogout">Logout</PermissionButton>
        </div>
      </el-header>
      <el-main class="app-main">
        <router-view />
      </el-main>
    </el-container>
  </el-container>
</template>

<style scoped>
.app-layout {
  height: 100vh;
}
.app-sidebar {
  border-right: 1px solid var(--el-border-color-light);
}
.app-brand {
  padding: 16px;
  font-weight: 600;
  white-space: nowrap;
  overflow: hidden;
}
.app-menu {
  border-right: none;
}
.app-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  border-bottom: 1px solid var(--el-border-color-light);
}
.app-header-right {
  display: flex;
  align-items: center;
  gap: 12px;
}
.app-main {
  padding: 24px;
  background: var(--ep-surface);
}
</style>
