// Feature page tests (generated by engineering-platform frontend-enterprise-management asset)
// Security boundary: frontend hides write buttons for read-only users; backend
// enforcement is verified by backend ManagementE2ETest (403 on direct API call).
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { mount, flushPromises } from '@vue/test-utils';
import { createPinia, setActivePinia } from 'pinia';
import { useAuthStore } from '../src/stores/auth';
import RoleManagementView from '../src/views/system/RoleManagementView.vue';
import DepartmentManagementView from '../src/views/system/DepartmentManagementView.vue';
import MenuManagementView from '../src/views/system/MenuManagementView.vue';
import DictionaryManagementView from '../src/views/system/DictionaryManagementView.vue';
import OperationLogView from '../src/views/system/OperationLogView.vue';
import { roleApi, permissionApi, departmentApi, menuApi, dictionaryApi, operationLogApi } from '../src/api/enterprise';
import { epStubs, platformStubs } from './stubs';

const stubs = { ...epStubs(), ...platformStubs() };

function seed(permissions: string[]): void {
  const pinia = createPinia();
  setActivePinia(pinia);
  const auth = useAuthStore(pinia);
  auth.$patch({ currentUser: { id: 1, username: 'u', departmentId: null, permissions } });
  localStorage.clear();
}

function mountWith(component: unknown): ReturnType<typeof mount> {
  return mount(component as never, { global: { stubs } });
}

describe('RoleManagementView', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  it('create role button visible with permission, hidden without', async () => {
    vi.spyOn(roleApi, 'page').mockResolvedValue({ items: [], total: 0, page: 1, size: 20 });
    vi.spyOn(permissionApi, 'list').mockResolvedValue([]);

    seed(['system:role:read', 'system:role:create']);
    const w1 = mountWith(RoleManagementView);
    await flushPromises();
    expect(w1.find('[data-testid="create-role"]').exists()).toBe(true);

    seed(['system:role:read']);
    const w2 = mountWith(RoleManagementView);
    await flushPromises();
    expect(w2.find('[data-testid="create-role"]').exists()).toBe(false);
  });
});

describe('DepartmentManagementView', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  it('create department button permission-gated', async () => {
    vi.spyOn(departmentApi, 'tree').mockResolvedValue([]);
    seed(['system:department:read']);
    const wrapper = mountWith(DepartmentManagementView);
    await flushPromises();
    expect(wrapper.find('[data-testid="create-department"]').exists()).toBe(false);
  });
});

describe('MenuManagementView', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  it('create menu button permission-gated', async () => {
    vi.spyOn(menuApi, 'tree').mockResolvedValue([]);
    vi.spyOn(permissionApi, 'list').mockResolvedValue([]);
    seed(['system:menu:read']);
    const wrapper = mountWith(MenuManagementView);
    await flushPromises();
    expect(wrapper.find('[data-testid="create-menu"]').exists()).toBe(false);
  });
});

describe('DictionaryManagementView', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  it('create type button permission-gated', async () => {
    vi.spyOn(dictionaryApi, 'types').mockResolvedValue([]);
    seed(['system:dictionary:read']);
    const wrapper = mountWith(DictionaryManagementView);
    await flushPromises();
    expect(wrapper.find('[data-testid="create-type"]').exists()).toBe(false);
  });
});

describe('OperationLogView', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  it('loads paged logs via platform API (read-only surface)', async () => {
    vi.spyOn(operationLogApi, 'page').mockResolvedValue({
      items: [
        {
          id: 1, userId: 1, operation: 'USER_CREATE', resourceType: 'USER', resourceId: '5',
          result: 'SUCCESS', requestId: 'req-1', correlationId: 'corr-1', method: 'POST',
          path: '/api/users', occurredAt: '2026-08-15T00:00:00',
        },
      ],
      total: 1, page: 1, size: 20,
    });
    seed(['system:operation-log:read']);
    const wrapper = mountWith(OperationLogView);
    await flushPromises();
    expect(operationLogApi.page).toHaveBeenCalled();
    expect(wrapper.find('[data-testid="oplog-filter-operation"]').exists()).toBe(true);
  });

  it('no write controls on operation log (read-only)', async () => {
    vi.spyOn(operationLogApi, 'page').mockResolvedValue({ items: [], total: 0, page: 1, size: 20 });
    seed(['system:operation-log:read']);
    const wrapper = mountWith(OperationLogView);
    await flushPromises();
    expect(wrapper.find('[data-testid="oplog-create"]').exists()).toBe(false);
    expect(wrapper.find('[data-testid="oplog-delete"]').exists()).toBe(false);
  });
});
