// Permission matrix + feature page tests (generated by engineering-platform frontend-enterprise-management asset)
import { describe, it, expect } from 'vitest';
import { groupPermissions, domainOf, resourceOf, actionOf, actionLabel } from '../src/utils/permissionMatrix';
import type { Permission } from '../src/types/enterprise';

const perms: Permission[] = [
  { id: 1, code: 'system:user:read', name: 'Read users', createdAt: '', updatedAt: '' },
  { id: 2, code: 'system:user:create', name: 'Create users', createdAt: '', updatedAt: '' },
  { id: 3, code: 'system:user:disable', name: 'Disable users', createdAt: '', updatedAt: '' },
  { id: 4, code: 'system:role:read', name: 'Read roles', createdAt: '', updatedAt: '' },
  { id: 5, code: 'product:item:read', name: 'Read products', createdAt: '', updatedAt: '' },
  { id: 6, code: 'product:item:update', name: 'Update products', createdAt: '', updatedAt: '' },
];

describe('permission matrix grouping', () => {
  it('parses domain/resource/action', () => {
    expect(domainOf('system:user:read')).toBe('system');
    expect(resourceOf('system:user:read')).toBe('user');
    expect(actionOf('system:user:assign-role')).toBe('assign-role');
  });

  it('groups by domain -> resource -> action', () => {
    const groups = groupPermissions(perms);
    expect(groups.length).toBe(2);
    expect(groups[0].domain).toBe('product');
    expect(groups[1].domain).toBe('system');

    const user = groups[1].resources.find((r) => r.resource === 'user')!;
    expect(user.actions.map((a) => a.action)).toEqual(['create', 'disable', 'read']);
  });

  it('maps action codes to readable labels', () => {
    expect(actionLabel('read')).toBe('Read');
    expect(actionLabel('assign-role')).toBe('Assign role');
    expect(actionLabel('unknown-x')).toBe('unknown-x');
  });
});
