// Auth store tests (generated by engineering-platform frontend-auth asset)
import { describe, it, expect, beforeEach, vi } from 'vitest';
import { createPinia, setActivePinia } from 'pinia';
import { useAuthStore } from '../src/stores/auth';
import { authApi } from '../src/api/auth';

vi.mock('../src/api/auth', () => ({
  authApi: {
    login: vi.fn(),
    me: vi.fn(),
  },
}));

describe('auth store', () => {
  beforeEach(() => {
    setActivePinia(createPinia());
    localStorage.clear();
    vi.clearAllMocks();
  });

  it('login stores token and loads current user', async () => {
    (authApi.login as ReturnType<typeof vi.fn>).mockResolvedValue({
      token: 'tok-123',
      userId: 1,
      username: 'admin',
      expiresAtEpochSeconds: 9999999999,
    });
    (authApi.me as ReturnType<typeof vi.fn>).mockResolvedValue({
      id: 1,
      username: 'admin',
      departmentId: 1,
      permissions: ['system:user:read', 'product:item:read'],
    });

    const auth = useAuthStore();
    await auth.login('admin', 'admin123');

    expect(auth.authenticated).toBe(true);
    expect(auth.token).toBe('tok-123');
    expect(localStorage.getItem('ep.token')).toBe('tok-123');
    expect(auth.currentUser?.username).toBe('admin');
    expect(auth.permissions).toContain('product:item:read');
  });

  it('login failure leaves unauthenticated state', async () => {
    (authApi.login as ReturnType<typeof vi.fn>).mockRejectedValue(new Error('bad credentials'));

    const auth = useAuthStore();
    await expect(auth.login('admin', 'wrong')).rejects.toThrow('bad credentials');
    expect(auth.authenticated).toBe(false);
    expect(localStorage.getItem('ep.token')).toBeNull();
  });

  it('logout clears token and user', async () => {
    localStorage.setItem('ep.token', 'tok');
    localStorage.setItem('ep.currentUser', JSON.stringify({ id: 1, username: 'a', departmentId: null, permissions: [] }));
    const auth = useAuthStore();
    auth.logout();
    expect(auth.authenticated).toBe(false);
    expect(auth.currentUser).toBeNull();
    expect(localStorage.getItem('ep.token')).toBeNull();
  });
});
