import { describe, it, expect } from 'vitest';
import { mount } from '@vue/test-utils';
import App from '../src/App.vue';

// V0.5 frontend shell smoke test (generated by engineering-platform frontend-shell asset)
// Proves Vue + TypeScript + Vite + Vitest chain actually mounts/renders.
describe('app shell', () => {
  it('mounts and renders the shell marker', () => {
    const wrapper = mount(App);
    expect(wrapper.find('[data-testid="app-shell"]').exists()).toBe(true);
    expect(wrapper.text()).toContain('Engineering Platform');
  });
});
