# TEST profile (generated by engineering-platform ${asset.version})
# H2 in-memory + schema/seed init for generated-project security E2E.
# Production profile is NOT affected: no known credentials are shipped.

spring:
  datasource:
    url: jdbc:h2:mem:rbacdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:db/migration/V002__rbac.sql
      data-locations: classpath:db/seed/seed-test-data.sql

auth:
  token:
    secret: test-only-secret-key-0123456789abcdef
    expiration-seconds: 3600
