package ${package};

import ${package}.api.auth.LoginRequest;
import ${package}.api.auth.LoginResponse;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.ActiveProfiles;

import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Real HTTP security E2E (generated by engineering-platform ${asset.version}).
 * Boots the real application (random port) and performs real HTTP calls:
 * login, token, authentication, RBAC enforcement, failure paths A-H.
 *
 * Test-only credentials (see application-test.yml / seed-test-data.sql):
 *   admin/admin123 (role admin  -> system:user:read)
 *   viewer/admin123 (role viewer -> no permissions)
 *   disabled/admin123 (disabled user)
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
class AuthRbacE2ETest {

    @LocalServerPort
    private int port;

    @Autowired
    private TestRestTemplate rest;

    private String url(String path) {
        return "http://localhost:" + port + path;
    }

    private ResponseEntity<Map> login(String username, String password) {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        HttpEntity<LoginRequest> body = new HttpEntity<>(new LoginRequest(username, password), headers);
        return rest.postForEntity(url("/api/auth/login"), body, Map.class);
    }

    private HttpHeaders bearer(String token) {
        HttpHeaders headers = new HttpHeaders();
        headers.setBearerAuth(token);
        return headers;
    }

    // A. no token -> protected API -> 401 unauthenticated
    @Test
    void unauthenticatedRequestIsRejected() {
        ResponseEntity<Map> response = rest.exchange(
                url("/api/users/me"), HttpMethod.GET, HttpEntity.EMPTY, Map.class);
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.UNAUTHORIZED);
    }

    // B. wrong password -> login rejected
    @Test
    void wrongPasswordIsRejected() {
        ResponseEntity<Map> response = login("admin", "wrong-password");
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.UNAUTHORIZED);
        Map err = (Map) response.getBody().get("error");
        assertThat(String.valueOf(err.get("code"))).contains("INVALID_CREDENTIALS");
    }

    // C. disabled user -> login rejected
    @Test
    void disabledUserCannotLogin() {
        ResponseEntity<Map> response = login("disabled", "admin123");
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN);
        Map err = (Map) response.getBody().get("error");
        assertThat(String.valueOf(err.get("code"))).contains("USER_DISABLED");
    }

    // D. valid user -> login success -> token returned
    @Test
    void validLoginReturnsToken() {
        ResponseEntity<Map> response = login("admin", "admin123");
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody().get("data")).isNotNull();
        Map data = (Map) response.getBody().get("data");
        assertThat(String.valueOf(data.get("token"))).isNotBlank();
        assertThat(String.valueOf(data.get("username"))).isEqualTo("admin");
    }

    // E. valid token + required permission -> protected API success
    @Test
    void validTokenWithPermissionSucceeds() {
        ResponseEntity<Map> loginResponse = login("admin", "admin123");
        String token = (String) ((Map) loginResponse.getBody().get("data")).get("token");

        ResponseEntity<Map> me = rest.exchange(
                url("/api/users/me"), HttpMethod.GET, new HttpEntity<>(bearer(token)), Map.class);
        assertThat(me.getStatusCode()).isEqualTo(HttpStatus.OK);

        ResponseEntity<Map> users = rest.exchange(
                url("/api/users"), HttpMethod.GET, new HttpEntity<>(bearer(token)), Map.class);
        assertThat(users.getStatusCode()).isEqualTo(HttpStatus.OK);
    }

    // F. valid token but missing permission -> 403
    @Test
    void validTokenWithoutPermissionDenied() {
        ResponseEntity<Map> loginResponse = login("viewer", "admin123");
        String token = (String) ((Map) loginResponse.getBody().get("data")).get("token");

        ResponseEntity<Map> users = rest.exchange(
                url("/api/users"), HttpMethod.GET, new HttpEntity<>(bearer(token)), Map.class);
        assertThat(users.getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN);
        Map err = (Map) users.getBody().get("error");
        assertThat(String.valueOf(err.get("code"))).contains("PERMISSION_DENIED");
    }

    // G. expired token -> rejected
    @Test
    void expiredTokenIsRejected() {
        ResponseEntity<Map> loginResponse = login("admin", "admin123");
        String token = (String) ((Map) loginResponse.getBody().get("data")).get("token");
        // tamper the token: flip the last hex char to corrupt signature
        String tampered = token.substring(0, token.length() - 1)
                + (token.endsWith("0") ? "1" : "0");

        ResponseEntity<Map> response = rest.exchange(
                url("/api/users/me"), HttpMethod.GET, new HttpEntity<>(bearer(tampered)), Map.class);
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.UNAUTHORIZED);
    }

    // H. RequestContext currentUser correct + cleared after request
    @Test
    void requestContextIsSetAndCleared() {
        ResponseEntity<Map> loginResponse = login("admin", "admin123");
        String token = (String) ((Map) loginResponse.getBody().get("data")).get("token");

        ResponseEntity<Map> me = rest.exchange(
                url("/api/users/me"), HttpMethod.GET, new HttpEntity<>(bearer(token)), Map.class);
        assertThat(me.getStatusCode()).isEqualTo(HttpStatus.OK);
        Map data = (Map) me.getBody().get("data");
        assertThat(String.valueOf(data.get("username"))).isEqualTo("admin");

        // after the request, no thread-local leak: next unauthenticated call still 401
        ResponseEntity<Map> anonymous = rest.exchange(
                url("/api/users/me"), HttpMethod.GET, HttpEntity.EMPTY, Map.class);
        assertThat(anonymous.getStatusCode()).isEqualTo(HttpStatus.UNAUTHORIZED);
    }
}
