package ${package}.api.user;

import java.util.List;

/**
 * Current user response (generated by engineering-platform ${asset.version}).
 * Exposes only safe profile fields + granted permission codes for the frontend
 * UX (menu/button visibility). Authorization always stays backend-side.
 */
public record CurrentUserResponse(
        Long id,
        String username,
        Long departmentId,
        List<String> permissions) {

    public static CurrentUserResponse of(Long id, String username, Long departmentId,
                                         java.util.Set<String> permissions) {
        return new CurrentUserResponse(id, username, departmentId,
                permissions.stream().sorted().toList());
    }
}
