package ${package};

import ${package}.api.auth.LoginRequest;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.ActiveProfiles;

import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Enterprise Management API E2E (generated by engineering-platform ${asset.version}).
 *
 * Real HTTP coverage for V05-WORK-003 management surface:
 *   User (create/assign dept+roles/enable/disable/duplicate/invalid/limited denied)
 *   Role (create/dataScope/assign permissions/duplicate)
 *   Department (create child/self-parent denied/disable)
 *   Menu (create with valid permission/invalid permission rejected)
 *   Dictionary (create type/item/duplicate/disable)
 *   Operation Log (query after writes)
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
class ManagementE2ETest {

    @LocalServerPort
    private int port;

    @Autowired
    private TestRestTemplate rest;

    private String url(String path) {
        return "http://localhost:" + port + path;
    }

    private ResponseEntity<Map> login(String username, String password) {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        HttpEntity<LoginRequest> body = new HttpEntity<>(new LoginRequest(username, password), headers);
        return rest.postForEntity(url("/api/auth/login"), body, Map.class);
    }

    private String token(String username, String password) {
        ResponseEntity<Map> response = login(username, password);
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        Map data = (Map) response.getBody().get("data");
        return (String) data.get("token");
    }

    private HttpEntity<String> json(String token, String body) {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        headers.setBearerAuth(token);
        return new HttpEntity<>(body, headers);
    }

    private ResponseEntity<Map> get(String token, String path) {
        HttpHeaders headers = new HttpHeaders();
        headers.setBearerAuth(token);
        return rest.exchange(url(path), HttpMethod.GET, new HttpEntity<>(headers), Map.class);
    }

    private ResponseEntity<Map> post(String token, String path, String body) {
        return rest.exchange(url(path), HttpMethod.POST, json(token, body), Map.class);
    }

    private ResponseEntity<Map> put(String token, String path, String body) {
        return rest.exchange(url(path), HttpMethod.PUT, json(token, body), Map.class);
    }

    private String adminToken() {
        return token("admin", "admin123");
    }

    // ---- User management -------------------------------------------------

    @Test
    void userCrudLifecycle() {
        String t = adminToken();
        // create user with department + role
        ResponseEntity<Map> created = post(t, "/api/users",
                "{\"username\":\"mgmt-user-1\",\"initialPassword\":\"Init123!\",\"departmentId\":1,\"roleIds\":[2]}");
        assertThat(created.getStatusCode()).isEqualTo(HttpStatus.OK);
        Map data = (Map) created.getBody().get("data");
        assertThat(data.get("initialPassword")).isEqualTo("Init123!");
        Map user = (Map) data.get("user");
        Object id = user.get("id");
        assertThat(user.get("username")).isEqualTo("mgmt-user-1");
        assertThat(String.valueOf(user.get("departmentId"))).isEqualTo("1");

        // new user can login
        assertThat(login("mgmt-user-1", "Init123!").getStatusCode()).isEqualTo(HttpStatus.OK);

        // duplicate username rejected
        ResponseEntity<Map> dup = post(t, "/api/users",
                "{\"username\":\"mgmt-user-1\",\"initialPassword\":\"X\"}");
        assertThat(dup.getStatusCode()).isEqualTo(HttpStatus.BAD_REQUEST);
        assertThat(((Map) dup.getBody().get("error")).get("code")).isEqualTo("USERNAME_DUPLICATE");

        // invalid department rejected
        ResponseEntity<Map> badDept = post(t, "/api/users",
                "{\"username\":\"mgmt-user-2\",\"departmentId\":999}");
        assertThat(badDept.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
        assertThat(((Map) badDept.getBody().get("error")).get("code")).isEqualTo("DEPARTMENT_NOT_FOUND");

        // transaction boundary: invalid role reference rolls back the whole create
        // (no partial user row survives the failed unit of work)
        ResponseEntity<Map> badRole = post(t, "/api/users",
                "{\"username\":\"mgmt-rollback-probe\",\"roleIds\":[999999]}");
        assertThat(badRole.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
        assertThat(((Map) badRole.getBody().get("error")).get("code")).isEqualTo("ROLE_NOT_FOUND");
        ResponseEntity<Map> probeList = get(t, "/api/users?page=1&size=20&username=mgmt-rollback-probe");
        Map probeData = (Map) probeList.getBody().get("data");
        assertThat(((Number) probeData.get("total")).longValue()).isEqualTo(0);
        assertThat(((java.util.List<?>) probeData.get("items"))).isEmpty();

        // disable -> login rejected
        post(t, "/api/users/" + id + "/disable", "{}");
        assertThat(login("mgmt-user-1", "Init123!").getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN);
        // re-enable -> login ok
        post(t, "/api/users/" + id + "/enable", "{}");
        assertThat(login("mgmt-user-1", "Init123!").getStatusCode()).isEqualTo(HttpStatus.OK);
    }

    @Test
    void userListFilteredAndPaged() {
        String t = adminToken();
        ResponseEntity<Map> list = get(t, "/api/users?page=1&size=10&enabled=true");
        assertThat(list.getStatusCode()).isEqualTo(HttpStatus.OK);
        Map data = (Map) list.getBody().get("data");
        assertThat(((Number) data.get("total")).longValue()).isGreaterThanOrEqualTo(7);
        assertThat(((List<?>) data.get("items"))).isNotEmpty();
    }

    @Test
    void limitedUserCannotManage() {
        // sales-user has product read only, no system:user:create
        String t = token("sales-user", "admin123");
        ResponseEntity<Map> denied = post(t, "/api/users",
                "{\"username\":\"nope\",\"initialPassword\":\"X\"}");
        assertThat(denied.getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN);
    }

    // ---- Role management -------------------------------------------------

    @Test
    void roleLifecycle() {
        String t = adminToken();
        ResponseEntity<Map> created = post(t, "/api/roles",
                "{\"code\":\"mgmt-role\",\"name\":\"Mgmt Role\",\"dataScope\":\"SELF\",\"permissionIds\":[2]}");
        assertThat(created.getStatusCode()).isEqualTo(HttpStatus.OK);
        Map data = (Map) created.getBody().get("data");
        Object id = data.get("id");
        assertThat(data.get("code")).isEqualTo("mgmt-role");
        assertThat(data.get("dataScope")).isEqualTo("SELF");
        assertThat(((List<?>) data.get("permissionIds")).stream().map(String::valueOf))
                .contains("2");

        // duplicate code rejected
        ResponseEntity<Map> dup = post(t, "/api/roles",
                "{\"code\":\"mgmt-role\",\"name\":\"Dup\"}");
        assertThat(dup.getStatusCode()).isEqualTo(HttpStatus.BAD_REQUEST);
        assertThat(((Map) dup.getBody().get("error")).get("code")).isEqualTo("ROLE_CODE_DUPLICATE");

        // assign permissions
        ResponseEntity<Map> assign = post(t, "/api/roles/" + id + "/permissions", "[1,2]");
        assertThat(assign.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(((List<?>) ((Map) assign.getBody().get("data")).get("permissionIds"))
                .stream().map(String::valueOf))
                .containsExactlyInAnyOrder("1", "2");

        // disable role
        post(t, "/api/roles/" + id + "/disable", "{}");
        ResponseEntity<Map> detail = get(t, "/api/roles/" + id);
        assertThat(((Map) detail.getBody().get("data")).get("enabled")).isEqualTo(false);
    }

    // ---- Department management ---------------------------------------------

    @Test
    void departmentCrudAndSafety() {
        String t = adminToken();
        ResponseEntity<Map> created = post(t, "/api/departments",
                "{\"code\":\"MGMT_DEPT\",\"name\":\"Mgmt Dept\",\"parentId\":1,\"sort\":9}");
        assertThat(created.getStatusCode()).isEqualTo(HttpStatus.OK);
        Map data = (Map) created.getBody().get("data");
        Object id = data.get("id");

        // tree reflects it
        ResponseEntity<Map> tree = get(t, "/api/departments/tree");
        assertThat(tree.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(String.valueOf(tree.getBody().get("data"))).contains("MGMT_DEPT");

        // self-parent denied
        ResponseEntity<Map> selfParent = put(t, "/api/departments/" + id,
                "{\"name\":\"X\",\"parentId\":" + id + "}");
        assertThat(selfParent.getStatusCode()).isEqualTo(HttpStatus.BAD_REQUEST);
        assertThat(((Map) selfParent.getBody().get("error")).get("code")).isEqualTo("DEPARTMENT_SELF_PARENT");

        // disable
        ResponseEntity<Map> disabled = post(t, "/api/departments/" + id + "/disable", "{}");
        assertThat(disabled.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(((Map) disabled.getBody().get("data")).get("enabled")).isEqualTo(false);
    }

    // ---- Menu management ----------------------------------------------------

    @Test
    void menuCrudAndPermissionValidation() {
        String t = adminToken();
        ResponseEntity<Map> created = post(t, "/api/menus",
                "{\"parentId\":4,\"code\":\"mgmt-menu\",\"name\":\"Mgmt Menu\",\"type\":\"MENU\",\"path\":\"/mgmt\",\"permissionCode\":\"product:item:read\",\"sort\":9}");
        assertThat(created.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(((Map) created.getBody().get("data")).get("code")).isEqualTo("mgmt-menu");

        // invalid permission rejected
        ResponseEntity<Map> badPerm = post(t, "/api/menus",
                "{\"parentId\":4,\"code\":\"mgmt-menu-2\",\"name\":\"Bad\",\"type\":\"MENU\",\"permissionCode\":\"no:such:perm\"}");
        assertThat(badPerm.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
        assertThat(((Map) badPerm.getBody().get("error")).get("code")).isEqualTo("MENU_PERMISSION_NOT_FOUND");
    }

    // ---- Dictionary management ---------------------------------------------

    @Test
    void dictionaryCrud() {
        String t = adminToken();
        ResponseEntity<Map> type = post(t, "/api/dictionaries/types",
                "{\"code\":\"mgmt_status\",\"name\":\"Mgmt Status\"}");
        assertThat(type.getStatusCode()).isEqualTo(HttpStatus.OK);
        Object typeId = ((Map) type.getBody().get("data")).get("id");

        // duplicate type code rejected
        ResponseEntity<Map> dupType = post(t, "/api/dictionaries/types",
                "{\"code\":\"mgmt_status\",\"name\":\"Dup\"}");
        assertThat(dupType.getStatusCode()).isEqualTo(HttpStatus.BAD_REQUEST);
        assertThat(((Map) dupType.getBody().get("error")).get("code")).isEqualTo("DICTIONARY_TYPE_CODE_DUPLICATE");

        // create item
        ResponseEntity<Map> item = post(t, "/api/dictionaries/types/" + typeId + "/items",
                "{\"value\":\"ACTIVE\",\"label\":\"Active\",\"sort\":1}");
        assertThat(item.getStatusCode()).isEqualTo(HttpStatus.OK);

        // duplicate item value rejected
        ResponseEntity<Map> dupItem = post(t, "/api/dictionaries/types/" + typeId + "/items",
                "{\"value\":\"ACTIVE\",\"label\":\"Dup\"}");
        assertThat(dupItem.getStatusCode()).isEqualTo(HttpStatus.BAD_REQUEST);
        assertThat(((Map) dupItem.getBody().get("error")).get("code")).isEqualTo("DICTIONARY_ITEM_DUPLICATE");

        // disable item
        Object itemId = ((Map) item.getBody().get("data")).get("id");
        ResponseEntity<Map> disabledItem = post(t, "/api/dictionaries/items/" + itemId + "/disable", "{}");
        assertThat(disabledItem.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(((Map) disabledItem.getBody().get("data")).get("enabled")).isEqualTo(false);

        // existing product_status unaffected (stable codes)
        ResponseEntity<Map> productStatus = get(t, "/api/dictionaries/product_status/items");
        assertThat(productStatus.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(((List<?>) productStatus.getBody().get("data"))).hasSize(2);
    }

    // ---- Operation log query -------------------------------------------------

    @Test
    void operationLogQueryAfterWrites() {
        String t = adminToken();
        // trigger writes
        post(t, "/api/dictionaries/types", "{\"code\":\"log_type\",\"name\":\"Log Type\"}");
        post(t, "/api/roles", "{\"code\":\"log-role\",\"name\":\"Log Role\",\"dataScope\":\"SELF\"}");

        ResponseEntity<Map> logs = get(t, "/api/operation-logs?page=1&size=20&result=SUCCESS");
        assertThat(logs.getStatusCode()).isEqualTo(HttpStatus.OK);
        Map data = (Map) logs.getBody().get("data");
        assertThat(((Number) data.get("total")).longValue()).isGreaterThanOrEqualTo(2);
        List<Map> items = (List<Map>) data.get("items");
        assertThat(items).extracting(m -> m.get("operation"))
                .contains("DICTIONARY_TYPE_CREATE", "ROLE_CREATE");
        // no sensitive fields persisted
        for (Map item : items) {
            assertThat(String.valueOf(item)).doesNotContain("password");
            assertThat(String.valueOf(item)).doesNotContain("Bearer");
        }
        // filter by operation
        ResponseEntity<Map> filtered = get(t, "/api/operation-logs?operation=ROLE_CREATE");
        assertThat(((Number) ((Map) filtered.getBody().get("data")).get("total")).longValue())
                .isGreaterThanOrEqualTo(1);
    }

    // ---- anonymous / permission denied ---------------------------------------

    @Test
    void anonymousDeniedOnManagement() {
        ResponseEntity<Map> response = rest.exchange(url("/api/users"),
                HttpMethod.GET, HttpEntity.EMPTY, Map.class);
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.UNAUTHORIZED);
    }
}
