package ${package}.infrastructure.persistence;

import ${package}.application.rbac.UserManagementPort;
import ${package}.common.core.PageQuery;
import ${package}.common.core.PageResult;
import ${package}.domain.entity.SysRole;
import ${package}.domain.entity.SysUser;
import ${package}.domain.entity.SysUserRole;
import ${package}.infrastructure.persistence.mapper.SysRoleMapper;
import ${package}.infrastructure.persistence.mapper.SysUserMapper;
import ${package}.infrastructure.persistence.mapper.SysUserRoleMapper;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * MyBatis-Plus implementation of {@link UserManagementPort} (generated by engineering-platform ${asset.version}).
 *
 * All MyBatis-Plus technical types (QueryWrapper / BaseMapper) stay confined
 * here, in the infrastructure layer. Application/business code depends only
 * on the port contract — never on MyBatis types.
 */
public class MybatisUserManagementRepository implements UserManagementPort {

    private final SysUserMapper userMapper;
    private final SysUserRoleMapper userRoleMapper;
    private final SysRoleMapper roleMapper;

    public MybatisUserManagementRepository(SysUserMapper userMapper, SysUserRoleMapper userRoleMapper,
                                           SysRoleMapper roleMapper) {
        this.userMapper = userMapper;
        this.userRoleMapper = userRoleMapper;
        this.roleMapper = roleMapper;
    }

    @Override
    public PageResult<SysUser> page(PageQuery query, String usernameKeyword, Boolean enabled,
                                    Long departmentId) {
        QueryWrapper<SysUser> countWrapper = new QueryWrapper<>();
        applyFilters(countWrapper, usernameKeyword, enabled, departmentId);
        long total = userMapper.selectCount(countWrapper);
        QueryWrapper<SysUser> wrapper = new QueryWrapper<>();
        applyFilters(wrapper, usernameKeyword, enabled, departmentId);
        wrapper.orderByAsc("id");
        wrapper.last("LIMIT " + query.size() + " OFFSET " + query.offset());
        List<SysUser> items = userMapper.selectList(wrapper);
        return PageResult.of(items, total, query.page(), query.size());
    }

    private void applyFilters(QueryWrapper<SysUser> wrapper, String usernameKeyword, Boolean enabled,
                              Long departmentId) {
        if (usernameKeyword != null && !usernameKeyword.isBlank()) {
            wrapper.like("username", usernameKeyword);
        }
        if (enabled != null) {
            wrapper.eq("enabled", enabled ? 1 : 0);
        }
        if (departmentId != null) {
            wrapper.eq("department_id", departmentId);
        }
    }

    @Override
    public Optional<SysUser> findById(Long userId) {
        return Optional.ofNullable(userMapper.selectById(userId));
    }

    @Override
    public Optional<SysUser> findByUsername(String username) {
        return Optional.ofNullable(userMapper.selectOne(
                new QueryWrapper<SysUser>().eq("username", username).last("LIMIT 1")));
    }

    @Override
    public boolean usernameExists(String username, Long excludeUserId) {
        QueryWrapper<SysUser> wrapper = new QueryWrapper<SysUser>().eq("username", username);
        if (excludeUserId != null) {
            wrapper.ne("id", excludeUserId);
        }
        return userMapper.selectCount(wrapper) > 0;
    }

    @Override
    public void insert(SysUser user) {
        userMapper.insert(user);
    }

    @Override
    public void update(SysUser user) {
        userMapper.updateById(user);
    }

    @Override
    public List<Long> roleIdsOf(Long userId) {
        return userRoleMapper.selectList(new QueryWrapper<SysUserRole>().eq("user_id", userId))
                .stream().map(SysUserRole::getRoleId).toList();
    }

    @Override
    public void replaceUserRoles(Long userId, List<Long> roleIds) {
        userRoleMapper.delete(new QueryWrapper<SysUserRole>().eq("user_id", userId));
        if (roleIds == null) {
            return;
        }
        for (Long roleId : roleIds.stream().distinct().toList()) {
            SysUserRole ur = new SysUserRole();
            ur.setUserId(userId);
            ur.setRoleId(roleId);
            ur.setCreatedAt(LocalDateTime.now());
            userRoleMapper.insert(ur);
        }
    }

    @Override
    public Optional<SysRole> findRoleById(Long roleId) {
        return Optional.ofNullable(roleMapper.selectById(roleId));
    }
}
