package ${package}.infrastructure.persistence;

import ${package}.application.rbac.PermissionManagementPort;
import ${package}.domain.entity.SysPermission;
import ${package}.infrastructure.persistence.mapper.SysPermissionMapper;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;

import java.util.List;
import java.util.Optional;

/**
 * MyBatis-Plus implementation of {@link PermissionManagementPort} (generated by engineering-platform ${asset.version}).
 *
 * READ-ONLY registry-style governance. All MyBatis technical types stay
 * confined here, in the infrastructure layer.
 */
public class MybatisPermissionManagementRepository implements PermissionManagementPort {

    private final SysPermissionMapper permissionMapper;

    public MybatisPermissionManagementRepository(SysPermissionMapper permissionMapper) {
        this.permissionMapper = permissionMapper;
    }

    @Override
    public List<SysPermission> list(String code) {
        QueryWrapper<SysPermission> wrapper = new QueryWrapper<>();
        if (code != null && !code.isBlank()) {
            wrapper.like("code", code);
        }
        wrapper.orderByAsc("code");
        return permissionMapper.selectList(wrapper);
    }

    @Override
    public Optional<SysPermission> findById(Long permissionId) {
        return Optional.ofNullable(permissionMapper.selectById(permissionId));
    }
}
