package ${package}.infrastructure.persistence;

import ${package}.application.rbac.UserQueryPort;
import ${package}.domain.entity.SysUser;
import ${package}.domain.entity.SysRole;
import ${package}.domain.entity.SysPermission;
import ${package}.domain.entity.SysUserRole;
import ${package}.domain.entity.SysRolePermission;
import ${package}.infrastructure.persistence.mapper.SysUserMapper;
import ${package}.infrastructure.persistence.mapper.SysRoleMapper;
import ${package}.infrastructure.persistence.mapper.SysPermissionMapper;
import ${package}.infrastructure.persistence.mapper.SysUserRoleMapper;
import ${package}.infrastructure.persistence.mapper.SysRolePermissionMapper;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;

import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * MyBatis-Plus implementation of {@link UserQueryPort} (generated by engineering-platform ${asset.version}).
 *
 * All MyBatis-Plus technical types (QueryWrapper / BaseMapper) stay confined here,
 * in the infrastructure layer. Application/business code depends only on
 * {@link UserQueryPort} — never on MyBatis types.
 */
public class MybatisUserQueryRepository implements UserQueryPort {

    private final SysUserMapper userMapper;
    private final SysRoleMapper roleMapper;
    private final SysPermissionMapper permissionMapper;
    private final SysUserRoleMapper userRoleMapper;
    private final SysRolePermissionMapper rolePermissionMapper;

    public MybatisUserQueryRepository(SysUserMapper userMapper, SysRoleMapper roleMapper,
                                      SysPermissionMapper permissionMapper, SysUserRoleMapper userRoleMapper,
                                      SysRolePermissionMapper rolePermissionMapper) {
        this.userMapper = userMapper;
        this.roleMapper = roleMapper;
        this.permissionMapper = permissionMapper;
        this.userRoleMapper = userRoleMapper;
        this.rolePermissionMapper = rolePermissionMapper;
    }

    @Override
    public Optional<SysUser> findByUsername(String username) {
        return Optional.ofNullable(userMapper.selectOne(
                new QueryWrapper<SysUser>().eq("username", username).last("LIMIT 1")));
    }

    @Override
    public Optional<SysUser> findById(Long userId) {
        return Optional.ofNullable(userMapper.selectById(userId));
    }

    @Override
    public List<SysUser> findAll() {
        return userMapper.selectList(null);
    }

    @Override
    public Set<String> permissionCodesOf(Long userId) {
        List<SysUserRole> userRoles = userRoleMapper.selectList(
                new QueryWrapper<SysUserRole>().eq("user_id", userId));
        if (userRoles.isEmpty()) {
            return Set.of();
        }
        Set<Long> roleIds = userRoles.stream().map(SysUserRole::getRoleId).collect(Collectors.toSet());
        List<SysRole> roles = roleMapper.selectBatchIds(roleIds);
        Set<Long> enabledRoleIds = roles.stream()
                .filter(r -> r.getEnabled() != null && r.getEnabled())
                .map(SysRole::getId)
                .collect(Collectors.toSet());
        if (enabledRoleIds.isEmpty()) {
            return Set.of();
        }
        List<SysRolePermission> rolePerms = rolePermissionMapper.selectList(
                new QueryWrapper<SysRolePermission>().in("role_id", enabledRoleIds));
        if (rolePerms.isEmpty()) {
            return Set.of();
        }
        Set<Long> permissionIds = rolePerms.stream()
                .map(SysRolePermission::getPermissionId).collect(Collectors.toSet());
        List<SysPermission> permissions = permissionMapper.selectBatchIds(permissionIds);
        return permissions.stream().map(SysPermission::getCode).collect(Collectors.toSet());
    }
}
