package ${package}.api.permission;

import ${package}.common.core.ApiResponse;
import ${package}.common.security.RequirePermission;
import ${package}.domain.entity.SysPermission;
import ${package}.application.rbac.PermissionManagementService;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * Permission governance API (generated by engineering-platform ${asset.version}).
 *
 * READ-ONLY registry-style management: permission codes come from system/asset
 * declarations, not from UI creation. No create/delete endpoints (no permissions
 * without real enforcement exist).
 */
@RestController
@RequestMapping("/api/permissions")
public class PermissionController {

    private final PermissionManagementService permissionService;

    public PermissionController(PermissionManagementService permissionService) {
        this.permissionService = permissionService;
    }

    @GetMapping
    @RequirePermission("system:permission:read")
    public ApiResponse<List<SysPermission>> list(@RequestParam(required = false) String code) {
        return ApiResponse.ofSuccess(permissionService.list(code));
    }

    @GetMapping("/{id}")
    @RequirePermission("system:permission:read")
    public ApiResponse<SysPermission> detail(@PathVariable Long id) {
        return ApiResponse.ofSuccess(permissionService.detail(id));
    }
}
