package ${package}.application.rbac;

import ${package}.common.core.ErrorCode;
import ${package}.common.core.PlatformException;
import ${package}.domain.entity.SysPermission;

import java.util.List;
import java.util.Optional;

/**
 * Permission governance application service (generated by engineering-platform ${asset.version}).
 *
 * READ-ONLY registry-style: permission codes come from system/asset declarations,
 * not from UI creation. Persistence goes through {@link PermissionManagementPort} —
 * no MyBatis types appear in this class.
 */
public class PermissionManagementService {

    private final PermissionManagementPort managementPort;

    public PermissionManagementService(PermissionManagementPort managementPort) {
        this.managementPort = managementPort;
    }

    public List<SysPermission> list(String code) {
        return managementPort.list(code);
    }

    public SysPermission detail(Long id) {
        Optional<SysPermission> permission = managementPort.findById(id);
        if (permission.isEmpty()) {
            throw new PlatformException(ErrorCode.of("PERMISSION_NOT_FOUND",
                    "permission not found: " + id));
        }
        return permission.get();
    }
}
