package ${package}.infrastructure.security;

import ${package}.common.core.PlatformException;
import ${package}.common.core.RequestContext;
import ${package}.common.security.RequirePermission;
import ${package}.common.security.SecurityErrorCodes;
import ${package}.application.rbac.UserQueryService;
import org.aspectj.lang.ProceedingJoinPoint;
import org.aspectj.lang.annotation.Around;
import org.aspectj.lang.annotation.Aspect;
import org.springframework.stereotype.Component;

import java.util.Set;

/**
 * RBAC enforcement aspect (generated by engineering-platform ${asset.version}).
 *
 * Real enforcement point:
 *   HTTP request → authentication (AuthInterceptor sets RequestContext)
 *   → current user → roles → permissions → required permission → allow/deny
 */
@Aspect
@Component
public class PermissionAspect {

    private final UserQueryService userQueryService;

    public PermissionAspect(UserQueryService userQueryService) {
        this.userQueryService = userQueryService;
    }

    @Around("@annotation(requirePermission)")
    public Object enforce(ProceedingJoinPoint joinPoint, RequirePermission requirePermission) throws Throwable {
        // 1. authentication: current user must exist in RequestContext
        String currentUserId = RequestContext.currentUserId()
                .orElseThrow(() -> new PlatformException(SecurityErrorCodes.UNAUTHENTICATED));
        Long userId;
        try {
            userId = Long.valueOf(currentUserId);
        } catch (NumberFormatException e) {
            throw new PlatformException(SecurityErrorCodes.UNAUTHENTICATED);
        }

        // 2. authorization: user's permission codes must contain at least one required code
        Set<String> granted = userQueryService.permissionCodesOf(userId);
        boolean allowed = false;
        for (String required : requirePermission.value()) {
            if (granted.contains(required)) {
                allowed = true;
                break;
            }
        }
        if (!allowed) {
            throw new PlatformException(SecurityErrorCodes.PERMISSION_DENIED);
        }

        return joinPoint.proceed();
    }
}
