package ${package}.infrastructure.persistence;

import ${package}.application.organization.DepartmentPort;
import ${package}.application.rbac.PermissionManagementPort;
import ${package}.application.rbac.PermissionManagementService;
import ${package}.application.rbac.RoleManagementPort;
import ${package}.application.rbac.RoleManagementService;
import ${package}.application.rbac.UserManagementPort;
import ${package}.application.rbac.UserManagementService;
import ${package}.application.rbac.UserQueryPort;
import ${package}.application.rbac.UserQueryService;
import ${package}.infrastructure.persistence.mapper.SysPermissionMapper;
import ${package}.infrastructure.persistence.mapper.SysRoleMapper;
import ${package}.infrastructure.persistence.mapper.SysRolePermissionMapper;
import ${package}.infrastructure.persistence.mapper.SysUserMapper;
import ${package}.infrastructure.persistence.mapper.SysUserRoleMapper;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * RBAC bean wiring (generated by engineering-platform ${asset.version}).
 * MyBatis implementations are wired as the stable application contracts
 * (UserQueryPort / UserManagementPort / RoleManagementPort / PermissionManagementPort);
 * application services depend only on those contracts.
 */
@Configuration
public class RbacBeansConfig {

    @Bean
    public UserQueryPort userQueryPort(SysUserMapper userMapper, SysRoleMapper roleMapper,
                                       SysPermissionMapper permissionMapper,
                                       SysUserRoleMapper userRoleMapper,
                                       SysRolePermissionMapper rolePermissionMapper) {
        return new MybatisUserQueryRepository(userMapper, roleMapper, permissionMapper,
                userRoleMapper, rolePermissionMapper);
    }

    @Bean
    public UserQueryService userQueryService(UserQueryPort userQueryPort) {
        return new UserQueryService(userQueryPort);
    }

    @Bean
    public UserManagementPort userManagementPort(SysUserMapper userMapper,
                                                 SysUserRoleMapper userRoleMapper,
                                                 SysRoleMapper roleMapper) {
        return new MybatisUserManagementRepository(userMapper, userRoleMapper, roleMapper);
    }

    @Bean
    public UserManagementService userManagementService(UserManagementPort userManagementPort,
                                                       DepartmentPort departmentPort) {
        return new UserManagementService(userManagementPort, departmentPort);
    }

    @Bean
    public RoleManagementPort roleManagementPort(SysRoleMapper roleMapper,
                                                 SysRolePermissionMapper rolePermissionMapper,
                                                 SysPermissionMapper permissionMapper) {
        return new MybatisRoleManagementRepository(roleMapper, rolePermissionMapper, permissionMapper);
    }

    @Bean
    public RoleManagementService roleManagementService(RoleManagementPort roleManagementPort) {
        return new RoleManagementService(roleManagementPort);
    }

    @Bean
    public PermissionManagementPort permissionManagementPort(SysPermissionMapper permissionMapper) {
        return new MybatisPermissionManagementRepository(permissionMapper);
    }

    @Bean
    public PermissionManagementService permissionManagementService(
            PermissionManagementPort permissionManagementPort) {
        return new PermissionManagementService(permissionManagementPort);
    }
}
