package ${package}.infrastructure.persistence;

import ${package}.application.rbac.UserQueryPort;
import ${package}.application.rbac.UserQueryService;
import ${package}.infrastructure.persistence.mapper.SysUserMapper;
import ${package}.infrastructure.persistence.mapper.SysRoleMapper;
import ${package}.infrastructure.persistence.mapper.SysPermissionMapper;
import ${package}.infrastructure.persistence.mapper.SysUserRoleMapper;
import ${package}.infrastructure.persistence.mapper.SysRolePermissionMapper;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * RBAC bean wiring (generated by engineering-platform ${asset.version}).
 * The MyBatis implementation is wired as the UserQueryPort; application code
 * depends only on the stable contract.
 */
@Configuration
public class RbacBeansConfig {

    @Bean
    public UserQueryPort userQueryPort(SysUserMapper userMapper, SysRoleMapper roleMapper,
                                       SysPermissionMapper permissionMapper,
                                       SysUserRoleMapper userRoleMapper,
                                       SysRolePermissionMapper rolePermissionMapper) {
        return new MybatisUserQueryRepository(userMapper, roleMapper, permissionMapper,
                userRoleMapper, rolePermissionMapper);
    }

    @Bean
    public UserQueryService userQueryService(UserQueryPort userQueryPort) {
        return new UserQueryService(userQueryPort);
    }
}
