package ${package}.common.security;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * RBAC permission requirement (generated by engineering-platform ${asset.version}).
 *
 * Enforcement happens in PermissionAspect at the HTTP boundary:
 * request → authentication → current user → roles → permissions → required → allow/deny.
 */
@Target({ElementType.METHOD, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
public @interface RequirePermission {

    /** Required permission code(s); ANY match grants access. */
    String[] value();
}
