package ${package}.application.rbac;

import ${package}.common.core.ErrorCode;
import ${package}.common.core.PageQuery;
import ${package}.common.core.PageResult;
import ${package}.common.core.PlatformException;
import ${package}.common.security.DataScope;
import ${package}.domain.entity.SysPermission;
import ${package}.domain.entity.SysRole;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * Role management application service (generated by engineering-platform ${asset.version}).
 *
 * Orchestration, business validation and transaction boundaries live here, in
 * the application layer. Persistence goes through {@link RoleManagementPort} —
 * no MyBatis types appear in this class.
 *
 * create / update / enable / disable / assign permissions / data scope.
 * Role code is immutable once created (stable role code governance).
 */
public class RoleManagementService {

    private final RoleManagementPort managementPort;

    public RoleManagementService(RoleManagementPort managementPort) {
        this.managementPort = managementPort;
    }

    public PageResult<RoleResponse> page(PageQuery query, String keyword, Boolean enabled) {
        PageResult<SysRole> result = managementPort.page(query, keyword, enabled);
        List<RoleResponse> items = result.items().stream()
                .map(r -> toResponse(r, managementPort.permissionIdsOf(r.getId()))).toList();
        return PageResult.of(items, result.total(), result.page(), result.size());
    }

    public RoleResponse detail(Long id) {
        SysRole role = requireRole(id);
        return toResponse(role, managementPort.permissionIdsOf(id));
    }

    @Transactional
    public RoleResponse create(RoleCreateRequest request) {
        if (request.code() == null || request.code().isBlank()) {
            throw new PlatformException(ErrorCode.of("ROLE_CODE_REQUIRED", "role code is required"));
        }
        String code = request.code().trim();
        if (!code.matches("[a-z][a-z0-9-]{1,63}")) {
            throw new PlatformException(ErrorCode.of("ROLE_CODE_INVALID", "role code format invalid"));
        }
        if (managementPort.findByCode(code).isPresent()) {
            throw new PlatformException(ErrorCode.of("ROLE_CODE_DUPLICATE",
                    "role code already exists: " + code));
        }
        validateDataScope(request.dataScope());
        SysRole role = new SysRole();
        role.setCode(code);
        role.setName(request.name() == null || request.name().isBlank() ? code : request.name().trim());
        role.setEnabled(true);
        role.setDataScope(request.dataScope() == null ? DataScope.SELF.code() : request.dataScope());
        LocalDateTime now = LocalDateTime.now();
        role.setCreatedAt(now);
        role.setUpdatedAt(now);
        managementPort.insert(role);
        managementPort.replaceRolePermissions(role.getId(), request.permissionIds());
        return toResponse(role, managementPort.permissionIdsOf(role.getId()));
    }

    @Transactional
    public RoleResponse update(Long id, RoleUpdateRequest request) {
        SysRole role = requireRole(id);
        // code immutable
        if (request.name() != null && !request.name().isBlank()) {
            role.setName(request.name().trim());
        }
        validateDataScope(request.dataScope());
        if (request.dataScope() != null) {
            role.setDataScope(request.dataScope());
        }
        role.setUpdatedAt(LocalDateTime.now());
        managementPort.update(role);
        if (request.permissionIds() != null) {
            managementPort.replaceRolePermissions(id, request.permissionIds());
        }
        return toResponse(role, managementPort.permissionIdsOf(id));
    }

    @Transactional
    public RoleResponse setEnabled(Long id, boolean enabled) {
        SysRole role = requireRole(id);
        role.setEnabled(enabled);
        role.setUpdatedAt(LocalDateTime.now());
        managementPort.update(role);
        return toResponse(role, managementPort.permissionIdsOf(id));
    }

    @Transactional
    public RoleResponse assignPermissions(Long id, List<Long> permissionIds) {
        requireRole(id);
        validatePermissions(permissionIds);
        managementPort.replaceRolePermissions(id, permissionIds);
        return toResponse(requireRole(id), managementPort.permissionIdsOf(id));
    }

    // ---- helpers ------------------------------------------------------------

    private SysRole requireRole(Long id) {
        Optional<SysRole> role = managementPort.findById(id);
        if (role.isEmpty()) {
            throw new PlatformException(ErrorCode.of("ROLE_NOT_FOUND", "role not found: " + id));
        }
        return role.get();
    }

    private void validateDataScope(String dataScope) {
        if (dataScope == null) {
            return;
        }
        if (DataScope.fromCode(dataScope) == null) {
            throw new PlatformException(ErrorCode.of("ROLE_DATA_SCOPE_INVALID",
                    "invalid data scope: " + dataScope));
        }
    }

    private void validatePermissions(List<Long> permissionIds) {
        if (permissionIds == null) {
            return;
        }
        for (Long pid : permissionIds) {
            if (managementPort.findPermissionById(pid).isEmpty()) {
                throw new PlatformException(ErrorCode.of("PERMISSION_NOT_FOUND",
                        "permission not found: " + pid));
            }
        }
    }

    private RoleResponse toResponse(SysRole role, List<Long> permissionIds) {
        return RoleResponse.of(role.getId(), role.getCode(), role.getName(), role.getEnabled(),
                role.getDataScope(), permissionIds, role.getCreatedAt());
    }
}
