package ${package}.application.rbac;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import ${package}.common.core.LongIdDeserializer;

/**
 * Role update request (generated by engineering-platform ${asset.version}).
 * code is immutable once created (stable role code governance).
 */
public record RoleUpdateRequest(
        String name,
        String dataScope,
        @JsonDeserialize(contentUsing = LongIdDeserializer.class)
        java.util.List<Long> permissionIds) {
}
