package ${package}.application.rbac;

/**
 * Role create request (generated by engineering-platform ${asset.version}).
 */
public record RoleCreateRequest(
        String code,
        String name,
        String dataScope,
        java.util.List<Long> permissionIds) {
}
