package ${package}.api.role;

import ${package}.application.rbac.RoleCreateRequest;
import ${package}.application.rbac.RoleManagementService;
import ${package}.application.rbac.RoleResponse;
import ${package}.application.rbac.RoleUpdateRequest;
import ${package}.common.core.ApiResponse;
import ${package}.common.core.PageQuery;
import ${package}.common.core.PageResult;
import ${package}.common.security.OperationLog;
import ${package}.common.security.RequirePermission;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * Role management API (generated by engineering-platform ${asset.version}).
 * Role code immutable once created (stable governance); DataScope + permissions managed here.
 */
@RestController
@RequestMapping("/api/roles")
public class RoleManagementController {

    private final RoleManagementService roleManagementService;

    public RoleManagementController(RoleManagementService roleManagementService) {
        this.roleManagementService = roleManagementService;
    }

    @GetMapping
    @RequirePermission("system:role:read")
    public ApiResponse<PageResult<RoleResponse>> list(
            @RequestParam(defaultValue = "1") int page,
            @RequestParam(defaultValue = "20") int size,
            @RequestParam(required = false) String keyword,
            @RequestParam(required = false) Boolean enabled) {
        return ApiResponse.ofSuccess(roleManagementService.page(
                PageQuery.of(page, size), keyword, enabled));
    }

    @GetMapping("/{id}")
    @RequirePermission("system:role:read")
    public ApiResponse<RoleResponse> detail(@PathVariable Long id) {
        return ApiResponse.ofSuccess(roleManagementService.detail(id));
    }

    @PostMapping
    @RequirePermission("system:role:create")
    @OperationLog(operation = "ROLE_CREATE", resourceType = "ROLE")
    public ApiResponse<RoleResponse> create(@RequestBody RoleCreateRequest request) {
        return ApiResponse.ofSuccess(roleManagementService.create(request));
    }

    @PutMapping("/{id}")
    @RequirePermission("system:role:update")
    @OperationLog(operation = "ROLE_UPDATE", resourceType = "ROLE")
    public ApiResponse<RoleResponse> update(@PathVariable Long id,
                                            @RequestBody RoleUpdateRequest request) {
        return ApiResponse.ofSuccess(roleManagementService.update(id, request));
    }

    @PostMapping("/{id}/enable")
    @RequirePermission("system:role:update")
    @OperationLog(operation = "ROLE_ENABLE", resourceType = "ROLE")
    public ApiResponse<RoleResponse> enable(@PathVariable Long id) {
        return ApiResponse.ofSuccess(roleManagementService.setEnabled(id, true));
    }

    @PostMapping("/{id}/disable")
    @RequirePermission("system:role:disable")
    @OperationLog(operation = "ROLE_DISABLE", resourceType = "ROLE")
    public ApiResponse<RoleResponse> disable(@PathVariable Long id) {
        return ApiResponse.ofSuccess(roleManagementService.setEnabled(id, false));
    }

    @PostMapping("/{id}/permissions")
    @RequirePermission("system:role:assign-permission")
    @OperationLog(operation = "ROLE_ASSIGN_PERMISSION", resourceType = "ROLE")
    public ApiResponse<RoleResponse> assignPermissions(@PathVariable Long id,
                                                       @RequestBody List<Long> permissionIds) {
        return ApiResponse.ofSuccess(roleManagementService.assignPermissions(id, permissionIds));
    }
}
