package ${package}.application.rbac;

import ${package}.common.core.PageQuery;
import ${package}.common.core.PageResult;
import ${package}.domain.entity.SysPermission;
import ${package}.domain.entity.SysRole;

import java.util.List;
import java.util.Optional;

/**
 * Role management write/read contract (generated by engineering-platform ${asset.version}).
 *
 * Stable application-level management contract. The implementation lives in the
 * infrastructure layer (MyBatis-Plus); application/business code depends only
 * on this interface — never on MyBatis persistence types.
 *
 * Transaction semantics belong to the application service that orchestrates
 * these operations (e.g. create + permission assignment is one unit of work).
 */
public interface RoleManagementPort {

    PageResult<SysRole> page(PageQuery query, String keyword, Boolean enabled);

    Optional<SysRole> findById(Long roleId);

    Optional<SysRole> findByCode(String code);

    void insert(SysRole role);

    void update(SysRole role);

    /** Permission ids currently assigned to the role (stable order). */
    List<Long> permissionIdsOf(Long roleId);

    /** Replace all permissions of the role with the given ids (delete + insert). */
    void replaceRolePermissions(Long roleId, List<Long> permissionIds);

    Optional<SysPermission> findPermissionById(Long permissionId);
}
