package ${package}.application.rbac;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import ${package}.common.core.LongIdDeserializer;

/**
 * Role create request (generated by engineering-platform ${asset.version}).
 */
public record RoleCreateRequest(
        String code,
        String name,
        String dataScope,
        @JsonDeserialize(contentUsing = LongIdDeserializer.class)
        java.util.List<Long> permissionIds) {
}
