package ${package}.application.rbac;

/**
 * Role update request (generated by engineering-platform ${asset.version}).
 * code is immutable once created (stable role code governance).
 */
public record RoleUpdateRequest(
        String name,
        String dataScope,
        java.util.List<Long> permissionIds) {
}
