-- TEST-ONLY seed data (generated by engineering-platform ${asset.version})
-- Loaded only by the test profile (spring.sql.init in application-test.yml).
-- Never shipped as production default: no known admin credentials in production.

INSERT INTO sys_user (id, username, password_hash, enabled, created_at, updated_at) VALUES
  (1, 'admin', '$2b$10$YscrnLtO0WilTpA3rUY/Q.mhtMvDEAsqNHiI8Xm6/yV.ng8SQ26sm', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (2, 'viewer', '$2b$10$YscrnLtO0WilTpA3rUY/Q.mhtMvDEAsqNHiI8Xm6/yV.ng8SQ26sm', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (3, 'disabled', '$2b$10$YscrnLtO0WilTpA3rUY/Q.mhtMvDEAsqNHiI8Xm6/yV.ng8SQ26sm', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_role (id, code, name, enabled, created_at, updated_at) VALUES
  (1, 'admin', 'Administrator', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (2, 'viewer', 'Viewer', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_permission (id, code, name, created_at, updated_at) VALUES
  (1, 'system:user:read', 'Read users', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (7, 'system:user:create', 'Create users', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (8, 'system:user:update', 'Update users', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (9, 'system:user:disable', 'Disable users', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (10, 'system:user:assign-role', 'Assign roles to users', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (11, 'system:user:assign-department', 'Assign department to users', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (12, 'system:role:read', 'Read roles', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (13, 'system:role:create', 'Create roles', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (14, 'system:role:update', 'Update roles', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (15, 'system:role:disable', 'Disable roles', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (16, 'system:role:assign-permission', 'Assign permissions to roles', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (17, 'system:permission:read', 'Read permissions', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (18, 'system:department:read', 'Read departments', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (19, 'system:department:create', 'Create departments', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (20, 'system:department:update', 'Update departments', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (21, 'system:department:disable', 'Disable departments', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (22, 'system:menu:read', 'Read menus', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (23, 'system:menu:create', 'Create menus', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (24, 'system:menu:update', 'Update menus', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (25, 'system:menu:disable', 'Disable menus', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (26, 'system:dictionary:read', 'Read dictionaries', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (27, 'system:dictionary:create', 'Create dictionaries', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (28, 'system:dictionary:update', 'Update dictionaries', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (29, 'system:dictionary:disable', 'Disable dictionaries', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (30, 'system:operation-log:read', 'Read operation logs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_user_role (id, user_id, role_id, created_at) VALUES
  (1, 1, 1, CURRENT_TIMESTAMP),
  (2, 2, 2, CURRENT_TIMESTAMP),
  (3, 3, 2, CURRENT_TIMESTAMP);

INSERT INTO sys_role_permission (id, role_id, permission_id, created_at) VALUES
  (1, 1, 1, CURRENT_TIMESTAMP),
  -- V05-WORK-003: admin gets full enterprise management permissions (7-30);
  -- ids 100+ avoid collision with other assets' seeds (data-permission 2-6, menu 7, product 8-13)
  (100, 1, 7, CURRENT_TIMESTAMP), (101, 1, 8, CURRENT_TIMESTAMP),
  (102, 1, 9, CURRENT_TIMESTAMP), (103, 1, 10, CURRENT_TIMESTAMP),
  (104, 1, 11, CURRENT_TIMESTAMP), (105, 1, 12, CURRENT_TIMESTAMP),
  (106, 1, 13, CURRENT_TIMESTAMP), (107, 1, 14, CURRENT_TIMESTAMP),
  (108, 1, 15, CURRENT_TIMESTAMP), (109, 1, 16, CURRENT_TIMESTAMP),
  (110, 1, 17, CURRENT_TIMESTAMP), (111, 1, 18, CURRENT_TIMESTAMP),
  (112, 1, 19, CURRENT_TIMESTAMP), (113, 1, 20, CURRENT_TIMESTAMP),
  (114, 1, 21, CURRENT_TIMESTAMP), (115, 1, 22, CURRENT_TIMESTAMP),
  (116, 1, 23, CURRENT_TIMESTAMP), (117, 1, 24, CURRENT_TIMESTAMP),
  (118, 1, 25, CURRENT_TIMESTAMP), (119, 1, 26, CURRENT_TIMESTAMP),
  (120, 1, 27, CURRENT_TIMESTAMP), (121, 1, 28, CURRENT_TIMESTAMP),
  (122, 1, 29, CURRENT_TIMESTAMP), (123, 1, 30, CURRENT_TIMESTAMP);
