-- TEST-ONLY seed data (generated by engineering-platform ${asset.version})
-- Loaded only by the test profile (spring.sql.init in application-test.yml).
-- Never shipped as production default: no known admin credentials in production.

INSERT INTO sys_user (id, username, password_hash, enabled, created_at, updated_at) VALUES
  (1, 'admin', '$2b$10$YscrnLtO0WilTpA3rUY/Q.mhtMvDEAsqNHiI8Xm6/yV.ng8SQ26sm', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (2, 'viewer', '$2b$10$YscrnLtO0WilTpA3rUY/Q.mhtMvDEAsqNHiI8Xm6/yV.ng8SQ26sm', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (3, 'disabled', '$2b$10$YscrnLtO0WilTpA3rUY/Q.mhtMvDEAsqNHiI8Xm6/yV.ng8SQ26sm', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_role (id, code, name, enabled, created_at, updated_at) VALUES
  (1, 'admin', 'Administrator', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (2, 'viewer', 'Viewer', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_permission (id, code, name, created_at, updated_at) VALUES
  (1, 'system:user:read', 'Read users', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_user_role (id, user_id, role_id, created_at) VALUES
  (1, 1, 1, CURRENT_TIMESTAMP),
  (2, 2, 2, CURRENT_TIMESTAMP),
  (3, 3, 2, CURRENT_TIMESTAMP);

INSERT INTO sys_role_permission (id, role_id, permission_id, created_at) VALUES
  (1, 1, 1, CURRENT_TIMESTAMP);
