package ${package}.infrastructure.persistence.mapper;

import ${package}.domain.entity.SysPermission;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;

/**
 * MyBatis-Plus mapper for SysPermission (generated by engineering-platform ${asset.version}).
 * Persistence implementation only — never leaks into business/API layers.
 */
@Mapper
public interface SysPermissionMapper extends BaseMapper<SysPermission> {
}
