package ${package}.infrastructure.persistence.mapper;

import ${package}.domain.entity.SysUser;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;

/**
 * MyBatis-Plus mapper for SysUser (generated by engineering-platform ${asset.version}).
 * Persistence implementation only — never leaks into business/API layers.
 */
@Mapper
public interface SysUserMapper extends BaseMapper<SysUser> {
}
