package ${package}.api.user;

import ${package}.common.core.ApiResponse;
import ${package}.common.core.PlatformException;
import ${package}.common.core.RequestContext;
import ${package}.common.security.SecurityErrorCodes;
import ${package}.domain.entity.SysUser;
import ${package}.application.rbac.UserQueryService;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Security user API (generated by engineering-platform ${asset.version}).
 * GET /api/users/me — authenticated current user with permission codes.
 * Management list/create/update endpoints live in UserManagementController.
 */
@RestController
@RequestMapping("/api/users")
public class UserController {

    private final UserQueryService userQueryService;

    public UserController(UserQueryService userQueryService) {
        this.userQueryService = userQueryService;
    }

    /** Authenticated current user (token required via interceptor).
     *  Returns safe profile + permission codes for frontend UX.
     *  V05-WORK-002: permission codes exposed so the UI can render menus/buttons;
     *  backend @RequirePermission stays the final security boundary. */
    @GetMapping("/me")
    public ApiResponse<CurrentUserResponse> me() {
        String currentUserId = RequestContext.currentUserId()
                .orElseThrow(() -> new PlatformException(SecurityErrorCodes.UNAUTHENTICATED));
        Long userId = Long.valueOf(currentUserId);
        SysUser user = userQueryService.findById(userId)
                .orElseThrow(() -> new PlatformException(SecurityErrorCodes.UNAUTHENTICATED));
        java.util.Set<String> permissions = userQueryService.permissionCodesOf(userId);
        return ApiResponse.ofSuccess(CurrentUserResponse.of(
                user.getId(), user.getUsername(), user.getDepartmentId(), permissions));
    }
}
