package ${package}.application.rbac;

import ${package}.common.core.ErrorCode;
import ${package}.common.core.PageQuery;
import ${package}.common.core.PageResult;
import ${package}.common.core.PlatformException;
import ${package}.common.security.PasswordEncoder;
import ${package}.domain.entity.SysRole;
import ${package}.domain.entity.SysUser;
import ${package}.application.organization.DepartmentPort;
import ${package}.domain.entity.SysDepartment;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * User management application service (generated by engineering-platform ${asset.version}).
 *
 * Orchestration, business validation and transaction boundaries live here, in
 * the application layer. Persistence goes through {@link UserManagementPort} —
 * no MyBatis types appear in this class.
 *
 * Write operations: create / update / enable / disable / assign roles / assign department.
 * Security: BCrypt initial password (never echoed, never logged), no passwordHash
 * exposure, transactional role assignment, department enabled validation.
 */
public class UserManagementService {

    private final UserManagementPort managementPort;
    private final DepartmentPort departmentPort;

    public UserManagementService(UserManagementPort managementPort, DepartmentPort departmentPort) {
        this.managementPort = managementPort;
        this.departmentPort = departmentPort;
    }

    // ---- query ------------------------------------------------------------

    public PageResult<UserResponse> page(PageQuery query, String usernameKeyword, Boolean enabled,
                                         Long departmentId) {
        PageResult<SysUser> result = managementPort.page(query, usernameKeyword, enabled, departmentId);
        List<UserResponse> items = result.items().stream()
                .map(u -> toResponse(u, managementPort.roleIdsOf(u.getId()))).toList();
        return PageResult.of(items, result.total(), result.page(), result.size());
    }

    public UserResponse detail(Long id) {
        SysUser user = requireUser(id);
        return toResponse(user, managementPort.roleIdsOf(id));
    }

    // ---- write ------------------------------------------------------------

    @Transactional
    public UserCreateResult create(UserCreateRequest request) {
        if (request.username() == null || request.username().isBlank()) {
            throw new PlatformException(ErrorCode.of("USERNAME_REQUIRED", "username is required"));
        }
        String username = request.username().trim();
        if (!username.matches("[A-Za-z0-9._-]{3,64}")) {
            throw new PlatformException(ErrorCode.of("USERNAME_INVALID", "username format invalid"));
        }
        if (managementPort.usernameExists(username, null)) {
            throw new PlatformException(ErrorCode.of("USERNAME_DUPLICATE",
                    "username already exists: " + username));
        }
        if (request.departmentId() != null) {
            requireEnabledDepartment(request.departmentId());
        }
        validateRoles(request.roleIds());

        SysUser user = new SysUser();
        user.setUsername(username);
        String initialPassword = request.initialPassword() != null && !request.initialPassword().isBlank()
                ? request.initialPassword()
                : java.util.UUID.randomUUID().toString().replace("-", "").substring(0, 12);
        user.setPasswordHash(PasswordEncoder.hash(initialPassword));
        user.setEnabled(true);
        user.setDepartmentId(request.departmentId());
        LocalDateTime now = LocalDateTime.now();
        user.setCreatedAt(now);
        user.setUpdatedAt(now);
        managementPort.insert(user);

        managementPort.replaceUserRoles(user.getId(), request.roleIds());
        // initial password returned exactly once here; never logged elsewhere
        return new UserCreateResult(toResponse(user, managementPort.roleIdsOf(user.getId())),
                initialPassword);
    }

    @Transactional
    public UserResponse update(Long id, UserUpdateRequest request) {
        SysUser user = requireUser(id);
        if (request.username() != null && !request.username().isBlank()
                && !request.username().trim().equals(user.getUsername())) {
            String username = request.username().trim();
            if (managementPort.usernameExists(username, id)) {
                throw new PlatformException(ErrorCode.of("USERNAME_DUPLICATE",
                        "username already exists: " + username));
            }
            user.setUsername(username);
        }
        if (request.departmentId() != null && !request.departmentId().equals(user.getDepartmentId())) {
            requireEnabledDepartment(request.departmentId());
            user.setDepartmentId(request.departmentId());
        }
        user.setUpdatedAt(LocalDateTime.now());
        managementPort.update(user);
        if (request.roleIds() != null) {
            managementPort.replaceUserRoles(id, request.roleIds());
        }
        return toResponse(user, managementPort.roleIdsOf(id));
    }

    @Transactional
    public UserResponse setEnabled(Long id, boolean enabled) {
        SysUser user = requireUser(id);
        user.setEnabled(enabled);
        user.setUpdatedAt(LocalDateTime.now());
        managementPort.update(user);
        return toResponse(user, managementPort.roleIdsOf(id));
    }

    @Transactional
    public UserResponse assignRoles(Long id, List<Long> roleIds) {
        requireUser(id);
        validateRoles(roleIds);
        managementPort.replaceUserRoles(id, roleIds);
        return toResponse(requireUser(id), managementPort.roleIdsOf(id));
    }

    @Transactional
    public UserResponse assignDepartment(Long id, Long departmentId) {
        SysUser user = requireUser(id);
        requireEnabledDepartment(departmentId);
        user.setDepartmentId(departmentId);
        user.setUpdatedAt(LocalDateTime.now());
        managementPort.update(user);
        return toResponse(user, managementPort.roleIdsOf(id));
    }

    // ---- helpers ------------------------------------------------------------

    private SysUser requireUser(Long id) {
        Optional<SysUser> user = managementPort.findById(id);
        if (user.isEmpty()) {
            throw new PlatformException(ErrorCode.of("USER_NOT_FOUND", "user not found: " + id));
        }
        return user.get();
    }

    private void requireEnabledDepartment(Long departmentId) {
        if (departmentId == null) {
            return;
        }
        Optional<SysDepartment> dept = departmentPort.findById(departmentId);
        if (dept.isEmpty()) {
            throw new PlatformException(ErrorCode.of("DEPARTMENT_NOT_FOUND",
                    "department not found: " + departmentId));
        }
        if (!Boolean.TRUE.equals(dept.get().getEnabled())) {
            throw new PlatformException(ErrorCode.of("DEPARTMENT_DISABLED",
                    "department disabled: " + departmentId));
        }
    }

    private void validateRoles(List<Long> roleIds) {
        if (roleIds == null) {
            return;
        }
        for (Long roleId : roleIds) {
            Optional<SysRole> role = managementPort.findRoleById(roleId);
            if (role.isEmpty()) {
                throw new PlatformException(ErrorCode.of("ROLE_NOT_FOUND", "role not found: " + roleId));
            }
            if (!Boolean.TRUE.equals(role.get().getEnabled())) {
                throw new PlatformException(ErrorCode.of("ROLE_DISABLED", "role disabled: " + roleId));
            }
        }
    }

    private UserResponse toResponse(SysUser user, List<Long> roleIds) {
        return UserResponse.of(user.getId(), user.getUsername(), user.getEnabled(),
                user.getDepartmentId(), roleIds, user.getCreatedAt());
    }

    /** Create result: response + initial password (returned once). */
    public record UserCreateResult(UserResponse user, String initialPassword) {
    }
}
