package ${package}.application.rbac;

import java.time.LocalDateTime;
import java.util.List;

/**
 * User management response (generated by engineering-platform ${asset.version}).
 * Never exposes passwordHash or any password material.
 */
public record UserResponse(
        Long id,
        String username,
        Boolean enabled,
        Long departmentId,
        List<Long> roleIds,
        LocalDateTime createdAt) {

    public static UserResponse of(Long id, String username, Boolean enabled,
                                  Long departmentId, List<Long> roleIds, LocalDateTime createdAt) {
        return new UserResponse(id, username, enabled, departmentId, roleIds, createdAt);
    }
}
