package ${package}.api.user;

import ${package}.application.rbac.UserCreateRequest;
import ${package}.application.rbac.UserManagementService;
import ${package}.application.rbac.UserResponse;
import ${package}.application.rbac.UserUpdateRequest;
import ${package}.common.core.ApiResponse;
import ${package}.common.core.PageQuery;
import ${package}.common.core.PageResult;
import ${package}.common.security.OperationLog;
import ${package}.common.security.RequirePermission;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;
import java.util.Map;

/**
 * User management API (generated by engineering-platform ${asset.version}).
 * All write operations are permission-protected and operation-logged.
 * Initial password returned once on create (never logged, never echoed later).
 */
@RestController
@RequestMapping("/api/users")
public class UserManagementController {

    private final UserManagementService userManagementService;

    public UserManagementController(UserManagementService userManagementService) {
        this.userManagementService = userManagementService;
    }

    @GetMapping
    @RequirePermission("system:user:read")
    public ApiResponse<PageResult<UserResponse>> list(
            @RequestParam(defaultValue = "1") int page,
            @RequestParam(defaultValue = "20") int size,
            @RequestParam(required = false) String username,
            @RequestParam(required = false) Boolean enabled,
            @RequestParam(required = false) Long departmentId) {
        return ApiResponse.ofSuccess(userManagementService.page(
                PageQuery.of(page, size), username, enabled, departmentId));
    }

    @GetMapping("/{id}")
    @RequirePermission("system:user:read")
    public ApiResponse<UserResponse> detail(@PathVariable Long id) {
        return ApiResponse.ofSuccess(userManagementService.detail(id));
    }

    @PostMapping
    @RequirePermission("system:user:create")
    @OperationLog(operation = "USER_CREATE", resourceType = "USER")
    public ApiResponse<Map<String, Object>> create(@RequestBody UserCreateRequest request) {
        UserManagementService.UserCreateResult result = userManagementService.create(request);
        // initial password returned exactly once
        return ApiResponse.ofSuccess(Map.of(
                "user", result.user(),
                "initialPassword", result.initialPassword()));
    }

    @PutMapping("/{id}")
    @RequirePermission("system:user:update")
    @OperationLog(operation = "USER_UPDATE", resourceType = "USER")
    public ApiResponse<UserResponse> update(@PathVariable Long id,
                                            @RequestBody UserUpdateRequest request) {
        return ApiResponse.ofSuccess(userManagementService.update(id, request));
    }

    @PostMapping("/{id}/enable")
    @RequirePermission("system:user:update")
    @OperationLog(operation = "USER_ENABLE", resourceType = "USER")
    public ApiResponse<UserResponse> enable(@PathVariable Long id) {
        return ApiResponse.ofSuccess(userManagementService.setEnabled(id, true));
    }

    @PostMapping("/{id}/disable")
    @RequirePermission("system:user:disable")
    @OperationLog(operation = "USER_DISABLE", resourceType = "USER")
    public ApiResponse<UserResponse> disable(@PathVariable Long id) {
        return ApiResponse.ofSuccess(userManagementService.setEnabled(id, false));
    }

    @PostMapping("/{id}/roles")
    @RequirePermission("system:user:assign-role")
    @OperationLog(operation = "USER_ASSIGN_ROLE", resourceType = "USER")
    public ApiResponse<UserResponse> assignRoles(@PathVariable Long id,
                                                 @RequestBody List<Long> roleIds) {
        return ApiResponse.ofSuccess(userManagementService.assignRoles(id, roleIds));
    }

    @PostMapping("/{id}/department")
    @RequirePermission("system:user:assign-department")
    @OperationLog(operation = "USER_ASSIGN_DEPARTMENT", resourceType = "USER")
    public ApiResponse<UserResponse> assignDepartment(@PathVariable Long id,
                                                      @RequestBody Map<String, Long> body) {
        return ApiResponse.ofSuccess(userManagementService.assignDepartment(id, body.get("departmentId")));
    }
}
