package ${package}.api.user;

import ${package}.common.core.ApiResponse;
import ${package}.common.core.PlatformException;
import ${package}.common.core.RequestContext;
import ${package}.common.security.RequirePermission;
import ${package}.common.security.SecurityErrorCodes;
import ${package}.domain.entity.SysUser;
import ${package}.application.rbac.UserQueryService;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Security user API (generated by engineering-platform ${asset.version}).
 */
@RestController
@RequestMapping("/api")
public class UserController {

    private final UserQueryService userQueryService;

    public UserController(UserQueryService userQueryService) {
        this.userQueryService = userQueryService;
    }

    /** Authenticated current user (token required via interceptor). */
    @GetMapping("/users/me")
    public ApiResponse<SysUser> me() {
        String currentUserId = RequestContext.currentUserId()
                .orElseThrow(() -> new PlatformException(SecurityErrorCodes.UNAUTHENTICATED));
        SysUser user = userQueryService.findById(Long.valueOf(currentUserId))
                .orElseThrow(() -> new PlatformException(SecurityErrorCodes.UNAUTHENTICATED));
        return ApiResponse.ofSuccess(user);
    }

    /** Permission-protected endpoint: requires system:user:read. */
    @GetMapping("/users")
    @RequirePermission("system:user:read")
    public ApiResponse<java.util.List<SysUser>> users() {
        return ApiResponse.ofSuccess(userQueryService.findAll());
    }
}
