package ${package}.application.rbac;

import ${package}.domain.entity.SysUser;

import java.util.List;
import java.util.Optional;
import java.util.Set;

/**
 * RBAC read contract (generated by engineering-platform ${asset.version}).
 *
 * Stable application-level query contract. The implementation lives in the
 * infrastructure layer (MyBatis-Plus); application/business code depends only
 * on this interface — never on QueryWrapper / BaseMapper / IPage.
 */
public interface UserQueryPort {

    Optional<SysUser> findByUsername(String username);

    Optional<SysUser> findById(Long userId);

    List<SysUser> findAll();

    /** All permission codes granted to a user via their enabled roles. */
    Set<String> permissionCodesOf(Long userId);
}
