package ${package}.application.rbac;

/**
 * User update request (generated by engineering-platform ${asset.version}).
 * Password reset is NOT part of this request (password reset workflow out of scope).
 */
public record UserUpdateRequest(
        String username,
        Long departmentId,
        java.util.List<Long> roleIds) {
}
