package ${package}.application.rbac;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import ${package}.common.core.LongIdDeserializer;

/**
 * User create request (generated by engineering-platform ${asset.version}).
 * Initial password: system-generated, returned once in the create response
 * (test/ops mode). Never echoed in logs or operation log.
 */
public record UserCreateRequest(
        String username,
        String initialPassword,
        @JsonDeserialize(using = LongIdDeserializer.class)
        Long departmentId,
        @JsonDeserialize(contentUsing = LongIdDeserializer.class)
        java.util.List<Long> roleIds) {
}
