package ${package}.application.rbac;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import ${package}.common.core.LongIdDeserializer;

/**
 * User update request (generated by engineering-platform ${asset.version}).
 * Password reset is NOT part of this request (password reset workflow out of scope).
 */
public record UserUpdateRequest(
        String username,
        @JsonDeserialize(using = LongIdDeserializer.class)
        Long departmentId,
        @JsonDeserialize(contentUsing = LongIdDeserializer.class)
        java.util.List<Long> roleIds) {
}
