// Login + App Shell + Dynamic Menu E2E (generated by engineering-platform playwright-e2e asset)
import { test, expect, loginAs } from './fixtures';

test.describe('login & shell', () => {
  test('wrong password shows error feedback', async ({ page }) => {
    await page.goto('/login');
    await page.getByTestId('login-username').fill('admin');
    await page.getByTestId('login-password').fill('wrong-password');
    await page.getByTestId('login-submit').click();
    await expect(page.getByTestId('login-error')).toBeVisible({ timeout: 10_000 });
    expect(page.url()).toContain('/login');
  });

  test('admin logs in, shell visible, dynamic menu loaded', async ({ page }) => {
    await loginAs(page, 'admin', 'admin123');
    // shell: header with current user
    await expect(page.getByText('admin').first()).toBeVisible({ timeout: 15_000 });
    // dynamic menu from /api/menus/me: System directory visible
    await expect(page.getByText('System').first()).toBeVisible({ timeout: 15_000 });
    // expand System to reveal management items (sub-menu children are hidden until open)
    await page.getByText('System').first().click();
    await expect(page.getByText('User management').first()).toBeVisible({ timeout: 10_000 });
  });

  test('logout returns to login', async ({ page }) => {
    await loginAs(page, 'admin', 'admin123');
    await page.getByRole('button', { name: /logout/i }).first().click();
    await page.waitForURL(/\/login/, { timeout: 15_000 });
    expect(page.url()).toContain('/login');
  });
});

test.describe('dynamic menu by role', () => {
  test('admin sees full management menu set', async ({ page }) => {
    await loginAs(page, 'admin', 'admin123');
    await page.getByText('System').first().click();
    for (const item of ['User management', 'Role & Permission', 'Permission registry',
      'Department management', 'Menu management', 'Dictionary management', 'Operation log']) {
      await expect(page.getByRole('menuitem', { name: new RegExp(item, 'i') }).first())
        .toBeVisible({ timeout: 10_000 });
    }
    await expect(page.getByRole('menuitem', { name: /Products/i }).first()).toBeVisible();
  });

  test('limited user (viewer) sees filtered menu (no management menus)', async ({ page }) => {
    await loginAs(page, 'viewer', 'admin123');
    await expect(page.getByText('System').first()).not.toBeVisible({ timeout: 10_000 });
  });
});
