// Operation Log Browser E2E (generated by engineering-platform playwright-e2e asset)
// Golden Path: a write operation must be visible in the log (read-only surface).
// Row-expand details (requestId/correlationId) are covered by HTTP E2E.
import { test, expect, loginAs } from './fixtures';

test.describe('operation log', () => {
  test('write operation appears in log (read-only surface, no sensitive fields)', async ({ page }) => {
    await loginAs(page, 'admin', 'admin123');

    // perform a logged write: create a dictionary item
    await page.getByText('System').first().click();
    await page.getByRole('menuitem', { name: /Dictionary management/i }).first().click();
    await page.waitForURL(/\/system\/dictionaries/, { timeout: 15_000 });
    await page.getByText('Gender').first().click();
    await page.getByTestId('create-item').click();
    const value = 'LOG_' + Date.now().toString().slice(-6);
    await page.getByTestId('item-form-value').fill(value);
    await page.getByTestId('item-form-label').fill('Log Probe');
    await page.getByTestId('app-form-submit').click();
    await expect(page.getByText('Dictionary item created').first()).toBeVisible({ timeout: 10_000 });

    // open operation log
    await page.getByText('System').first().click();
    await page.getByRole('menuitem', { name: /Operation log/i }).first().click();
    await page.waitForURL(/\/system\/operation-logs/, { timeout: 15_000 });
    await expect(page.getByText('Operation Log').first()).toBeVisible({ timeout: 15_000 });
    // our operation recorded (DICTIONARY_ITEM_CREATE); no edit/delete controls (read-only)
    await expect(page.getByText('DICTIONARY_ITEM_CREATE').first()).toBeVisible({ timeout: 15_000 });
    await expect(page.getByTestId('oplog-create')).not.toBeVisible({ timeout: 5_000 }).catch(() => undefined);
    // page does not render sensitive fields (no password/token material in table)
    const body = await page.locator('body').innerText();
    expect(body).not.toMatch(/password|token secret|AUTH_TOKEN/i);
  });
});
