// Product Full-stack Browser E2E (generated by engineering-platform playwright-e2e asset)
import { test, expect, loginAs } from './fixtures';

test.describe('product full-stack', () => {
  test.beforeEach(async ({ page }) => {
    await loginAs(page, 'admin', 'admin123');
    await page.getByText('Products').first().click();
    await page.getByRole('menuitem', { name: /Product list/i }).first().click();
    await page.waitForURL(/\/products/, { timeout: 15_000 });
  });

  test('list loads with dictionary-driven status labels', async ({ page }) => {
    await expect(page.getByText('Products').first()).toBeVisible({ timeout: 15_000 });
    await expect(page.getByText('PRD-001').first()).toBeVisible({ timeout: 15_000 });
  });

  test('search/filter narrows rows', async ({ page }) => {
    await page.getByTestId('product-search-keyword').fill('PRD-001');
    await page.getByTestId('search-form-submit').click();
    await expect(page.getByText('PRD-001').first()).toBeVisible({ timeout: 10_000 });
    await expect(page.getByText('PRD-002').first()).not.toBeVisible({ timeout: 10_000 });
  });

  test('create product via drawer with dictionary status', async ({ page }) => {
    const code = 'PRD-E2E-' + Date.now().toString().slice(-6);
    await page.getByTestId('create-product').click();
    await page.getByTestId('product-form-code').fill(code);
    await page.getByTestId('product-form-name').fill('E2E Product');
    await page.getByTestId('app-form-submit').click();
    await expect(page.getByText('Product created').first()).toBeVisible({ timeout: 10_000 });
    await expect(page.getByText(code).first()).toBeVisible({ timeout: 10_000 });
  });

  test('detail page shows information hierarchy', async ({ page }) => {
    await expect(page.getByText('PRD-001').first()).toBeVisible({ timeout: 15_000 });
    await page.getByTestId('product-detail-open').first().click();
    await page.waitForURL(/\/products\/\d+$/, { timeout: 10_000 });
    await expect(page.getByTestId('product-detail')).toBeVisible({ timeout: 10_000 });
    await expect(page.getByTestId('detail-code')).toContainText('PRD-001');
  });

  test('disable product via confirm', async ({ page }) => {
    const code = 'PRD-DIS-' + Date.now().toString().slice(-6);
    await page.getByTestId('create-product').click();
    await page.getByTestId('product-form-code').fill(code);
    await page.getByTestId('product-form-name').fill('To Disable');
    await page.getByTestId('app-form-submit').click();
    await expect(page.getByText('Product created').first()).toBeVisible({ timeout: 10_000 });
    // search for the new product (list is id-asc ordered; new row may be beyond page 1)
    await page.getByTestId('product-search-keyword').fill(code);
    await page.getByTestId('search-form-submit').click();
    await expect(page.getByText(code).first()).toBeVisible({ timeout: 10_000 });
    // disable via row ConfirmAction trigger -> popconfirm confirm
    await page.getByTestId('product-disable-trigger').first().click();
    await page.locator('.el-popconfirm').getByRole('button', { name: /Confirm/i }).click();
    // row still present after refresh; toast confirms disable (transient — poll briefly)
    await expect(page.getByText(code).first()).toBeVisible({ timeout: 10_000 });
    await expect(page.getByText('Product disabled').first()).toBeVisible({ timeout: 10_000 });
  });
});
