package ${package}.common.error;

import java.time.Instant;
import java.util.List;

/**
 * Unified error response body (generated by engineering-platform ${asset.version}).
 * Conformance: required file for exception-handling capability.
 */
public record ApiError(
        Instant timestamp,
        int status,
        String code,
        String message,
        List<FieldViolation> violations) {

    public static ApiError of(int status, String code, String message) {
        return new ApiError(Instant.now(), status, code, message, List.of());
    }

    public static ApiError of(int status, String code, String message, List<FieldViolation> violations) {
        return new ApiError(Instant.now(), status, code, message, violations);
    }

    public record FieldViolation(String field, String message) {
    }
}
