package ${package}.infrastructure.persistence;

import ${package}.application.datascope.DataPermissionContext;
import ${package}.application.organization.DepartmentPort;
import ${package}.application.product.ProductPort;
import ${package}.common.core.PageQuery;
import ${package}.common.core.PageResult;
import ${package}.common.security.DataScope;
import ${package}.domain.entity.Product;
import ${package}.infrastructure.persistence.mapper.ProductMapper;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;

import java.util.List;
import java.util.Optional;
import java.util.Set;

/**
 * MyBatis-Plus implementation of {@link ProductPort} with real data-permission
 * enforcement (generated by engineering-platform ${asset.version}).
 *
 * Data scope enforcement happens HERE, at the query boundary:
 *   ALL                    → no restriction
 *   DEPARTMENT             → department_id = context.departmentId
 *   DEPARTMENT_AND_CHILDREN→ department_id IN (department + descendants)
 *   SELF                   → created_by = current user
 *
 * Fail-safe: missing department with a department-dependent scope denies (empty),
 * never upgrades to ALL. All MyBatis types stay confined to infrastructure.
 */
public class MybatisProductRepository implements ProductPort {

    private final ProductMapper productMapper;
    private final DepartmentPort departmentPort;

    public MybatisProductRepository(ProductMapper productMapper, DepartmentPort departmentPort) {
        this.productMapper = productMapper;
        this.departmentPort = departmentPort;
    }

    @Override
    public Optional<Product> findById(Long id) {
        return Optional.ofNullable(productMapper.selectById(id));
    }

    @Override
    public Optional<Product> findByIdInScope(Long id, DataPermissionContext context) {
        return findByScope(context).stream().filter(p -> p.getId().equals(id)).findFirst();
    }

    @Override
    public List<Product> findByScope(DataPermissionContext context) {
        QueryWrapper<Product> wrapper = scopeWrapper(context);
        wrapper.orderByAsc("id");
        return productMapper.selectList(wrapper);
    }

    @Override
    public PageResult<Product> findPageByScope(DataPermissionContext context, PageQuery query) {
        QueryWrapper<Product> countWrapper = scopeWrapper(context);
        long total = productMapper.selectCount(countWrapper);
        QueryWrapper<Product> pageWrapper = scopeWrapper(context);
        pageWrapper.orderByAsc("id");
        pageWrapper.last("LIMIT " + query.size() + " OFFSET " + query.offset());
        List<Product> items = productMapper.selectList(pageWrapper);
        return PageResult.of(items, total, query.page(), query.size());
    }

    private QueryWrapper<Product> scopeWrapper(DataPermissionContext context) {
        QueryWrapper<Product> wrapper = new QueryWrapper<>();
        DataScope scope = context.scope() == null ? DataScope.SELF : context.scope();
        switch (scope) {
            case ALL -> {
                // no restriction
            }
            case DEPARTMENT -> {
                if (context.departmentId() == null) {
                    wrapper.eq("id", -1L); // fail-safe deny
                } else {
                    wrapper.eq("department_id", context.departmentId());
                }
            }
            case DEPARTMENT_AND_CHILDREN -> {
                if (context.departmentId() == null) {
                    wrapper.eq("id", -1L); // fail-safe deny
                } else {
                    Set<Long> ids = departmentPort.descendantIds(context.departmentId());
                    ids.add(context.departmentId());
                    wrapper.in("department_id", ids);
                }
            }
            case SELF -> {
                if (context.userId() == null) {
                    wrapper.eq("id", -1L); // fail-safe deny
                } else {
                    wrapper.eq("created_by", String.valueOf(context.userId()));
                }
            }
        }
        return wrapper;
    }

    @Override
    public boolean existsByCode(String code, Long excludeId) {
        QueryWrapper<Product> wrapper = new QueryWrapper<>();
        wrapper.eq("code", code);
        if (excludeId != null) {
            wrapper.ne("id", excludeId);
        }
        return productMapper.selectCount(wrapper) > 0;
    }

    @Override
    public Product insert(Product product) {
        productMapper.insert(product);
        return product;
    }

    @Override
    public int update(Product product) {
        return productMapper.updateById(product);
    }
}
