package ${package}.application.product;

import ${package}.application.datascope.DataPermissionContext;
import ${package}.application.dictionary.DictionaryPort;
import ${package}.common.core.ErrorCode;
import ${package}.common.core.PageQuery;
import ${package}.common.core.PageResult;
import ${package}.common.core.PlatformException;
import ${package}.domain.entity.DictionaryItem;
import ${package}.domain.entity.Product;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Set;

/**
 * Product application service (generated by engineering-platform ${asset.version}).
 *
 * Consumes Platform Core (ApiResponse via controller, PageQuery/PageResult,
 * PlatformException/ErrorCode), Dictionary (status/category validation),
 * Data Permission (detail/update/list all enforce scope), and Operation Log
 * (write operations are annotated at the controller boundary).
 *
 * Client never supplies createdBy/departmentId: they come from the
 * authenticated RequestContext (current user / their department).
 */
public class ProductService {

    private static final Set<String> KNOWN_STATUS = Set.of("ENABLED", "DISABLED");

    private final ProductPort productPort;
    private final DictionaryPort dictionaryPort;

    public ProductService(ProductPort productPort, DictionaryPort dictionaryPort) {
        this.productPort = productPort;
        this.dictionaryPort = dictionaryPort;
    }

    // ---- create ----------------------------------------------------------

    public ProductResponse create(ProductCreateRequest request, Long userId, Long departmentId) {
        validateCode(request.code());
        validateName(request.name());
        String status = normalizeStatus(request.status());
        String category = normalizeCategory(request.category());
        if (productPort.existsByCode(request.code(), null)) {
            throw new PlatformException(ErrorCode.of("PRODUCT_CODE_DUPLICATE",
                    "product code already exists: " + request.code()));
        }
        Product product = new Product();
        product.setCode(request.code());
        product.setName(request.name().trim());
        product.setStatus(status);
        product.setCategory(category);
        product.setDepartmentId(departmentId);
        product.setCreatedBy(userId);
        LocalDateTime now = LocalDateTime.now();
        product.setCreatedAt(now);
        product.setUpdatedAt(now);
        productPort.insert(product);
        return toResponse(product);
    }

    // ---- detail ----------------------------------------------------------

    public ProductResponse get(Long id, DataPermissionContext context) {
        Product product = productPort.findByIdInScope(id, context)
                .orElseThrow(() -> new PlatformException(ErrorCode.of("PRODUCT_NOT_FOUND",
                        "product not found: " + id)));
        return toResponse(product);
    }

    // ---- list / page ------------------------------------------------------

    public List<ProductResponse> list(DataPermissionContext context) {
        return productPort.findByScope(context).stream().map(this::toResponse).toList();
    }

    public PageResult<ProductResponse> page(PageQuery query, DataPermissionContext context) {
        PageResult<Product> result = productPort.findPageByScope(context, query);
        List<ProductResponse> items = result.items().stream().map(this::toResponse).toList();
        return PageResult.of(items, result.total(), result.page(), result.size());
    }

    /** Paged query with keyword/status/category filters (V05-WORK-005 frontend search/filter). */
    public PageResult<ProductResponse> pageFiltered(PageQuery query, DataPermissionContext context,
                                                    String keyword, String status, String category) {
        PageResult<Product> result = productPort.findPageByScopeFiltered(context, query, keyword, status, category);
        List<ProductResponse> items = result.items().stream().map(this::toResponse).toList();
        return PageResult.of(items, result.total(), result.page(), result.size());
    }

    // ---- update ----------------------------------------------------------

    public ProductResponse update(Long id, ProductUpdateRequest request, DataPermissionContext context) {
        Product product = productPort.findByIdInScope(id, context)
                .orElseThrow(() -> new PlatformException(ErrorCode.of("PRODUCT_NOT_FOUND",
                        "product not found: " + id)));
        validateCode(request.code());
        validateName(request.name());
        String status = normalizeStatus(request.status());
        String category = normalizeCategory(request.category());
        if (productPort.existsByCode(request.code(), id)) {
            throw new PlatformException(ErrorCode.of("PRODUCT_CODE_DUPLICATE",
                    "product code already exists: " + request.code()));
        }
        product.setCode(request.code());
        product.setName(request.name().trim());
        product.setStatus(status);
        product.setCategory(category);
        product.setUpdatedAt(LocalDateTime.now());
        // createdBy/createdAt/departmentId are immutable (never updated)
        productPort.update(product);
        return toResponse(product);
    }

    // ---- disable ----------------------------------------------------------

    public ProductResponse disable(Long id, DataPermissionContext context) {
        Product product = productPort.findByIdInScope(id, context)
                .orElseThrow(() -> new PlatformException(ErrorCode.of("PRODUCT_NOT_FOUND",
                        "product not found: " + id)));
        product.setStatus("DISABLED");
        product.setUpdatedAt(LocalDateTime.now());
        productPort.update(product);
        return toResponse(product);
    }

    // ---- validation helpers --------------------------------------------------

    private void validateCode(String code) {
        if (code == null || code.isBlank()) {
            throw new PlatformException(ErrorCode.of("PRODUCT_CODE_REQUIRED", "product code is required"));
        }
        if (code.trim().length() > 64) {
            throw new PlatformException(ErrorCode.of("PRODUCT_CODE_INVALID", "product code too long"));
        }
        if (!code.trim().matches("[A-Za-z0-9._-]+")) {
            throw new PlatformException(ErrorCode.of("PRODUCT_CODE_INVALID", "product code format invalid"));
        }
    }

    private void validateName(String name) {
        if (name == null || name.isBlank()) {
            throw new PlatformException(ErrorCode.of("PRODUCT_NAME_REQUIRED", "product name is required"));
        }
        if (name.trim().length() > 128) {
            throw new PlatformException(ErrorCode.of("PRODUCT_NAME_INVALID", "product name too long"));
        }
    }

    /** Status validated against the product_status dictionary when available; falls back to stable set. */
    private String normalizeStatus(String status) {
        if (status == null || status.isBlank()) {
            return "ENABLED";
        }
        String normalized = status.trim().toUpperCase();
        if (!KNOWN_STATUS.contains(normalized)) {
            throw new PlatformException(ErrorCode.of("PRODUCT_STATUS_INVALID",
                    "invalid product status: " + status));
        }
        // consume dictionary: product_status type must expose the value (or be absent)
        dictionaryPort.findTypeByCode("product_status").ifPresent(type -> {
            Set<String> values = dictionaryPort.findItemsByTypeId(type.getId()).stream()
                    .map(DictionaryItem::getValue).collect(java.util.stream.Collectors.toSet());
            if (!values.isEmpty() && !values.contains(normalized)) {
                throw new PlatformException(ErrorCode.of("PRODUCT_STATUS_INVALID",
                        "product status not in dictionary: " + status));
            }
        });
        return normalized;
    }

    private String normalizeCategory(String category) {
        if (category == null || category.isBlank()) {
            return null;
        }
        return category.trim();
    }

    private ProductResponse toResponse(Product product) {
        return ProductResponse.of(
                product.getId(), product.getCode(), product.getName(), product.getStatus(),
                product.getCategory(), product.getDepartmentId(), product.getCreatedBy(),
                product.getCreatedAt(), product.getUpdatedAt());
    }
}
