package ${package}.application.product;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;

import java.time.LocalDateTime;

/**
 * Product response DTO (generated by engineering-platform ${asset.version}).
 * Stable API payload — never exposes the persistence entity or MyBatis types.
 */
public record ProductResponse(
        @JsonSerialize(using = ToStringSerializer.class)
        Long id,
        String code,
        String name,
        String status,
        String category,
        Long departmentId,
        Long createdBy,
        LocalDateTime createdAt,
        LocalDateTime updatedAt) {

    public static ProductResponse of(
            Long id, String code, String name, String status, String category,
            Long departmentId, Long createdBy, LocalDateTime createdAt, LocalDateTime updatedAt) {
        return new ProductResponse(id, code, name, status, category,
                departmentId, createdBy, createdAt, updatedAt);
    }
}
