package ${package}.api.product;

import ${package}.application.datascope.DataPermissionContext;
import ${package}.application.datascope.DataScopeResolver;
import ${package}.application.product.ProductCreateRequest;
import ${package}.application.product.ProductResponse;
import ${package}.application.product.ProductService;
import ${package}.application.product.ProductUpdateRequest;
import ${package}.common.core.ApiResponse;
import ${package}.common.core.PageQuery;
import ${package}.common.core.PageResult;
import ${package}.common.core.PlatformException;
import ${package}.common.core.RequestContext;
import ${package}.common.security.OperationLog;
import ${package}.common.security.RequirePermission;
import ${package}.common.security.SecurityErrorCodes;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * Reference Product CRUD API (generated by engineering-platform ${asset.version}).
 *
 * Validation host consuming the whole V0.4 Enterprise Foundation:
 *   Platform Core (ApiResponse/PageQuery/PageResult/RequestContext)
 *   Authentication (AuthInterceptor fills RequestContext)
 *   RBAC (@RequirePermission)
 *   Organization/Data Permission (DataScopeResolver per request)
 *   Operation Log (@OperationLog on write operations)
 */
@RestController
@RequestMapping("/api/products")
public class ProductController {

    private final ProductService productService;
    private final DataScopeResolver dataScopeResolver;

    public ProductController(ProductService productService, DataScopeResolver dataScopeResolver) {
        this.productService = productService;
        this.dataScopeResolver = dataScopeResolver;
    }

    private Long currentUserId() {
        return Long.valueOf(RequestContext.currentUserId()
                .orElseThrow(() -> new PlatformException(SecurityErrorCodes.UNAUTHENTICATED)));
    }

    private DataPermissionContext scope() {
        return dataScopeResolver.resolve(currentUserId());
    }

    @PostMapping
    @RequirePermission("product:item:create")
    @OperationLog(operation = "PRODUCT_CREATE", resourceType = "PRODUCT")
    public ApiResponse<ProductResponse> create(@RequestBody ProductCreateRequest request) {
        Long userId = currentUserId();
        Long departmentId = RequestContext.currentDepartmentId()
                .map(Long::valueOf).orElse(null);
        return ApiResponse.ofSuccess(productService.create(request, userId, departmentId));
    }

    @GetMapping("/{id}")
    @RequirePermission("product:item:read")
    public ApiResponse<ProductResponse> detail(@PathVariable Long id) {
        return ApiResponse.ofSuccess(productService.get(id, scope()));
    }

    @GetMapping
    @RequirePermission("product:item:read")
    public ApiResponse<PageResult<ProductResponse>> list(
            @RequestParam(defaultValue = "1") int page,
            @RequestParam(defaultValue = "20") int size) {
        return ApiResponse.ofSuccess(productService.page(PageQuery.of(page, size), scope()));
    }

    @PutMapping("/{id}")
    @RequirePermission("product:item:update")
    @OperationLog(operation = "PRODUCT_UPDATE", resourceType = "PRODUCT")
    public ApiResponse<ProductResponse> update(@PathVariable Long id,
                                               @RequestBody ProductUpdateRequest request) {
        return ApiResponse.ofSuccess(productService.update(id, request, scope()));
    }

    @PostMapping("/{id}/disable")
    @RequirePermission("product:item:disable")
    @OperationLog(operation = "PRODUCT_DISABLE", resourceType = "PRODUCT")
    public ApiResponse<ProductResponse> disable(@PathVariable Long id) {
        return ApiResponse.ofSuccess(productService.disable(id, scope()));
    }
}
