package ${package}.domain.entity;

import java.time.LocalDateTime;

/**
 * Reference product entity (generated by engineering-platform ${asset.version}).
 *
 * Validation host for the V0.4 Enterprise Foundation: consumes Platform Core,
 * Authentication, RBAC, Organization, Data Permission, Menu, Dictionary and
 * Operation Log. NOT an ERP product module (no SKU/SPU/pricing/inventory).
 * Pure domain POJO — no persistence annotations (infrastructure owns mapping).
 */
public class Product {

    private Long id;
    private String code;
    private String name;
    private String status;
    private String category;
    private Long departmentId;
    private Long createdBy;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Product() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Long getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }

    public Long getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
