package ${package}.application.product;

/**
 * Product create request (generated by engineering-platform ${asset.version}).
 * Client never supplies createdBy/departmentId — they are derived from the
 * authenticated RequestContext server-side.
 */
public record ProductCreateRequest(String code, String name, String status, String category) {
}
