package ${package}.infrastructure.persistence;

import ${package}.application.dictionary.DictionaryPort;
import ${package}.application.organization.DepartmentPort;
import ${package}.application.product.ProductPort;
import ${package}.application.product.ProductService;
import ${package}.infrastructure.persistence.mapper.ProductMapper;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Product reference bean wiring (generated by engineering-platform ${asset.version}).
 */
@Configuration
public class ProductBeansConfig {

    @Bean
    public ProductPort productPort(ProductMapper productMapper, DepartmentPort departmentPort) {
        return new MybatisProductRepository(productMapper, departmentPort);
    }

    @Bean
    public ProductService productService(ProductPort productPort, DictionaryPort dictionaryPort) {
        return new ProductService(productPort, dictionaryPort);
    }
}
