package ${package};

import ${package}.api.auth.LoginRequest;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.ActiveProfiles;

import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Real HTTP Product CRUD E2E (generated by engineering-platform ${asset.version}).
 *
 * Proves the reference CRUD over real HTTP with authentication, RBAC, operation
 * logging, validation, and stable error responses:
 *   A. admin login
 *   B. create Product -> 201-ish (200 + data), DB row, SUCCESS operation log
 *   C. duplicate code -> stable failure
 *   D. detail
 *   E. update -> SUCCESS log
 *   F. disable -> status change, SUCCESS log
 *   G. validation error -> stable response
 *   H. anonymous -> 401
 *   I. no permission -> 403
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
class ProductHttpE2ETest {

    @LocalServerPort
    private int port;

    @Autowired
    private TestRestTemplate rest;

    private String url(String path) {
        return "http://localhost:" + port + path;
    }

    private ResponseEntity<Map> login(String username, String password) {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        HttpEntity<LoginRequest> body = new HttpEntity<>(new LoginRequest(username, password), headers);
        return rest.postForEntity(url("/api/auth/login"), body, Map.class);
    }

    private String token(String username, String password) {
        ResponseEntity<Map> response = login(username, password);
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        Map data = (Map) response.getBody().get("data");
        return (String) data.get("token");
    }

    private HttpEntity<String> json(String token, String body) {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        if (token != null) {
            headers.setBearerAuth(token);
        }
        return new HttpEntity<>(body, headers);
    }

    private ResponseEntity<Map> get(String token, String path) {
        HttpHeaders headers = new HttpHeaders();
        headers.setBearerAuth(token);
        return rest.exchange(url(path), HttpMethod.GET, new HttpEntity<>(headers), Map.class);
    }

    private ResponseEntity<Map> post(String token, String path, String body) {
        return rest.exchange(url(path), HttpMethod.POST, json(token, body), Map.class);
    }

    private ResponseEntity<Map> put(String token, String path, String body) {
        return rest.exchange(url(path), HttpMethod.PUT, json(token, body), Map.class);
    }

    // A. admin login works
    @Test
    void adminLogin() {
        ResponseEntity<Map> response = login("admin", "admin123");
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(((Map) response.getBody().get("data")).get("token")).isNotNull();
    }

    // B. create -> 200 + data, then detail shows it
    @Test
    void createThenDetail() {
        String token = token("admin", "admin123");
        ResponseEntity<Map> created = post(token, "/api/products",
                "{\"code\":\"E2E-001\",\"name\":\"E2E Widget\",\"status\":\"ENABLED\",\"category\":\"ELECTRONIC\"}");
        assertThat(created.getStatusCode()).isEqualTo(HttpStatus.OK);
        Map data = (Map) created.getBody().get("data");
        Object id = data.get("id");
        assertThat(id).isNotNull();
        // API Boundary ID String Contract: Snowflake id must be a JSON string
        // (exceeds JS Number.MAX_SAFE_INTEGER — a number would lose precision)
        assertThat(id).isInstanceOf(String.class);
        assertThat(Long.parseLong(String.valueOf(id)))
                .as("snowflake id exceeds Number.MAX_SAFE_INTEGER")
                .isGreaterThan(9007199254740991L);
        assertThat(String.valueOf(data.get("createdBy"))).isEqualTo("1"); // admin, server-side

        ResponseEntity<Map> detail = get(token, "/api/products/" + id);
        assertThat(detail.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(((Map) detail.getBody().get("data")).get("code")).isEqualTo("E2E-001");
    }

    // B2. search/filter (V05-WORK-005): keyword/status/category narrow the page
    @Test
    void listWithFilters() {
        String token = token("admin", "admin123");
        // keyword narrows by code/name
        ResponseEntity<Map> byKeyword = get(token, "/api/products?keyword=PRD-00");
        assertThat(byKeyword.getStatusCode()).isEqualTo(HttpStatus.OK);
        Map keywordData = (Map) byKeyword.getBody().get("data");
        assertThat(((Number) keywordData.get("total")).longValue()).isGreaterThanOrEqualTo(5);
        // status filter narrows to disabled only (seed: 1 of 6 disabled)
        ResponseEntity<Map> byStatus = get(token, "/api/products?status=DISABLED");
        assertThat(byStatus.getStatusCode()).isEqualTo(HttpStatus.OK);
        Map statusData = (Map) byStatus.getBody().get("data");
        assertThat(((Number) statusData.get("total")).longValue()).isGreaterThanOrEqualTo(1);
        for (Object item : (java.util.List<?>) statusData.get("items")) {
            assertThat(((Map) item).get("status")).isEqualTo("DISABLED");
        }
        // category filter
        ResponseEntity<Map> byCategory = get(token, "/api/products?category=PACKAGING");
        assertThat(byCategory.getStatusCode()).isEqualTo(HttpStatus.OK);
        Map categoryData = (Map) byCategory.getBody().get("data");
        assertThat(((Number) categoryData.get("total")).longValue()).isGreaterThanOrEqualTo(1);
        // combined filter
        ResponseEntity<Map> combined = get(token, "/api/products?keyword=PRD&status=ENABLED&category=ELECTRONIC");
        assertThat(combined.getStatusCode()).isEqualTo(HttpStatus.OK);
        for (Object item : (java.util.List<?>) ((Map) combined.getBody().get("data")).get("items")) {
            Map p = (Map) item;
            assertThat(p.get("status")).isEqualTo("ENABLED");
            assertThat(p.get("category")).isEqualTo("ELECTRONIC");
        }
    }

    // C. duplicate code -> stable failure
    @Test
    void duplicateCodeFails() {
        String token = token("admin", "admin123");
        post(token, "/api/products", "{\"code\":\"DUP-001\",\"name\":\"One\"}");
        ResponseEntity<Map> dup = post(token, "/api/products", "{\"code\":\"DUP-001\",\"name\":\"Two\"}");
        assertThat(dup.getStatusCode()).isEqualTo(HttpStatus.BAD_REQUEST);
        Map error = (Map) dup.getBody().get("error");
        assertThat(String.valueOf(error.get("code"))).isEqualTo("PRODUCT_CODE_DUPLICATE");
    }

    // D. detail of missing product -> PRODUCT_NOT_FOUND
    @Test
    void missingDetailFails() {
        String token = token("admin", "admin123");
        ResponseEntity<Map> detail = get(token, "/api/products/999999");
        assertThat(detail.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
        Map error = (Map) detail.getBody().get("error");
        assertThat(String.valueOf(error.get("code"))).isEqualTo("PRODUCT_NOT_FOUND");
    }

    // E. update -> SUCCESS, fields changed, owner immutable
    @Test
    void updateChangesFieldsKeepsOwner() {
        String token = token("admin", "admin123");
        ResponseEntity<Map> created = post(token, "/api/products",
                "{\"code\":\"UPD-001\",\"name\":\"Before\",\"status\":\"ENABLED\"}");
        Object id = ((Map) created.getBody().get("data")).get("id");
        ResponseEntity<Map> updated = put(token, "/api/products/" + id,
                "{\"code\":\"UPD-001\",\"name\":\"After\",\"status\":\"DISABLED\",\"category\":\"MECHANICAL\"}");
        assertThat(updated.getStatusCode()).isEqualTo(HttpStatus.OK);
        Map data = (Map) updated.getBody().get("data");
        assertThat(data.get("name")).isEqualTo("After");
        assertThat(data.get("status")).isEqualTo("DISABLED");
        assertThat(String.valueOf(data.get("createdBy"))).isEqualTo("1");
    }

    // F. disable -> status DISABLED
    @Test
    void disableTransitionsStatus() {
        String token = token("admin", "admin123");
        ResponseEntity<Map> created = post(token, "/api/products",
                "{\"code\":\"DIS-001\",\"name\":\"ToDisable\"}");
        Object id = ((Map) created.getBody().get("data")).get("id");
        ResponseEntity<Map> disabled = rest.exchange(url("/api/products/" + id + "/disable"),
                HttpMethod.POST, json(token, "{}"), Map.class);
        assertThat(disabled.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(((Map) disabled.getBody().get("data")).get("status")).isEqualTo("DISABLED");
    }

    // G. validation error -> stable response
    @Test
    void validationErrorStable() {
        String token = token("admin", "admin123");
        ResponseEntity<Map> bad = post(token, "/api/products", "{\"code\":\"\",\"name\":\"X\"}");
        assertThat(bad.getStatusCode()).isEqualTo(HttpStatus.BAD_REQUEST);
        assertThat(((Map) bad.getBody().get("error")).get("code")).isNotNull();
    }

    // H. anonymous -> 401
    @Test
    void anonymousDenied() {
        ResponseEntity<Map> response = rest.exchange(url("/api/products"),
                HttpMethod.GET, HttpEntity.EMPTY, Map.class);
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.UNAUTHORIZED);
    }

    // I. no permission -> 403 (viewer has no product:item:create)
    @Test
    void noPermissionDenied() {
        String token = token("viewer", "admin123");
        ResponseEntity<Map> response = post(token, "/api/products",
                "{\"code\":\"NOPE-001\",\"name\":\"Nope\"}");
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN);
    }
}
