package ${package}.application.product;

/**
 * Product update request (generated by engineering-platform ${asset.version}).
 * createdBy/createdAt/departmentId are immutable — never accepted from client.
 */
public record ProductUpdateRequest(String code, String name, String status, String category) {
}
