package ${package}.application.product;

import ${package}.application.datascope.DataPermissionContext;
import ${package}.common.core.PageQuery;
import ${package}.common.core.PageResult;
import ${package}.domain.entity.Product;

import java.util.List;
import java.util.Optional;

/**
 * Product persistence contract (generated by engineering-platform ${asset.version}).
 *
 * Stable application-level query contract. The implementation lives in the
 * infrastructure layer (MyBatis-Plus); application/business code depends only
 * on this interface — never on MyBatis persistence types.
 */
public interface ProductPort {

    /** Product by id without data-scope filtering (caller enforces scope). */
    Optional<Product> findById(Long id);

    /** Product by id visible under the given data permission context. */
    Optional<Product> findByIdInScope(Long id, DataPermissionContext context);

    /** All products visible under the given data permission context. */
    List<Product> findByScope(DataPermissionContext context);

    /** Paged products visible under the given data permission context. */
    PageResult<Product> findPageByScope(DataPermissionContext context, PageQuery query);

    /** True when a product with the code exists (excluding the given id for update). */
    boolean existsByCode(String code, Long excludeId);

    /** Insert a new product; returns the persisted product (with generated id). */
    Product insert(Product product);

    /** Update a product; returns rows affected. */
    int update(Product product);
}
