-- TEST-ONLY product-reference seed (generated by engineering-platform ${asset.version})
-- Loaded only by the test profile. Extends data-permission seed (departments/users/roles).
-- Filename keeps alphabetical order AFTER seed-zz-menu.sql.

-- Permissions: product CRUD (data-permission seed: 2=product:item:read;
-- menu seed: 3=system:menu:manage)
INSERT INTO sys_permission (id, code, name, created_at, updated_at) VALUES
  (4, 'product:item:create', 'Create products', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (5, 'product:item:update', 'Update products', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (6, 'product:item:disable', 'Disable products', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Role-Permission: admin gets full CRUD; sales-manager gets create+update
-- (partial); finance-user gets disable (partial); sales-user remains read-only;
-- viewer has no product permissions (403)
INSERT INTO sys_role_permission (id, role_id, permission_id, created_at) VALUES
  (8, 1, 4, CURRENT_TIMESTAMP),   -- admin create
  (9, 1, 5, CURRENT_TIMESTAMP),   -- admin update
  (10, 1, 6, CURRENT_TIMESTAMP),  -- admin disable
  (11, 3, 4, CURRENT_TIMESTAMP),  -- sales-manager create
  (12, 3, 5, CURRENT_TIMESTAMP),  -- sales-manager update (partial)
  (13, 5, 6, CURRENT_TIMESTAMP);  -- finance-user disable (partial)

-- Products: reference data spread across departments/creators/status/category
INSERT INTO product (id, code, name, status, category, department_id, created_by, created_at, updated_at) VALUES
  (1, 'PRD-001', 'P-HQ-1', 'ENABLED', 'ELECTRONIC', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (2, 'PRD-002', 'P-SALES-1', 'ENABLED', 'ELECTRONIC', 2, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (3, 'PRD-003', 'P-SALES-2', 'DISABLED', 'MECHANICAL', 2, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (4, 'PRD-004', 'P-SALES-EAST-1', 'ENABLED', 'ELECTRONIC', 3, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (5, 'PRD-005', 'P-FINANCE-1', 'ENABLED', 'PACKAGING', 4, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (6, 'PRD-006', 'P-SELF-1', 'ENABLED', 'ELECTRONIC', 1, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Dictionary: product_status type (dictionary seed: 1=gender 2=order_status 3=retired)
INSERT INTO sys_dictionary_type (id, code, name, enabled, description, created_at, updated_at) VALUES
  (4, 'product_status', 'Product Status', 1, 'Product lifecycle states', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys_dictionary_item (id, type_id, `value`, label, enabled, sort, description, created_at, updated_at) VALUES
  (9, 4, 'ENABLED', 'Enabled', 1, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (10, 4, 'DISABLED', 'Disabled', 1, 2, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_dictionary_type (id, code, name, enabled, description, created_at, updated_at) VALUES
  (5, 'product_category', 'Product category', 1, 'Product categories', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys_dictionary_item (id, type_id, `value`, label, enabled, sort, description, created_at, updated_at) VALUES
  (11, 5, 'ELECTRONIC', 'Electronic', 1, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (12, 5, 'MECHANICAL', 'Mechanical', 1, 2, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (13, 5, 'PACKAGING', 'Packaging', 1, 3, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
