// Supplier routes (generated by engineering-platform frontend-supplier-reference asset)
// Controlled registry aligned with backend menu.path (/suppliers). The router
// (frontend-auth) loads this module via glob when the asset is present.
import type { RouteRecordRaw } from 'vue-router';

export const businessRoutes: RouteRecordRaw[] = [
  {
    path: '/suppliers',
    name: 'suppliers',
    component: () => import('../../views/supplier/SupplierListView.vue'),
    meta: { title: 'Suppliers', permission: 'supplier:item:read' },
  },
  {
    path: '/suppliers/:id',
    name: 'supplier-detail',
    component: () => import('../../views/supplier/SupplierDetailView.vue'),
    meta: { title: 'Supplier Detail', permission: 'supplier:item:read' },
  },
  {
    path: '/suppliers/:id/edit',
    name: 'supplier-edit',
    component: () => import('../../views/supplier/SupplierEditView.vue'),
    meta: { title: 'Edit Supplier', permission: 'supplier:item:update' },
  },
];
