// Permission tests (generated by engineering-platform frontend-permission asset)
import { describe, it, expect, beforeEach } from 'vitest';
import { mount } from '@vue/test-utils';
import { createPinia, setActivePinia, type Pinia } from 'pinia';
import ElementPlus from 'element-plus';
import { useAuthStore } from '../src/stores/auth';
import PermissionButton from '../src/permission/PermissionButton.vue';
import { hasPermission } from '../src/permission';

function seedPermissions(pinia: Pinia, permissions: string[]): void {
  const auth = useAuthStore(pinia);
  auth.$patch({
    currentUser: { id: 1, username: 'u', departmentId: null, permissions },
  });
}

describe('permission UI', () => {
  let pinia: Pinia;

  beforeEach(() => {
    pinia = createPinia();
    setActivePinia(pinia);
    localStorage.clear();
  });

  it('hasPermission true when granted', () => {
    seedPermissions(pinia, ['product:item:create']);
    expect(hasPermission('product:item:create')).toBe(true);
    expect(hasPermission('product:item:update')).toBe(false);
  });

  it('wildcard grants everything', () => {
    seedPermissions(pinia, ['*']);
    expect(hasPermission('anything:at:all')).toBe(true);
  });

  it('PermissionButton renders when permission granted', () => {
    seedPermissions(pinia, ['system:user:read']);
    const wrapper = mount(PermissionButton, {
      props: { permission: 'system:user:read' },
      global: { plugins: [pinia, ElementPlus] },
      slots: { default: 'Manage' },
    });
    expect(wrapper.find('button').exists()).toBe(true);
    expect(wrapper.text()).toContain('Manage');
  });

  it('PermissionButton hidden when permission missing', () => {
    seedPermissions(pinia, ['other:perm']);
    const wrapper = mount(PermissionButton, {
      props: { permission: 'system:user:read' },
      global: { plugins: [pinia, ElementPlus] },
      slots: { default: 'Manage' },
    });
    expect(wrapper.find('button').exists()).toBe(false);
  });
});
