// Product API service (generated by engineering-platform frontend-product-reference asset)
// All HTTP through the Platform Request Client — no raw axios/fetch.
import { http } from './request';
import type { Product, ProductCreateRequest, ProductUpdateRequest, ProductQuery, ProductPageResponse } from '../types/product';

export const productApi = {
  page: (query: ProductQuery = {}) =>
    http.get<ProductPageResponse>('/products' + queryString(query as unknown as Record<string, unknown>)),
  detail: (id: number) => http.get<Product>('/products/' + id),
  create: (body: ProductCreateRequest) => http.post<Product>('/products', body),
  update: (id: number, body: ProductUpdateRequest) => http.put<Product>('/products/' + id, body),
  disable: (id: number) => http.post<Product>('/products/' + id + '/disable', {}),
};

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined && v !== null && v !== '');
  if (entries.length === 0) {
    return '';
  }
  return '?' + entries
    .map(([k, v]) => encodeURIComponent(k) + '=' + encodeURIComponent(String(v)))
    .join('&');
}
