package ${package}.application.organization;

import ${package}.domain.entity.SysDepartment;

import java.util.List;
import java.util.Optional;

/**
 * Department read contract (generated by engineering-platform ${asset.version}).
 * Application/business code depends only on this interface — never on MyBatis types.
 */
public interface DepartmentPort {

    Optional<SysDepartment> findById(Long departmentId);

    List<SysDepartment> findAll();

    /** All descendant department ids (children + grandchildren, recursive). */
    java.util.Set<Long> descendantIds(Long departmentId);
}
