package ${package}.application.organization;

import ${package}.common.core.PlatformException;
import ${package}.domain.entity.SysDepartment;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Department application service (generated by engineering-platform ${asset.version}).
 * Tree building + structural validation (self-parent / cycle prevention).
 */
public class DepartmentService {

    private final DepartmentPort departmentPort;

    public DepartmentService(DepartmentPort departmentPort) {
        this.departmentPort = departmentPort;
    }

    /** Department tree node. */
    public record DepartmentNode(SysDepartment department, List<DepartmentNode> children) {
    }

    /** Stable tree: root-level first, siblings ordered by sort then id; disabled nodes included with flag. */
    public List<DepartmentNode> tree() {
        List<SysDepartment> all = departmentPort.findAll();
        validateStructure(all);
        Map<Long, DepartmentNode> nodes = new LinkedHashMap<>();
        for (SysDepartment d : all) {
            nodes.put(d.getId(), new DepartmentNode(d, new ArrayList<>()));
        }
        List<DepartmentNode> roots = new ArrayList<>();
        for (SysDepartment d : all) {
            DepartmentNode node = nodes.get(d.getId());
            if (d.getParentId() == null || !nodes.containsKey(d.getParentId())) {
                roots.add(node);
            } else {
                nodes.get(d.getParentId()).children().add(node);
            }
        }
        return roots;
    }

    /** Rejects self-parent and any cycle reachable from the given node. */
    public void validateStructure(List<SysDepartment> all) {
        for (SysDepartment d : all) {
            if (d.getParentId() != null && d.getParentId().equals(d.getId())) {
                throw new PlatformException(
                        ${package}.common.core.ErrorCode.of("DEPARTMENT_SELF_PARENT",
                                "department cannot be its own parent: " + d.getCode()));
            }
        }
        for (SysDepartment d : all) {
            if (d.getParentId() == null) {
                continue;
            }
            java.util.Set<Long> seen = new java.util.HashSet<>();
            Long cursor = d.getParentId();
            while (cursor != null && seen.add(cursor)) {
                if (cursor.equals(d.getId())) {
                    throw new PlatformException(
                            ${package}.common.core.ErrorCode.of("DEPARTMENT_CYCLE",
                                    "department cycle detected at: " + d.getCode()));
                }
                Long next = null;
                for (SysDepartment x : all) {
                    if (x.getId().equals(cursor)) {
                        next = x.getParentId();
                        break;
                    }
                }
                cursor = next;
            }
        }
    }

    /** All descendant ids of a department (application-level tree computation). */
    public java.util.Set<Long> descendantIds(Long departmentId) {
        return departmentPort.descendantIds(departmentId);
    }
}
