package ${package}.api.organization;

import ${package}.application.organization.DepartmentService;
import ${package}.common.core.ApiResponse;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * Department API (generated by engineering-platform ${asset.version}).
 */
@RestController
@RequestMapping("/api/departments")
public class DepartmentController {

    private final DepartmentService departmentService;

    public DepartmentController(DepartmentService departmentService) {
        this.departmentService = departmentService;
    }

    @GetMapping("/tree")
    public ApiResponse<List<DepartmentService.DepartmentNode>> tree() {
        return ApiResponse.ofSuccess(departmentService.tree());
    }
}
