package ${package}.api.organization;

import ${package}.application.organization.DepartmentManagementService;
import ${package}.application.organization.DepartmentService;
import ${package}.common.core.ApiResponse;
import ${package}.common.security.OperationLog;
import ${package}.common.security.RequirePermission;
import ${package}.domain.entity.SysDepartment;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;
import java.util.Map;

/**
 * Department management API (generated by engineering-platform ${asset.version}).
 */
@RestController
@RequestMapping("/api/departments")
public class DepartmentManagementController {

    private final DepartmentManagementService managementService;
    private final DepartmentService departmentService;

    public DepartmentManagementController(DepartmentManagementService managementService,
                                          DepartmentService departmentService) {
        this.managementService = managementService;
        this.departmentService = departmentService;
    }

    @GetMapping("/tree")
    @RequirePermission("system:department:read")
    public ApiResponse<List<DepartmentService.DepartmentNode>> tree() {
        return ApiResponse.ofSuccess(departmentService.tree());
    }

    @GetMapping("/{id}")
    @RequirePermission("system:department:read")
    public ApiResponse<SysDepartment> detail(@PathVariable Long id) {
        return ApiResponse.ofSuccess(managementService.detail(id));
    }

    @PostMapping
    @RequirePermission("system:department:create")
    @OperationLog(operation = "DEPARTMENT_CREATE", resourceType = "DEPARTMENT")
    public ApiResponse<SysDepartment> create(@RequestBody Map<String, Object> body) {
        return ApiResponse.ofSuccess(managementService.create(
                str(body.get("code")), str(body.get("name")),
                longOrNull(body.get("parentId")), intOrNull(body.get("sort"))));
    }

    @PutMapping("/{id}")
    @RequirePermission("system:department:update")
    @OperationLog(operation = "DEPARTMENT_UPDATE", resourceType = "DEPARTMENT")
    public ApiResponse<SysDepartment> update(@PathVariable Long id,
                                             @RequestBody Map<String, Object> body) {
        return ApiResponse.ofSuccess(managementService.update(id,
                str(body.get("name")), longOrNull(body.get("parentId")), intOrNull(body.get("sort"))));
    }

    @PostMapping("/{id}/enable")
    @RequirePermission("system:department:update")
    @OperationLog(operation = "DEPARTMENT_ENABLE", resourceType = "DEPARTMENT")
    public ApiResponse<SysDepartment> enable(@PathVariable Long id) {
        return ApiResponse.ofSuccess(managementService.setEnabled(id, true));
    }

    @PostMapping("/{id}/disable")
    @RequirePermission("system:department:disable")
    @OperationLog(operation = "DEPARTMENT_DISABLE", resourceType = "DEPARTMENT")
    public ApiResponse<SysDepartment> disable(@PathVariable Long id) {
        return ApiResponse.ofSuccess(managementService.setEnabled(id, false));
    }

    private static String str(Object o) {
        return o == null ? null : String.valueOf(o);
    }

    private static Long longOrNull(Object o) {
        if (o == null) {
            return null;
        }
        return o instanceof Number n ? n.longValue() : Long.valueOf(String.valueOf(o));
    }

    private static Integer intOrNull(Object o) {
        if (o == null) {
            return null;
        }
        return o instanceof Number n ? n.intValue() : Integer.valueOf(String.valueOf(o));
    }
}
