package ${package}.infrastructure.persistence;

import ${package}.application.organization.DepartmentManagementPort;
import ${package}.domain.entity.SysDepartment;
import ${package}.infrastructure.persistence.mapper.SysDepartmentMapper;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;

import java.util.List;
import java.util.Optional;

/**
 * MyBatis-Plus implementation of {@link DepartmentManagementPort} (generated by engineering-platform ${asset.version}).
 *
 * All MyBatis-Plus technical types (QueryWrapper / BaseMapper) stay confined
 * here, in the infrastructure layer.
 */
public class MybatisDepartmentManagementRepository implements DepartmentManagementPort {

    private final SysDepartmentMapper departmentMapper;

    public MybatisDepartmentManagementRepository(SysDepartmentMapper departmentMapper) {
        this.departmentMapper = departmentMapper;
    }

    @Override
    public Optional<SysDepartment> findById(Long departmentId) {
        return Optional.ofNullable(departmentMapper.selectById(departmentId));
    }

    @Override
    public List<SysDepartment> findAll() {
        return departmentMapper.selectList(
                new QueryWrapper<SysDepartment>().orderByAsc("sort", "id"));
    }

    @Override
    public boolean codeExists(String code) {
        return departmentMapper.selectCount(new QueryWrapper<SysDepartment>()
                .eq("code", code)) > 0;
    }

    @Override
    public void insert(SysDepartment department) {
        departmentMapper.insert(department);
    }

    @Override
    public void update(SysDepartment department) {
        departmentMapper.updateById(department);
    }
}
