package ${package}.infrastructure.persistence;

import ${package}.application.organization.DepartmentManagementPort;
import ${package}.application.organization.DepartmentManagementService;
import ${package}.application.organization.DepartmentPort;
import ${package}.application.organization.DepartmentService;
import ${package}.infrastructure.persistence.mapper.SysDepartmentMapper;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Organization bean wiring (generated by engineering-platform ${asset.version}).
 * MyBatis implementations are wired as the stable application contracts
 * (DepartmentPort / DepartmentManagementPort); application services depend only
 * on those contracts.
 */
@Configuration
public class OrganizationBeansConfig {

    @Bean
    public DepartmentPort departmentPort(SysDepartmentMapper departmentMapper) {
        return new MybatisDepartmentRepository(departmentMapper);
    }

    @Bean
    public DepartmentService departmentService(DepartmentPort departmentPort) {
        return new DepartmentService(departmentPort);
    }

    @Bean
    public DepartmentManagementPort departmentManagementPort(SysDepartmentMapper departmentMapper) {
        return new MybatisDepartmentManagementRepository(departmentMapper);
    }

    @Bean
    public DepartmentManagementService departmentManagementService(
            DepartmentManagementPort departmentManagementPort, DepartmentService departmentService) {
        return new DepartmentManagementService(departmentManagementPort, departmentService);
    }
}
