package ${package}.infrastructure.persistence;

import ${package}.application.organization.DepartmentPort;
import ${package}.application.organization.DepartmentService;
import ${package}.infrastructure.persistence.mapper.SysDepartmentMapper;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Organization bean wiring (generated by engineering-platform ${asset.version}).
 */
@Configuration
public class OrganizationBeansConfig {

    @Bean
    public DepartmentPort departmentPort(SysDepartmentMapper departmentMapper) {
        return new MybatisDepartmentRepository(departmentMapper);
    }

    @Bean
    public DepartmentService departmentService(DepartmentPort departmentPort) {
        return new DepartmentService(departmentPort);
    }
}
