package ${package}.infrastructure.persistence.mapper;

import ${package}.domain.entity.SysDepartment;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;

/**
 * MyBatis-Plus mapper for SysDepartment (generated by engineering-platform ${asset.version}).
 * Persistence implementation only — never leaks into business/API layers.
 */
@Mapper
public interface SysDepartmentMapper extends BaseMapper<SysDepartment> {
}
