package ${package}.infrastructure.persistence;

import ${package}.application.datascope.DataScopeResolver;
import ${package}.application.rbac.UserQueryPort;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Data permission bean wiring (generated by engineering-platform ${asset.version}).
 * V0.4 WORK-005: Product validation host moved to product-reference asset;
 * this config only wires the DataScopeResolver core.
 */
@Configuration
public class DataPermissionBeansConfig {

    @Bean
    public DataScopeResolver dataScopeResolver(UserQueryPort userQueryPort) {
        return new DataScopeResolver(userQueryPort);
    }
}
