package ${package}.application.datascope;

import ${package}.common.security.DataScope;

/**
 * Resolved data permission context (generated by engineering-platform ${asset.version}).
 * Produced by DataScopeResolver; consumed by repository-level enforcement.
 */
public record DataPermissionContext(
        Long userId,
        Long departmentId,
        DataScope scope) {

    public static DataPermissionContext of(Long userId, Long departmentId, DataScope scope) {
        return new DataPermissionContext(userId, departmentId, scope);
    }
}
