package ${package}.infrastructure.persistence;

import ${package}.application.datascope.DataScopeResolver;
import ${package}.application.datascope.ProductPort;
import ${package}.application.organization.DepartmentPort;
import ${package}.application.rbac.UserQueryPort;
import ${package}.infrastructure.persistence.mapper.ProductMapper;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Data permission bean wiring (generated by engineering-platform ${asset.version}).
 */
@Configuration
public class DataPermissionBeansConfig {

    @Bean
    public DataScopeResolver dataScopeResolver(UserQueryPort userQueryPort) {
        return new DataScopeResolver(userQueryPort);
    }

    @Bean
    public ProductPort productPort(ProductMapper productMapper, DepartmentPort departmentPort) {
        return new MybatisProductRepository(productMapper, departmentPort);
    }
}
