package ${package}.application.datascope;

import ${package}.application.rbac.UserQueryPort;
import ${package}.common.security.DataScope;

import java.util.Optional;
import java.util.Set;

/**
 * Data scope resolver (generated by engineering-platform ${asset.version}).
 *
 * Resolves the effective {@link DataScope} for the current user from their
 * enabled roles. Deterministic multi-role merge rule (contract):
 *
 *   ALL > DEPARTMENT_AND_CHILDREN > DEPARTMENT > SELF
 *
 * Fail-safe: when no role defines a scope, the narrowest scope (SELF) is used;
 * missing department with a department-dependent scope resolves to an empty
 * (deny-all) context — never upgraded to ALL.
 */
public class DataScopeResolver {

    private final UserQueryPort userQueryPort;

    public DataScopeResolver(UserQueryPort userQueryPort) {
        this.userQueryPort = userQueryPort;
    }

    /** Effective scope for a user (deterministic merge). */
    public DataScope effectiveScope(Long userId) {
        Set<String> scopes = userQueryPort.dataScopesOf(userId);
        DataScope merged = null;
        for (String raw : scopes) {
            DataScope scope = DataScope.fromCode(raw);
            if (scope == null) {
                continue;
            }
            merged = merge(merged, scope);
        }
        // fail-safe: no role data scope -> narrowest (SELF)
        return merged == null ? DataScope.SELF : merged;
    }

    /** Resolve full context for a user; department-dependent scopes without a department deny. */
    public DataPermissionContext resolve(Long userId) {
        DataScope scope = effectiveScope(userId);
        Optional<Long> departmentId = userQueryPort.departmentIdOf(userId);
        if (scope == DataScope.DEPARTMENT || scope == DataScope.DEPARTMENT_AND_CHILDREN) {
            // missing department -> deny-all (empty context); never ALL
            if (departmentId.isEmpty()) {
                return DataPermissionContext.of(userId, null, DataScope.SELF);
            }
            return DataPermissionContext.of(userId, departmentId.get(), scope);
        }
        return DataPermissionContext.of(userId, departmentId.orElse(null), scope);
    }

    /** Merge rule: ALL > DEPARTMENT_AND_CHILDREN > DEPARTMENT > SELF. */
    public static DataScope merge(DataScope current, DataScope next) {
        if (current == null) {
            return next;
        }
        if (current == DataScope.ALL || next == DataScope.ALL) {
            return DataScope.ALL;
        }
        if (current == DataScope.DEPARTMENT_AND_CHILDREN || next == DataScope.DEPARTMENT_AND_CHILDREN) {
            return DataScope.DEPARTMENT_AND_CHILDREN;
        }
        if (current == DataScope.DEPARTMENT || next == DataScope.DEPARTMENT) {
            return DataScope.DEPARTMENT;
        }
        return DataScope.SELF;
    }
}
