package ${package}.infrastructure.persistence;

import ${package}.application.datascope.DataPermissionContext;
import ${package}.application.datascope.ProductPort;
import ${package}.application.organization.DepartmentPort;
import ${package}.common.security.DataScope;
import ${package}.domain.entity.Product;
import ${package}.infrastructure.persistence.mapper.ProductMapper;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;

import java.util.List;
import java.util.Set;

/**
 * MyBatis-Plus implementation of {@link ProductPort} with real data-permission
 * enforcement (generated by engineering-platform ${asset.version}).
 *
 * Data scope enforcement happens HERE, at the query boundary:
 *   ALL                    → no restriction
 *   DEPARTMENT             → department_id = context.departmentId
 *   DEPARTMENT_AND_CHILDREN→ department_id IN (department + descendants)
 *   SELF                   → created_by = current user
 *
 * Fail-safe: missing department with a department-dependent scope denies (empty),
 * never upgrades to ALL. All MyBatis types stay confined to infrastructure.
 */
public class MybatisProductRepository implements ProductPort {

    private final ProductMapper productMapper;
    private final DepartmentPort departmentPort;

    public MybatisProductRepository(ProductMapper productMapper, DepartmentPort departmentPort) {
        this.productMapper = productMapper;
        this.departmentPort = departmentPort;
    }

    @Override
    public List<Product> findByScope(DataPermissionContext context) {
        QueryWrapper<Product> wrapper = new QueryWrapper<>();
        DataScope scope = context.scope() == null ? DataScope.SELF : context.scope();
        switch (scope) {
            case ALL -> {
                // no restriction
            }
            case DEPARTMENT -> {
                if (context.departmentId() == null) {
                    return List.of(); // fail-safe deny
                }
                wrapper.eq("department_id", context.departmentId());
            }
            case DEPARTMENT_AND_CHILDREN -> {
                if (context.departmentId() == null) {
                    return List.of(); // fail-safe deny
                }
                Set<Long> ids = departmentPort.descendantIds(context.departmentId());
                ids.add(context.departmentId());
                wrapper.in("department_id", ids);
            }
            case SELF -> {
                if (context.userId() == null) {
                    return List.of(); // fail-safe deny
                }
                wrapper.eq("created_by", String.valueOf(context.userId()));
            }
        }
        wrapper.orderByAsc("id");
        return productMapper.selectList(wrapper);
    }
}
