package ${package};

import ${package}.application.datascope.DataPermissionContext;
import ${package}.application.datascope.DataScopeResolver;
import ${package}.application.organization.DepartmentService;
import ${package}.common.security.DataScope;
import ${package}.common.core.PlatformException;
import ${package}.domain.entity.SysDepartment;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Organization + data-permission unit tests (generated by engineering-platform ${asset.version}).
 * Run inside the real generated application (test profile seed data).
 * RANDOM_PORT so this class shares one Spring context with the HTTP E2E tests
 * (single H2 in-memory init; avoids duplicate ALTER migration on a second context).
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
class OrgModelUnitTest {

    @Autowired
    private DepartmentService departmentService;

    @Autowired
    private DataScopeResolver dataScopeResolver;

    // 7. Department tree: stable ordering, parent/children correct
    @Test
    void departmentTreeIsStable() {
        List<DepartmentService.DepartmentNode> roots = departmentService.tree();
        assertThat(roots).hasSize(1);
        DepartmentService.DepartmentNode hq = roots.get(0);
        assertThat(hq.department().getCode()).isEqualTo("HQ");
        List<DepartmentService.DepartmentNode> children = hq.children();
        assertThat(children).hasSize(3); // Sales, Finance, Disabled-Dept (stable sort)
        assertThat(children.get(0).department().getCode()).isEqualTo("SALES");
        assertThat(children.get(1).department().getCode()).isEqualTo("FINANCE");
    }

    // 8. self-parent reject
    @Test
    void selfParentIsRejected() {
        SysDepartment bad = new SysDepartment();
        bad.setId(99L);
        bad.setParentId(99L);
        bad.setCode("SELF");
        assertThatThrownBy(() -> departmentService.validateStructure(List.of(bad)))
                .isInstanceOf(PlatformException.class)
                .satisfies(ex -> assertThat(((PlatformException) ex).errorCode().code())
                        .isEqualTo("DEPARTMENT_SELF_PARENT"));
    }

    // 9. cycle reject (A->B->A)
    @Test
    void cycleIsRejected() {
        SysDepartment a = new SysDepartment();
        a.setId(1L);
        a.setParentId(2L);
        a.setCode("A");
        SysDepartment b = new SysDepartment();
        b.setId(2L);
        b.setParentId(1L);
        b.setCode("B");
        assertThatThrownBy(() -> departmentService.validateStructure(List.of(a, b)))
                .isInstanceOf(PlatformException.class)
                .satisfies(ex -> assertThat(((PlatformException) ex).errorCode().code())
                        .isEqualTo("DEPARTMENT_CYCLE"));
    }

    // 10. user department relation: admin@HQ(1), sales-manager@Sales(2)
    @Test
    void userDepartmentRelationExists() {
        assertThat(departmentService.descendantIds(2L)).containsExactly(3L); // Sales -> Sales-East
    }

    // 12. multiple-role deterministic merge: ALL > DEPARTMENT_AND_CHILDREN > DEPARTMENT > SELF
    @Test
    void multiRoleMergeRuleIsDeterministic() {
        assertThat(DataScopeResolver.merge(DataScope.SELF, DataScope.DEPARTMENT)).isEqualTo(DataScope.DEPARTMENT);
        assertThat(DataScopeResolver.merge(DataScope.DEPARTMENT, DataScope.DEPARTMENT_AND_CHILDREN))
                .isEqualTo(DataScope.DEPARTMENT_AND_CHILDREN);
        assertThat(DataScopeResolver.merge(DataScope.DEPARTMENT_AND_CHILDREN, DataScope.ALL))
                .isEqualTo(DataScope.ALL);
        assertThat(DataScopeResolver.merge(DataScope.ALL, DataScope.SELF)).isEqualTo(DataScope.ALL);
    }

    // admin has roles admin(ALL) + sales-manager(DEPARTMENT_AND_CHILDREN) -> ALL wins
    @Test
    void adminEffectiveScopeIsAll() {
        assertThat(dataScopeResolver.effectiveScope(1L)).isEqualTo(DataScope.ALL);
    }

    // 19. missing context fail-safe: user without department never upgrades to ALL
    @Test
    void missingContextIsFailSafe() {
        // viewer(2) has SELF scope; SELF does not require a department
        DataPermissionContext viewerCtx = dataScopeResolver.resolve(2L);
        assertThat(viewerCtx.scope()).isEqualTo(DataScope.SELF);
        // sales-user(5) DEPARTMENT requires department; assigned dept=2 (Sales)
        DataPermissionContext salesCtx = dataScopeResolver.resolve(5L);
        assertThat(salesCtx.scope()).isEqualTo(DataScope.DEPARTMENT);
        assertThat(salesCtx.departmentId()).isEqualTo(2L);
    }
}
