package ${package}.api.product;

import ${package}.application.datascope.DataPermissionContext;
import ${package}.application.datascope.DataScopeResolver;
import ${package}.application.datascope.ProductPort;
import ${package}.common.core.ApiResponse;
import ${package}.common.core.PlatformException;
import ${package}.common.core.RequestContext;
import ${package}.common.security.RequirePermission;
import ${package}.common.security.SecurityErrorCodes;
import ${package}.domain.entity.Product;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * Reference product API with data-permission enforcement (generated by engineering-platform ${asset.version}).
 * RBAC (can you access) and DataScope (what data you see) are separate concerns.
 */
@RestController
@RequestMapping("/api/products")
public class ProductController {

    private final DataScopeResolver dataScopeResolver;
    private final ProductPort productPort;

    public ProductController(DataScopeResolver dataScopeResolver, ProductPort productPort) {
        this.dataScopeResolver = dataScopeResolver;
        this.productPort = productPort;
    }

    @GetMapping
    @RequirePermission("product:item:read")
    public ApiResponse<List<Product>> list() {
        String currentUserId = RequestContext.currentUserId()
                .orElseThrow(() -> new PlatformException(SecurityErrorCodes.UNAUTHENTICATED));
        Long userId = Long.valueOf(currentUserId);
        DataPermissionContext context = dataScopeResolver.resolve(userId);
        return ApiResponse.ofSuccess(productPort.findByScope(context));
    }
}
