package ${package}.application.datascope;

import ${package}.domain.entity.Product;

import java.util.List;

/**
 * Product read contract with data-permission enforcement (generated by engineering-platform ${asset.version}).
 * Application/business code depends only on this interface — never on MyBatis types.
 */
public interface ProductPort {

    /** List products visible under the resolved data scope. */
    List<Product> findByScope(DataPermissionContext context);
}
