-- TEST-ONLY data-permission seed (generated by engineering-platform ${asset.version})
-- Loaded only by the test profile. Extends rbac seed (users/roles/permissions).
-- Product rows live in product-reference asset seed (seed-zz-product.sql).

-- Departments: HQ(1) -> Sales(2) -> Sales-East(3); Finance(4) sibling of Sales
INSERT INTO sys_department (id, parent_id, code, name, enabled, sort, created_at, updated_at) VALUES
  (1, NULL, 'HQ', 'HQ', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (2, 1, 'SALES', 'Sales', 1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (3, 2, 'SALES_EAST', 'Sales-East', 1, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (4, 1, 'FINANCE', 'Finance', 1, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (5, 1, 'DISABLED', 'Disabled-Dept', 0, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Users: extend rbac seed users with department_id
-- rbac seed: 1=admin 2=viewer 3=disabled
UPDATE sys_user SET department_id = 1 WHERE id = 1;   -- admin @ HQ
UPDATE sys_user SET department_id = 1 WHERE id = 2;   -- viewer @ HQ
UPDATE sys_user SET department_id = 2 WHERE id = 3;   -- disabled @ Sales
INSERT INTO sys_user (id, username, password_hash, enabled, department_id, created_at, updated_at) VALUES
  (4, 'sales-manager', '$2b$10$YscrnLtO0WilTpA3rUY/Q.mhtMvDEAsqNHiI8Xm6/yV.ng8SQ26sm', 1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (5, 'sales-user', '$2b$10$YscrnLtO0WilTpA3rUY/Q.mhtMvDEAsqNHiI8Xm6/yV.ng8SQ26sm', 1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (6, 'finance-user', '$2b$10$YscrnLtO0WilTpA3rUY/Q.mhtMvDEAsqNHiI8Xm6/yV.ng8SQ26sm', 1, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (7, 'self-user', '$2b$10$YscrnLtO0WilTpA3rUY/Q.mhtMvDEAsqNHiI8Xm6/yV.ng8SQ26sm', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Roles: add data_scope (rbac seed: 1=admin 2=viewer)
UPDATE sys_role SET data_scope = 'ALL' WHERE id = 1;
UPDATE sys_role SET data_scope = 'SELF' WHERE id = 2;
INSERT INTO sys_role (id, code, name, enabled, data_scope, created_at, updated_at) VALUES
  (3, 'sales-manager', 'Sales Manager', 1, 'DEPARTMENT_AND_CHILDREN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (4, 'sales-user', 'Sales User', 1, 'DEPARTMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (5, 'finance-user', 'Finance User', 1, 'DEPARTMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (6, 'self', 'Self Only', 1, 'SELF', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Permissions: add product:item:read (rbac seed: 1=system:user:read)
INSERT INTO sys_permission (id, code, name, created_at, updated_at) VALUES
  (2, 'product:item:read', 'Read products', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- User-Role: extend (rbac seed: 1=admin->1, 2=viewer->2, 3=disabled->2)
INSERT INTO sys_user_role (id, user_id, role_id, created_at) VALUES
  (4, 1, 3, CURRENT_TIMESTAMP),   -- admin also sales-manager role (multi-role merge test)
  (5, 4, 3, CURRENT_TIMESTAMP),   -- sales-manager
  (6, 5, 4, CURRENT_TIMESTAMP),   -- sales-user
  (7, 6, 5, CURRENT_TIMESTAMP),   -- finance-user
  (8, 7, 6, CURRENT_TIMESTAMP);   -- self-user

-- Role-Permission: grant product read (rbac seed: 1=admin->system:user:read)
INSERT INTO sys_role_permission (id, role_id, permission_id, created_at) VALUES
  (2, 1, 2, CURRENT_TIMESTAMP),   -- admin can read products
  (3, 3, 2, CURRENT_TIMESTAMP),   -- sales-manager can read products
  (4, 4, 2, CURRENT_TIMESTAMP),   -- sales-user can read products
  (5, 5, 2, CURRENT_TIMESTAMP),   -- finance-user can read products
  (6, 6, 2, CURRENT_TIMESTAMP);   -- self can read products
