-- Data permission schema (generated by engineering-platform ${asset.version})
-- V004: sys_role.data_scope + reference product table
-- MySQL-compatible baseline (H2 MODE=MySQL for tests).

ALTER TABLE sys_role ADD COLUMN data_scope VARCHAR(32) NULL;

CREATE TABLE IF NOT EXISTS product (
    id            BIGINT       NOT NULL AUTO_INCREMENT,
    name          VARCHAR(128) NOT NULL,
    department_id BIGINT       NULL,
    created_by    VARCHAR(64)  NULL,
    created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_product_department (department_id),
    KEY idx_product_created_by (created_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
