<script setup lang="ts">
// User Management (generated by engineering-platform frontend-enterprise-management asset)
// List + search/filter + create/edit drawer + enable/disable + assign role/department.
// Permission-button driven; backend @RequirePermission is the security boundary.
import { onMounted, reactive, ref } from 'vue';
import { ElMessageBox } from 'element-plus';
import PageHeader from '../../components/PageHeader.vue';
import PageContainer from '../../components/PageContainer.vue';
import SearchForm from '../../components/SearchForm.vue';
import AppTable from '../../components/AppTable.vue';
import StatusTag from '../../components/StatusTag.vue';
import FormDrawer from '../../components/FormDrawer.vue';
import AppForm from '../../components/AppForm.vue';
import PermissionButton from '../../permission/PermissionButton.vue';
import { userApi, roleApi, departmentApi } from '../../api/enterprise';
import type { User, Role, DepartmentNode, UserCreateResult } from '../../types/enterprise';
import { errorMessage, notifySuccess, toastSuccess } from '../../utils/feedback';
import { flattenDepartments } from '../../utils/tree';

const loading = ref(false);
const listError = ref<string | null>(null);
const users = ref<User[]>([]);
const total = ref(0);
const page = ref(1);
const size = ref(20);

const filters = reactive({ username: '', enabled: null as boolean | null, departmentId: null as number | null });

const roles = ref<Role[]>([]);
const departments = ref<DepartmentNode[]>([]);
const deptOptions = ref<{ id: number; name: string }[]>([]);

// drawer state
const drawerOpen = ref(false);
const editing = ref<User | null>(null);
const submitting = ref(false);
const formError = ref<string | null>(null);
const createResult = ref<UserCreateResult | null>(null);
const form = reactive({
  username: '',
  initialPassword: '',
  departmentId: null as number | null,
  roleIds: [] as number[],
});

async function loadUsers(): Promise<void> {
  loading.value = true;
  listError.value = null;
  try {
    const result = await userApi.page({
      page: page.value,
      size: size.value,
      username: filters.username || undefined,
      enabled: filters.enabled ?? undefined,
      departmentId: filters.departmentId ?? undefined,
    });
    users.value = result.items;
    total.value = result.total;
  } catch (e) {
    listError.value = errorMessage(e);
  } finally {
    loading.value = false;
  }
}

async function loadOptions(): Promise<void> {
  const [roleResult, deptTree] = await Promise.all([roleApi.page({ page: 1, size: 100 }), departmentApi.tree()]);
  roles.value = roleResult.items;
  departments.value = deptTree;
  deptOptions.value = flattenDepartments(deptTree).map((d) => ({ id: d.id, name: d.name }));
}

function deptName(id: number | null): string {
  if (id == null) {
    return '—';
  }
  return deptOptions.value.find((d) => d.id === id)?.name ?? '—';
}

function resetFilters(): void {
  filters.username = '';
  filters.enabled = null;
  filters.departmentId = null;
  page.value = 1;
  loadUsers();
}

function openCreate(): void {
  editing.value = null;
  createResult.value = null;
  formError.value = null;
  Object.assign(form, { username: '', initialPassword: '', departmentId: null, roleIds: [] });
  drawerOpen.value = true;
}

function openEdit(user: User): void {
  editing.value = user;
  createResult.value = null;
  formError.value = null;
  Object.assign(form, {
    username: user.username,
    initialPassword: '',
    departmentId: user.departmentId,
    roleIds: [...user.roleIds],
  });
  drawerOpen.value = true;
}

async function submitForm(): Promise<void> {
  submitting.value = true;
  formError.value = null;
  try {
    if (editing.value) {
      await userApi.update(editing.value.id, {
        username: form.username || undefined,
        departmentId: form.departmentId,
        roleIds: form.roleIds,
      });
      notifySuccess('User updated');
    } else {
      const result = await userApi.create({
        username: form.username,
        initialPassword: form.initialPassword || undefined,
        departmentId: form.departmentId,
        roleIds: form.roleIds,
      });
      createResult.value = result;
      notifySuccess('User created', 'The initial password is shown once below.');
    }
    drawerOpen.value = false;
    await loadUsers();
  } catch (e) {
    formError.value = errorMessage(e);
  } finally {
    submitting.value = false;
  }
}

async function setEnabled(user: User, enabled: boolean): Promise<void> {
  if (!enabled) {
    try {
      await ElMessageBox.confirm(
        'Disable user "' + (user.username) + '"? They will no longer be able to sign in.',
        'Disable user',
        { type: 'warning', confirmButtonText: 'Disable', cancelButtonText: 'Cancel' },
      );
    } catch {
      return; // cancelled
    }
  }
  try {
    if (enabled) {
      await userApi.enable(user.id);
      toastSuccess('User enabled');
    } else {
      await userApi.disable(user.id);
      toastSuccess('User disabled');
    }
    await loadUsers();
  } catch (e) {
    toastSuccess(errorMessage(e));
  }
}

async function assignRoles(user: User, roleIds: number[]): Promise<void> {
  try {
    await userApi.assignRoles(user.id, roleIds);
    notifySuccess('Roles updated');
    await loadUsers();
  } catch (e) {
    toastSuccess(errorMessage(e));
  }
}

onMounted(async () => {
  await Promise.all([loadUsers(), loadOptions().catch(() => undefined)]);
});
</script>

<template>
  <PageContainer full-width>
    <PageHeader title="User Management" description="Create, edit, enable/disable users and manage their roles & departments.">
      <template #actions>
        <PermissionButton permission="system:user:create" type="primary" data-testid="create-user" @click="openCreate">
          Create User
        </PermissionButton>
      </template>
    </PageHeader>

    <SearchForm @search="loadUsers" @reset="resetFilters">
      <el-input
        v-model="filters.username"
        placeholder="Search username"
        clearable
        style="width: 220px"
        data-testid="user-search-username"
      />
      <el-select v-model="filters.enabled" placeholder="Status" clearable style="width: 140px" data-testid="user-filter-enabled">
        <el-option label="Enabled" :value="true" />
        <el-option label="Disabled" :value="false" />
      </el-select>
      <el-select v-model="filters.departmentId" placeholder="Department" clearable filterable style="width: 200px" data-testid="user-filter-department">
        <el-option v-for="d in deptOptions" :key="d.id" :label="d.name" :value="d.id" />
      </el-select>
    </SearchForm>

    <AppTable
      :loading="loading"
      :error="listError"
      :data="users"
      :total="total"
      :page="page"
      :size="size"
      @refresh="loadUsers"
      @update:page="(p: number) => { page = p; loadUsers(); }"
      @update:size="(s: number) => { size = s; page = 1; loadUsers(); }"
    >
      <el-table-column prop="username" label="Username" min-width="160" />
      <el-table-column prop="departmentId" label="Department" min-width="140">
        <template #default="{ row }">
          {{ deptName(row.departmentId)?.name ?? '—' }}
        </template>
      </el-table-column>
      <el-table-column label="Roles" min-width="160">
        <template #default="{ row }">
          <el-select
            v-if="roles.length"
            :model-value="row.roleIds"
            multiple
            size="small"
            style="max-width: 220px"
            data-testid="user-role-select"
            @change="(v: number[]) => assignRoles(row, v)"
          >
            <el-option v-for="r in roles" :key="r.id" :label="r.name" :value="r.id" />
          </el-select>
          <span v-else>—</span>
        </template>
      </el-table-column>
      <el-table-column label="Status" width="110">
        <template #default="{ row }">
          <StatusTag :enabled="row.enabled" />
        </template>
      </el-table-column>
      <el-table-column prop="createdAt" label="Created" min-width="170">
        <template #default="{ row }">{{ new Date(row.createdAt).toLocaleString() }}</template>
      </el-table-column>
      <el-table-column label="Actions" width="120" fixed="right">
        <template #default="{ row }">
          <el-dropdown trigger="click" data-testid="user-row-more">
            <el-button size="small" link>More</el-button>
            <template #dropdown>
              <el-dropdown-menu>
                <el-dropdown-item
                  v-if="row.enabled"
                  data-testid="disable-user"
                  @click="setEnabled(row, false)"
                >
                  Disable
                </el-dropdown-item>
                <el-dropdown-item v-else data-testid="enable-user" @click="setEnabled(row, true)">
                  Enable
                </el-dropdown-item>
                <el-dropdown-item @click="openEdit(row)">Edit</el-dropdown-item>
              </el-dropdown-menu>
            </template>
          </el-dropdown>
        </template>
      </el-table-column>
    </AppTable>

    <FormDrawer v-model="drawerOpen" :title="editing ? 'Edit User' : 'Create User'">
      <AppForm
        :model="form as unknown as Record<string, unknown>"
        :submitting="submitting"
        :error="formError"
        :submit-text="editing ? 'Save' : 'Create'"
        compact
        @submit="submitForm"
        @cancel="drawerOpen = false"
      >
        <template #default>
          <el-alert
            v-if="createResult"
            type="success"
            :closable="false"
            data-testid="initial-password-alert"
            :title="'Initial password: ' + (createResult.initialPassword)"
            description="Shown once. The user should change it on first sign-in."
            class="form-alert"
          />
          <el-form-item label="Username" prop="username" :rules="[{ required: true, message: 'Username is required' }]">
            <el-input v-model="form.username" data-testid="user-form-username" />
          </el-form-item>
          <el-form-item v-if="!editing" label="Initial password" prop="initialPassword">
            <el-input
              v-model="form.initialPassword"
              type="password"
              show-password
              placeholder="Leave empty for auto-generated"
              data-testid="user-form-password"
            />
            <div class="form-hint">Shown once. Never displayed again or logged.</div>
          </el-form-item>
          <el-form-item label="Department">
            <el-select v-model="form.departmentId" clearable filterable style="width: 100%" data-testid="user-form-department">
              <el-option v-for="d in deptOptions" :key="d.id" :label="d.name" :value="d.id" />
            </el-select>
          </el-form-item>
          <el-form-item label="Roles">
            <el-select v-model="form.roleIds" multiple style="width: 100%" data-testid="user-form-roles">
              <el-option v-for="r in roles" :key="r.id" :label="r.name" :value="r.id" />
            </el-select>
          </el-form-item>
        </template>
      </AppForm>
    </FormDrawer>
  </PageContainer>
</template>

<style scoped>
.form-alert {
  margin-bottom: var(--ep-space-4);
}
.form-hint {
  font-size: var(--ep-font-size-sm);
  color: var(--ep-color-info);
}
</style>
