// Department Management Browser E2E (generated by engineering-platform playwright-e2e asset)
import { test, expect, loginAs } from './fixtures';

test.describe('department management', () => {
  test.beforeEach(async ({ page }) => {
    await loginAs(page, 'admin', 'admin123');
    // expand System directory (sub-menu children are hidden until open)
    await page.getByText('System').first().click();
    await page.getByRole('menuitem', { name: /Department management/i }).first().click();
    await page.waitForURL(/\/system\/departments/, { timeout: 15_000 });
  });

  test('tree + workspace loads and selects a node', async ({ page }) => {
    await expect(page.getByText('Department Management').first()).toBeVisible({ timeout: 15_000 });
    await expect(page.getByText('HQ').first()).toBeVisible({ timeout: 15_000 });
    // click HQ node -> workspace shows detail
    await page.getByTestId('department-node-1').click();
    await expect(page.getByTestId('department-workspace')).toBeVisible({ timeout: 10_000 });
  });

  test('create child department', async ({ page }) => {
    const code = 'E2E_' + Date.now().toString().slice(-6);
    await page.getByTestId('create-department').click();
    await page.getByTestId('dept-form-code').fill(code);
    await page.getByTestId('dept-form-name').fill('E2E Dept');
    await page.getByTestId('dept-save').click();
    await expect(page.getByText('Department created').first()).toBeVisible({ timeout: 10_000 });
  });

  test('self-parent rejected without breaking page', async ({ page }) => {
    // open HQ, edit, try to set parent = itself (HQ as parent of HQ)
    await page.getByTestId('department-node-1').click();
    await page.getByTestId('edit-department').click();
    // select HQ as parent (same node) — backend must reject DEPARTMENT_SELF_PARENT
    await page.getByTestId('dept-form-parent').click();
    await page.getByRole('option', { name: /HQ/i }).first().click({ force: true, timeout: 8_000 });
    await page.getByTestId('dept-save').click();
    // error feedback, page still functional
    await expect(page.getByTestId('app-form-error').or(page.getByTestId('department-workspace'))).toBeVisible({
      timeout: 10_000,
    });
  });
});
