// Menu Management Browser E2E (generated by engineering-platform playwright-e2e asset)
import { test, expect, loginAs } from './fixtures';

test.describe('menu management', () => {
  test.beforeEach(async ({ page }) => {
    await loginAs(page, 'admin', 'admin123');
    // expand System directory (sub-menu children are hidden until open)
    await page.getByText('System').first().click();
    await page.getByRole('menuitem', { name: /Menu management/i }).first().click();
    await page.waitForURL(/\/system\/menus/, { timeout: 15_000 });
  });

  test('tree loads with type labels', async ({ page }) => {
    await expect(page.getByText('Menu Management').first()).toBeVisible({ timeout: 15_000 });
    await expect(page.getByTestId('menu-tree')).toBeVisible({ timeout: 15_000 });
  });

  test('create menu with permission selector', async ({ page }) => {
    const code = 'e2e-menu-' + Date.now().toString().slice(-6);
    await page.getByTestId('create-menu').click();
    await page.getByTestId('menu-form-code').fill(code);
    await page.getByTestId('menu-form-name').fill('E2E Menu');
    // permission selector: pick system:user:read option
    await page.getByTestId('menu-form-permission').click();
    await page.getByRole('option').first().click({ force: true, timeout: 8_000 });
    await page.getByTestId('menu-save').click();
    await expect(page.getByText('Menu created').first()).toBeVisible({ timeout: 10_000 });
  });
});
