// Role & Permission Workspace Browser E2E (generated by engineering-platform playwright-e2e asset)
import { test, expect, loginAs } from './fixtures';

test.describe('role & permission', () => {
  test.beforeEach(async ({ page }) => {
    await loginAs(page, 'admin', 'admin123');
    // expand System directory (sub-menu children are hidden until open)
    await page.getByText('System').first().click();
    await page.getByRole('menuitem', { name: /Role & Permission/i }).first().click();
    await page.waitForURL(/\/system\/roles/, { timeout: 15_000 });
  });

  test('role list + workspace shows grouped permission matrix and data scope', async ({ page }) => {
    await expect(page.getByText('Role & Permission Management').first()).toBeVisible({ timeout: 15_000 });
    // open admin role workspace
    await page.getByRole('button', { name: /Open/i }).first().click();
    await expect(page.getByTestId('role-workspace')).toBeVisible({ timeout: 10_000 });
    // permission matrix grouped by domain (System)
    await expect(page.getByText('System').first()).toBeVisible({ timeout: 10_000 });
    // data scope human-readable
    await expect(page.getByText(/All data|Own department|Own records|Department & children/i).first())
      .toBeVisible({ timeout: 10_000 });
  });

  test('create role with permission selection persists', async ({ page }) => {
    const code = 'e2e-role-' + Date.now().toString().slice(-6);
    await page.getByTestId('create-role').click();
    await page.getByTestId('role-form-code').fill(code);
    await page.getByTestId('role-form-name').fill('E2E Role');
    // toggle one permission checkbox (system:user:read)
    await page.getByTestId('perm-system:user:read').click().catch(() => undefined);
    await page.getByTestId('role-save').click();
    await expect(page.getByText('Role created').first()).toBeVisible({ timeout: 10_000 });
    // role appears in list
    await expect(page.getByText(code).first()).toBeVisible({ timeout: 10_000 });
  });
});
