# MyBatis-Plus baseline (generated by engineering-platform ${asset.version})
mybatis-plus:
  mapper-locations: ${mybatisPlus.mapperLocations!'classpath*:mapper/**/*.xml'}
  configuration:
    map-underscore-to-camel-case: true
