package ${package}.infrastructure.persistence;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.context.annotation.Configuration;

/**
 * MyBatis-Plus mapper scan baseline (generated by engineering-platform ${asset.version}).
 * Conformance: required file for mybatis-plus provider.
 */
@Configuration
@MapperScan("${package}.infrastructure.persistence.mapper")
public class MapperScanConfig {
}
