// Auth types (generated by engineering-platform frontend-auth asset)

export interface LoginRequest {
  username: string;
  password: string;
}

export interface LoginResponse {
  token: string;
  userId: number;
  username: string;
  expiresAtEpochSeconds: number;
}

export interface CurrentUser {
  id: number;
  username: string;
  departmentId: number | null;
  permissions: string[];
}
