// Supplier types (generated by engineering-platform frontend-supplier-reference asset)
// Stable contract for the reference business module.
// API Boundary ID String Contract: Snowflake IDs cross as strings (EntityId).
import type { PageResult, EntityId } from './enterprise';

export type { PageResult, EntityId };

export interface Supplier {
  id: EntityId;
  code: string;
  name: string;
  status: string; // dictionary value (supplier_status)
  category: string | null; // dictionary value (supplier_category)
  departmentId: EntityId | null;
  createdBy: EntityId | null;
  createdAt: string;
  updatedAt: string;
}

export interface SupplierCreateRequest {
  code: string;
  name: string;
  status: string;
  category: string | null;
}

export interface SupplierUpdateRequest {
  code: string;
  name: string;
  status: string;
  category: string | null;
}

export interface SupplierQuery {
  page?: number;
  size?: number;
  keyword?: string;
  status?: string;
  category?: string;
}

export type SupplierPageResponse = PageResult<Supplier>;
