// Supplier Detail + Edit tests (generated by engineering-platform frontend-supplier-reference asset)
// detail rendering, not-found, error retry, disable flow, edit update.
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { mount, flushPromises } from '@vue/test-utils';
import { createPinia, setActivePinia } from 'pinia';
import { useAuthStore } from '../src/stores/auth';
import { createRouter, createMemoryHistory } from 'vue-router';
import SupplierDetailView from '../src/views/supplier/SupplierDetailView.vue';
import SupplierEditView from '../src/views/supplier/SupplierEditView.vue';
import { supplierApi } from '../src/api/supplier';
import { dictionaryApi } from '../src/api/enterprise';
import type { Supplier } from '../src/types/supplier';
import { epStubs, platformStubs } from './stubs';
import ConfirmAction from '../src/components/ConfirmAction.vue';

const stubs = {
  ...epStubs(),
  ...platformStubs(),
  'el-result': { template: '<div><slot name="extra" /><slot /></div>' },
};

const supplier: Supplier = {
  id: '2', code: 'SUP-002', name: 'P-SALES-1', status: 'DISABLED', category: 'MECHANICAL',
  departmentId: '2', createdBy: '4', createdAt: '2026-08-15T00:00:00', updatedAt: '2026-08-15T00:00:00',
};

function makeRouter(): ReturnType<typeof createRouter> {
  return createRouter({
    history: createMemoryHistory(),
    routes: [
      { path: '/suppliers/:id', component: SupplierDetailView },
      { path: '/suppliers/:id/edit', component: SupplierEditView },
      { path: '/suppliers', component: { template: '<div>list</div>' } },
    ],
  });
}

function seed(permissions: string[]): void {
  const pinia = createPinia();
  setActivePinia(pinia);
  const auth = useAuthStore(pinia);
  auth.$patch({ currentUser: { id: '1', username: 'u', departmentId: null, permissions } });
  localStorage.clear();
}

describe('SupplierDetailView', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  it('renders detail sections from real API (not an edit form)', async () => {
    seed(['supplier:item:read']);
    vi.spyOn(supplierApi, 'detail').mockResolvedValue(supplier);
    const router = makeRouter();
    await router.push('/suppliers/2');
    await router.isReady();
    const wrapper = mount(SupplierDetailView, { global: { plugins: [router], stubs } });
    await flushPromises();
    expect(supplierApi.detail).toHaveBeenCalledWith('2');
    expect(wrapper.find('[data-testid="supplier-detail"]').exists()).toBe(true);
    expect(wrapper.find('[data-testid="detail-code"]').exists()).toBe(true);
  });

  it('shows not-found state for missing/out-of-scope supplier (404)', async () => {
    seed(['supplier:item:read']);
    const err = new Error('not found') as Error & { status: number };
    err.status = 404;
    vi.spyOn(supplierApi, 'detail').mockRejectedValue(err);
    const router = makeRouter();
    await router.push('/suppliers/999');
    await router.isReady();
    const wrapper = mount(SupplierDetailView, { global: { plugins: [router], stubs } });
    await flushPromises();
    expect(wrapper.find('[data-testid="supplier-detail-notfound"]').exists()).toBe(true);
  });

  it('shows error state with retry', async () => {
    seed(['supplier:item:read']);
    vi.spyOn(supplierApi, 'detail').mockRejectedValueOnce(new Error('net')).mockResolvedValueOnce(supplier);
    const router = makeRouter();
    await router.push('/suppliers/2');
    await router.isReady();
    const wrapper = mount(SupplierDetailView, { global: { plugins: [router], stubs } });
    await flushPromises();
    expect(wrapper.find('[data-testid="supplier-detail-error"]').exists()).toBe(true);
    wrapper.find('[data-testid="supplier-detail-retry"]').trigger('click');
    await flushPromises();
    expect(wrapper.find('[data-testid="supplier-detail"]').exists()).toBe(true);
  });

  it('disable action hidden without supplier:item:disable', async () => {
    seed(['supplier:item:read']);
    const enabled: Supplier = { ...supplier, status: 'ENABLED' };
    vi.spyOn(supplierApi, 'detail').mockResolvedValue(enabled);
    const router = makeRouter();
    await router.push('/suppliers/2');
    await router.isReady();
    const wrapper = mount(SupplierDetailView, { global: { plugins: [router], stubs } });
    await flushPromises();
    expect(wrapper.find('[data-testid="supplier-detail-disable"]').exists()).toBe(false);
  });

  it('disable calls API and refreshes', async () => {
    seed(['supplier:item:read', 'supplier:item:disable']);
    const enabled: Supplier = { ...supplier, status: 'ENABLED' };
    vi.spyOn(supplierApi, 'detail').mockResolvedValue(enabled);
    const disableSpy = vi.spyOn(supplierApi, 'disable').mockResolvedValue({ ...supplier, status: 'DISABLED' });
    const router = makeRouter();
    await router.push('/suppliers/2');
    await router.isReady();
    const wrapper = mount(SupplierDetailView, { global: { plugins: [router], stubs } });
    await flushPromises();
    // ConfirmAction (ElPopconfirm) confirm triggers disable directly
    wrapper.findComponent(ConfirmAction).vm.$emit('confirm');
    await flushPromises();
    expect(disableSpy).toHaveBeenCalledWith('2');
  });
});

describe('SupplierEditView', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  it('loads supplier and submits update (ownership untouched)', async () => {
    seed(['supplier:item:read', 'supplier:item:update']);
    vi.spyOn(supplierApi, 'detail').mockResolvedValue(supplier);
    vi.spyOn(dictionaryApi, 'itemsByCode').mockResolvedValue([]);
    const updateSpy = vi.spyOn(supplierApi, 'update').mockResolvedValue(supplier);
    const router = makeRouter();
    await router.push('/suppliers/2/edit');
    await router.isReady();
    const wrapper = mount(SupplierEditView, { global: { plugins: [router], stubs } });
    await flushPromises();
    expect(wrapper.find('[data-testid="supplier-edit"]').exists()).toBe(true);
    // fire AppForm submit
    const AppForm = (await import('../src/components/AppForm.vue')).default;
    wrapper.findComponent(AppForm).vm.$emit('submit');
    await flushPromises();
    expect(updateSpy).toHaveBeenCalledWith('2', expect.objectContaining({
      code: 'SUP-002',
      // ownership fields never part of the request body
    }));
    const body = updateSpy.mock.calls[0][1] as unknown as Record<string, unknown>;
    expect(body).not.toHaveProperty('createdBy');
    expect(body).not.toHaveProperty('departmentId');
  });

  it('shows error state when detail load fails', async () => {
    seed(['supplier:item:read', 'supplier:item:update']);
    vi.spyOn(supplierApi, 'detail').mockRejectedValue(new Error('boom'));
    const router = makeRouter();
    await router.push('/suppliers/2/edit');
    await router.isReady();
    const wrapper = mount(SupplierEditView, { global: { plugins: [router], stubs } });
    await flushPromises();
    expect(wrapper.find('[data-testid="supplier-edit-error"]').exists()).toBe(true);
  });
});
