// Supplier route registration + DataScope UI evidence (generated by engineering-platform frontend-supplier-reference asset)
// Route module must be picked up by the frontend-auth router via glob.
import { describe, it, expect } from 'vitest';
import { businessRoutes } from '../src/router/business/supplier';

describe('supplier routes', () => {
  it('registers /suppliers, detail and edit routes with permission meta', () => {
    const paths = businessRoutes.map((r) => r.path);
    expect(paths).toContain('/suppliers');
    expect(paths).toContain('/suppliers/:id');
    expect(paths).toContain('/suppliers/:id/edit');

    const list = businessRoutes.find((r) => r.path === '/suppliers')!;
    expect(list.meta).toMatchObject({ permission: 'supplier:item:read' });
    const edit = businessRoutes.find((r) => r.path === '/suppliers/:id/edit')!;
    expect(edit.meta).toMatchObject({ permission: 'supplier:item:update' });
  });

  it('routes are static imports (no dynamic component from backend path)', () => {
    for (const r of businessRoutes) {
      expect(typeof r.component).toBe('function'); // lazy import fn, not a backend-derived string
    }
  });
});
