<script setup lang="ts">
// V0.5 frontend shell (generated by engineering-platform frontend-shell asset)
// WORK-001: minimal renderable shell marker only — no dashboard/login/menu yet.
</script>

<template>
  <div class="app-shell" data-testid="app-shell">
    <h1>Engineering Platform</h1>
    <p>Frontend shell ready (V0.5 WORK-001).</p>
  </div>
</template>

<style scoped>
.app-shell {
  font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
  padding: 2rem;
}
</style>
