import { createApp } from 'vue';
import { createPinia } from 'pinia';
import ElementPlus from 'element-plus';
import 'element-plus/dist/index.css';
import App from './App.vue';

// V0.5 frontend shell bootstrap (generated by engineering-platform frontend-shell asset)
// WORK-001: minimal mountable shell only — no login/router business routes yet.
const app = createApp(App);
app.use(createPinia());
app.use(ElementPlus);
app.mount('#app');
