package ${package}.application.menu;

import ${package}.common.core.ErrorCode;
import ${package}.common.core.PlatformException;
import ${package}.domain.entity.SysMenu;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.Optional;

/**
 * Menu management application service (generated by engineering-platform ${asset.version}).
 *
 * Orchestration, business validation and transaction boundaries live here, in
 * the application layer. Persistence goes through {@link MenuManagementPort};
 * structural safety (self-parent, cycle, invalid parent, stable ordering)
 * reuses {@link MenuService}. permissionCode, when set, must reference an
 * existing permission (Menu ≠ Authorization). No MyBatis types appear here.
 *
 * create / update / enable / disable.
 */
public class MenuManagementService {

    private final MenuManagementPort managementPort;
    private final MenuService menuService;

    public MenuManagementService(MenuManagementPort managementPort, MenuService menuService) {
        this.managementPort = managementPort;
        this.menuService = menuService;
    }

    public SysMenu detail(Long id) {
        Optional<SysMenu> menu = managementPort.findById(id);
        if (menu.isEmpty()) {
            throw new PlatformException(ErrorCode.of("MENU_NOT_FOUND", "menu not found: " + id));
        }
        return menu.get();
    }

    @Transactional
    public SysMenu create(Long parentId, String code, String name, String type, String path,
                          String permissionCode, Integer sort) {
        validateCode(code);
        if (managementPort.codeExists(code)) {
            throw new PlatformException(ErrorCode.of("MENU_CODE_DUPLICATE",
                    "menu code already exists: " + code));
        }
        validateParent(parentId);
        validatePermissionCode(permissionCode);
        SysMenu menu = new SysMenu();
        menu.setParentId(parentId);
        menu.setCode(code);
        menu.setName(name == null || name.isBlank() ? code : name.trim());
        menu.setType(type == null ? "MENU" : type);
        menu.setPath(path);
        menu.setPermissionCode(permissionCode);
        menu.setEnabled(true);
        menu.setSort(sort == null ? 0 : sort);
        LocalDateTime now = LocalDateTime.now();
        menu.setCreatedAt(now);
        menu.setUpdatedAt(now);
        managementPort.insert(menu);
        // structural safety after insert (catches cycles introduced by parent refs)
        menuService.validateStructure(managementPort.findAll());
        return menu;
    }

    @Transactional
    public SysMenu update(Long id, Long parentId, String name, String path, String permissionCode,
                          Integer sort) {
        SysMenu menu = requireMenu(id);
        if (name != null && !name.isBlank()) {
            menu.setName(name.trim());
        }
        if (parentId != null && !parentId.equals(menu.getParentId())) {
            if (parentId.equals(id)) {
                throw new PlatformException(ErrorCode.of("MENU_SELF_PARENT",
                        "menu cannot be its own parent"));
            }
            if (managementPort.findById(parentId).isEmpty()) {
                throw new PlatformException(ErrorCode.of("MENU_INVALID_PARENT",
                        "parent menu not found: " + parentId));
            }
            menu.setParentId(parentId);
        }
        if (path != null) {
            menu.setPath(path);
        }
        if (permissionCode != null) {
            validatePermissionCode(permissionCode);
            menu.setPermissionCode(permissionCode.isBlank() ? null : permissionCode);
        }
        if (sort != null) {
            menu.setSort(sort);
        }
        menu.setUpdatedAt(LocalDateTime.now());
        managementPort.update(menu);
        menuService.validateStructure(managementPort.findAll());
        return menu;
    }

    @Transactional
    public SysMenu setEnabled(Long id, boolean enabled) {
        SysMenu menu = requireMenu(id);
        menu.setEnabled(enabled);
        menu.setUpdatedAt(LocalDateTime.now());
        managementPort.update(menu);
        return menu;
    }

    private SysMenu requireMenu(Long id) {
        Optional<SysMenu> menu = managementPort.findById(id);
        if (menu.isEmpty()) {
            throw new PlatformException(ErrorCode.of("MENU_NOT_FOUND", "menu not found: " + id));
        }
        return menu.get();
    }

    private void validateCode(String code) {
        if (code == null || code.isBlank()) {
            throw new PlatformException(ErrorCode.of("MENU_CODE_REQUIRED", "menu code is required"));
        }
    }

    private void validateParent(Long parentId) {
        if (parentId != null && managementPort.findById(parentId).isEmpty()) {
            throw new PlatformException(ErrorCode.of("MENU_INVALID_PARENT",
                    "parent menu not found: " + parentId));
        }
    }

    private void validatePermissionCode(String permissionCode) {
        if (permissionCode == null || permissionCode.isBlank()) {
            return;
        }
        if (!managementPort.permissionCodeExists(permissionCode)) {
            throw new PlatformException(ErrorCode.of("MENU_PERMISSION_NOT_FOUND",
                    "permission code does not exist: " + permissionCode));
        }
    }
}
