package ${package}.api.menu;

import ${package}.application.menu.MenuService;
import ${package}.common.core.ApiResponse;
import ${package}.common.core.PlatformException;
import ${package}.common.core.RequestContext;
import ${package}.common.security.SecurityErrorCodes;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * Menu API (generated by engineering-platform ${asset.version}).
 *
 * GET /api/menus/me returns the permission-filtered menu tree of the current
 * user. Menu visibility filtering references RBAC permission codes but does NOT
 * replace @RequirePermission authorization on backend endpoints.
 */
@RestController
@RequestMapping("/api/menus")
public class MenuController {

    private final MenuService menuService;

    public MenuController(MenuService menuService) {
        this.menuService = menuService;
    }

    @GetMapping("/me")
    public ApiResponse<List<MenuService.MenuNode>> me() {
        String currentUserId = RequestContext.currentUserId()
                .orElseThrow(() -> new PlatformException(SecurityErrorCodes.UNAUTHENTICATED));
        Long userId = Long.valueOf(currentUserId);
        return ApiResponse.ofSuccess(menuService.treeForUser(userId));
    }

    @GetMapping("/tree")
    public ApiResponse<List<MenuService.MenuNode>> tree() {
        return ApiResponse.ofSuccess(menuService.tree());
    }
}
