package ${package};

import ${package}.api.auth.LoginRequest;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.ActiveProfiles;

import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Real HTTP Menu E2E (generated by engineering-platform ${asset.version}).
 *
 * Proves menu permission filtering over real HTTP:
 *   admin (system:user:read + system:menu:manage + product:item:read via data-permission seed)
 *   viewer (no permissions)
 *
 * Seed menus (see seed-zz-menu.sql):
 *   1 System (DIRECTORY)
 *     2 User management (MENU, system:user:read)
 *     3 Menu management (ACTION, system:menu:manage)
 *   4 Products (DIRECTORY)
 *     5 Product list (MENU, product:item:read)
 *     6 Disabled node (MENU, enabled=0)
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
class MenuE2ETest {

    @LocalServerPort
    private int port;

    @Autowired
    private TestRestTemplate rest;

    private String url(String path) {
        return "http://localhost:" + port + path;
    }

    private ResponseEntity<Map> login(String username, String password) {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        HttpEntity<LoginRequest> body = new HttpEntity<>(new LoginRequest(username, password), headers);
        return rest.postForEntity(url("/api/auth/login"), body, Map.class);
    }

    private String token(String username, String password) {
        ResponseEntity<Map> response = login(username, password);
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        Map data = (Map) response.getBody().get("data");
        return (String) data.get("token");
    }

    @SuppressWarnings("unchecked")
    private List<Map> myMenuTree(String token) {
        HttpHeaders headers = new HttpHeaders();
        headers.setBearerAuth(token);
        ResponseEntity<Map> response = rest.exchange(url("/api/menus/me"), HttpMethod.GET,
                new HttpEntity<>(headers), Map.class);
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        return (List<Map>) response.getBody().get("data");
    }

    // A. admin sees all enabled menus (root containers + permission-gated leaves)
    @Test
    void adminSeesFullMenuTree() {
        String token = token("admin", "admin123");
        List<Map> tree = myMenuTree(token);
        assertThat(tree).hasSize(2); // System + Products containers
        List<Map> systemChildren = (List<Map>) tree.get(0).get("children");
        assertThat(systemChildren).hasSize(2); // User management + Menu management
        List<Map> productChildren = (List<Map>) tree.get(1).get("children");
        assertThat(productChildren).hasSize(1); // Product list only (disabled excluded)
    }

    // B. viewer (no permissions) sees only containers with no children pruned -> empty
    @Test
    void viewerSeesNoPermissionGatedMenus() {
        String token = token("viewer", "admin123");
        List<Map> tree = myMenuTree(token);
        // containers without any visible child are pruned
        assertThat(tree).isEmpty();
    }

    // C. disabled menu never appears even for admin
    @Test
    void disabledMenuExcludedForAdmin() {
        String token = token("admin", "admin123");
        List<Map> tree = myMenuTree(token);
        String json = tree.toString();
        assertThat(json).doesNotContain("Disabled");
        assertThat(json).doesNotContain("product-disabled");
    }

    // D. anonymous denied on /api/menus/me
    @Test
    void anonymousDenied() {
        ResponseEntity<Map> response = rest.exchange(
                url("/api/menus/me"), HttpMethod.GET, HttpEntity.EMPTY, Map.class);
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.UNAUTHORIZED);
    }
}
