package ${package}.application.menu;

import ${package}.application.rbac.UserQueryPort;
import ${package}.common.core.ErrorCode;
import ${package}.common.core.PlatformException;
import ${package}.domain.entity.SysMenu;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Menu application service (generated by engineering-platform ${asset.version}).
 *
 * Backend permission resource model:
 *   - tree building with structural validation (self-parent / cycle prevention)
 *   - permission filtering via RBAC (menu.permissionCode references sys_permission.code)
 *   - menu.permissionCode only filters visibility; authorization stays with @RequirePermission
 */
public class MenuService {

    /** Menu tree node. */
    public record MenuNode(SysMenu menu, List<MenuNode> children) {
    }

    private final MenuPort menuPort;
    private final UserQueryPort userQueryPort;

    public MenuService(MenuPort menuPort, UserQueryPort userQueryPort) {
        this.menuPort = menuPort;
        this.userQueryPort = userQueryPort;
    }

    /**
     * Full menu tree (admin / unrestricted view). Stable ordering: sort then id.
     * Disabled menus are excluded.
     */
    public List<MenuNode> tree() {
        List<SysMenu> all = menuPort.findAll();
        validateStructure(all);
        List<SysMenu> enabled = all.stream().filter(m -> Boolean.TRUE.equals(m.getEnabled())).toList();
        return buildTree(enabled);
    }

    /**
     * Permission-filtered menu tree for a user (GET /api/menus/me).
     * A menu is visible when it has no permissionCode (e.g. DIRECTORY container)
     * or the user holds that permission code. Empty containers are pruned.
     */
    public List<MenuNode> treeForUser(Long userId) {
        List<SysMenu> all = menuPort.findAll();
        validateStructure(all);
        Set<String> granted = userQueryPort.permissionCodesOf(userId);
        List<SysMenu> visible = new ArrayList<>();
        for (SysMenu m : all) {
            if (!Boolean.TRUE.equals(m.getEnabled())) {
                continue;
            }
            if (m.getPermissionCode() == null || m.getPermissionCode().isBlank()
                    || granted.contains(m.getPermissionCode())) {
                visible.add(m);
            }
        }
        return pruneEmpty(buildTree(visible));
    }

    /** Rejects self-parent and any cycle reachable from the given node. */
    public void validateStructure(List<SysMenu> all) {
        for (SysMenu m : all) {
            if (m.getParentId() != null && m.getParentId().equals(m.getId())) {
                throw new PlatformException(ErrorCode.of("MENU_SELF_PARENT",
                        "menu cannot be its own parent: " + m.getCode()));
            }
        }
        for (SysMenu m : all) {
            if (m.getParentId() == null) {
                continue;
            }
            Set<Long> seen = new HashSet<>();
            Long cursor = m.getParentId();
            while (cursor != null && seen.add(cursor)) {
                if (cursor.equals(m.getId())) {
                    throw new PlatformException(ErrorCode.of("MENU_CYCLE",
                            "menu cycle detected at: " + m.getCode()));
                }
                Long next = null;
                for (SysMenu x : all) {
                    if (x.getId().equals(cursor)) {
                        next = x.getParentId();
                        break;
                    }
                }
                cursor = next;
            }
        }
    }

    /** Stable tree: roots first (sort then id via repository), children appended in input order. */
    private List<MenuNode> buildTree(List<SysMenu> all) {
        Map<Long, MenuNode> nodes = new LinkedHashMap<>();
        for (SysMenu m : all) {
            nodes.put(m.getId(), new MenuNode(m, new ArrayList<>()));
        }
        List<MenuNode> roots = new ArrayList<>();
        for (SysMenu m : all) {
            MenuNode node = nodes.get(m.getId());
            if (m.getParentId() == null || !nodes.containsKey(m.getParentId())) {
                roots.add(node);
            } else {
                nodes.get(m.getParentId()).children().add(node);
            }
        }
        return roots;
    }

    /** Remove container nodes that ended up with no children (permission filtering). */
    private List<MenuNode> pruneEmpty(List<MenuNode> nodes) {
        List<MenuNode> result = new ArrayList<>();
        for (MenuNode node : nodes) {
            List<MenuNode> kept = pruneEmpty(node.children());
            if (!kept.isEmpty() || node.children().isEmpty() && hasOwnPermission(node.menu())) {
                result.add(new MenuNode(node.menu(), kept));
            }
        }
        return result;
    }

    private boolean hasOwnPermission(SysMenu menu) {
        return menu.getPermissionCode() != null && !menu.getPermissionCode().isBlank();
    }
}
