package ${package}.infrastructure.persistence;

import ${package}.application.menu.MenuPort;
import ${package}.application.menu.MenuService;
import ${package}.application.rbac.UserQueryPort;
import ${package}.infrastructure.persistence.mapper.SysMenuMapper;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Menu bean wiring (generated by engineering-platform ${asset.version}).
 */
@Configuration
public class MenuBeansConfig {

    @Bean
    public MenuPort menuPort(SysMenuMapper menuMapper) {
        return new MybatisMenuRepository(menuMapper);
    }

    @Bean
    public MenuService menuService(MenuPort menuPort, UserQueryPort userQueryPort) {
        return new MenuService(menuPort, userQueryPort);
    }
}
