package ${package}.infrastructure.persistence;

import ${package}.application.menu.MenuManagementPort;
import ${package}.application.menu.MenuManagementService;
import ${package}.application.menu.MenuPort;
import ${package}.application.menu.MenuService;
import ${package}.application.rbac.UserQueryPort;
import ${package}.infrastructure.persistence.mapper.SysMenuMapper;
import ${package}.infrastructure.persistence.mapper.SysPermissionMapper;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Menu bean wiring (generated by engineering-platform ${asset.version}).
 * MyBatis implementations are wired as the stable application contracts
 * (MenuPort / MenuManagementPort); application services depend only on those
 * contracts.
 */
@Configuration
public class MenuBeansConfig {

    @Bean
    public MenuPort menuPort(SysMenuMapper menuMapper) {
        return new MybatisMenuRepository(menuMapper);
    }

    @Bean
    public MenuService menuService(MenuPort menuPort, UserQueryPort userQueryPort) {
        return new MenuService(menuPort, userQueryPort);
    }

    @Bean
    public MenuManagementPort menuManagementPort(SysMenuMapper menuMapper,
                                                 SysPermissionMapper permissionMapper) {
        return new MybatisMenuManagementRepository(menuMapper, permissionMapper);
    }

    @Bean
    public MenuManagementService menuManagementService(MenuManagementPort menuManagementPort,
                                                       MenuService menuService) {
        return new MenuManagementService(menuManagementPort, menuService);
    }
}
