package ${package}.application.menu;

import ${package}.domain.entity.SysMenu;

import java.util.List;
import java.util.Optional;

/**
 * Menu management write/read contract (generated by engineering-platform ${asset.version}).
 *
 * Stable application-level management contract. The implementation lives in the
 * infrastructure layer (MyBatis-Plus); application/business code depends only
 * on this interface — never on MyBatis persistence types.
 *
 * Transaction semantics belong to the application service that orchestrates
 * these operations (structural validation + write is one unit of work).
 */
public interface MenuManagementPort {

    Optional<SysMenu> findById(Long menuId);

    List<SysMenu> findAll();

    /** True when a menu with the code exists. */
    boolean codeExists(String code);

    /** True when a permission with the code exists (Menu ≠ Authorization). */
    boolean permissionCodeExists(String permissionCode);

    void insert(SysMenu menu);

    void update(SysMenu menu);
}
