package ${package}.infrastructure.persistence;

import ${package}.application.menu.MenuManagementPort;
import ${package}.domain.entity.SysMenu;
import ${package}.domain.entity.SysPermission;
import ${package}.infrastructure.persistence.mapper.SysMenuMapper;
import ${package}.infrastructure.persistence.mapper.SysPermissionMapper;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;

import java.util.List;
import java.util.Optional;

/**
 * MyBatis-Plus implementation of {@link MenuManagementPort} (generated by engineering-platform ${asset.version}).
 *
 * All MyBatis-Plus technical types (QueryWrapper / BaseMapper) stay confined
 * here, in the infrastructure layer.
 */
public class MybatisMenuManagementRepository implements MenuManagementPort {

    private final SysMenuMapper menuMapper;
    private final SysPermissionMapper permissionMapper;

    public MybatisMenuManagementRepository(SysMenuMapper menuMapper, SysPermissionMapper permissionMapper) {
        this.menuMapper = menuMapper;
        this.permissionMapper = permissionMapper;
    }

    @Override
    public Optional<SysMenu> findById(Long menuId) {
        return Optional.ofNullable(menuMapper.selectById(menuId));
    }

    @Override
    public List<SysMenu> findAll() {
        return menuMapper.selectList(
                new QueryWrapper<SysMenu>().orderByAsc("sort", "id"));
    }

    @Override
    public boolean codeExists(String code) {
        return menuMapper.selectCount(new QueryWrapper<SysMenu>().eq("code", code)) > 0;
    }

    @Override
    public boolean permissionCodeExists(String permissionCode) {
        return permissionMapper.selectCount(new QueryWrapper<SysPermission>()
                .eq("code", permissionCode)) > 0;
    }

    @Override
    public void insert(SysMenu menu) {
        menuMapper.insert(menu);
    }

    @Override
    public void update(SysMenu menu) {
        menuMapper.updateById(menu);
    }
}
