package ${package}.infrastructure.persistence;

import ${package}.application.menu.MenuPort;
import ${package}.domain.entity.SysMenu;
import ${package}.infrastructure.persistence.mapper.SysMenuMapper;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;

import java.util.List;

/**
 * MyBatis-Plus implementation of {@link MenuPort} (generated by engineering-platform ${asset.version}).
 * All MyBatis types stay confined here, in the infrastructure layer.
 */
public class MybatisMenuRepository implements MenuPort {

    private final SysMenuMapper menuMapper;

    public MybatisMenuRepository(SysMenuMapper menuMapper) {
        this.menuMapper = menuMapper;
    }

    @Override
    public List<SysMenu> findAll() {
        return menuMapper.selectList(new QueryWrapper<SysMenu>().orderByAsc("sort", "id"));
    }
}
