-- Menu schema (generated by engineering-platform ${asset.version})
-- V005: sys_menu — backend permission resource model (DIRECTORY / MENU / ACTION)
-- MySQL-compatible baseline (H2 MODE=MySQL for tests).

CREATE TABLE IF NOT EXISTS sys_menu (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    parent_id       BIGINT       NULL,
    code            VARCHAR(64)  NOT NULL,
    name            VARCHAR(64)  NOT NULL,
    type            VARCHAR(16)  NOT NULL,
    path            VARCHAR(128) NULL,
    permission_code VARCHAR(128) NULL,
    enabled         TINYINT(1)   NOT NULL DEFAULT 1,
    sort            INT          NOT NULL DEFAULT 0,
    created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_sys_menu_code UNIQUE (code),
    KEY idx_sys_menu_parent (parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
