package com.engineeringplatform.generator.core;

import com.engineeringplatform.generator.contracts.BusinessEntityField;
import com.engineeringplatform.generator.contracts.ResolvedBusinessModule;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * V06-WORK-003 — Generic Frontend Templates.
 *
 * Frontend rendering responsibility of the Generic Module Generator, split out
 * of GenericModuleGenerator so UI/template strings stop growing that single
 * class. Produces the full frontend file set (types/api/router/views/tests)
 * for one resolved Business Module Contract.
 *
 * Architecture rule unchanged: this is still pure content generation inside
 * the existing AssetProjectGenerator pipeline — no second execution engine.
 */
public final class GenericFrontendTemplates {

    /**
     * Generate all frontend files for one business module.
     */
    public List<GenericModuleGenerator.GeneratedFile> generateFrontend(ResolvedBusinessModule module) {
        String entity = module.entity().name();
        String entityVar = decapitalize(entity);
        String modPkg = module.id().replace("-", "");
        String route = frontendRoute(module);
        String table = module.table() == null ? module.id().replace("-", "_") : module.table();
        List<BusinessEntityField> fields = module.entity().fields();
        boolean dataScope = bool(module.enterprise(), "dataScope");
        boolean permissions = bool(module.enterprise(), "permissions");
        boolean dictionary = bool(module.enterprise(), "dictionary");
        List<String> features = module.features();
        String label = str(module.frontend(), "label", module.name());
        String title = label + "s";

        List<GenericModuleGenerator.GeneratedFile> files = new ArrayList<>();
        files.add(new GenericModuleGenerator.GeneratedFile("frontend/src/types/" + module.id() + ".ts", typesSource(module.id(), entity, fields, dataScope)));
        files.add(new GenericModuleGenerator.GeneratedFile("frontend/src/api/" + module.id() + ".ts", apiSource(module.id(), entity, fields, features, table)));
        files.add(new GenericModuleGenerator.GeneratedFile("frontend/src/router/business/" + module.id() + ".ts", routerSource(module.id(), entity, route, table, features)));
        files.add(new GenericModuleGenerator.GeneratedFile("frontend/src/views/" + modPkg + "/" + entity + "ListView.vue",
                listViewSource(module.id(), entity, entityVar, fields, features, dataScope, permissions, dictionary, route, table, title, label)));
        files.add(new GenericModuleGenerator.GeneratedFile("frontend/src/views/" + modPkg + "/" + entity + "DetailView.vue",
                detailViewSource(module.id(), entity, entityVar, fields, dataScope, permissions, route, title)));
        files.add(new GenericModuleGenerator.GeneratedFile("frontend/src/views/" + modPkg + "/" + entity + "EditView.vue",
                editViewSource(module.id(), entity, entityVar, fields, permissions, route, title)));
        files.add(new GenericModuleGenerator.GeneratedFile("frontend/tests/" + module.id() + "-api.spec.ts", apiSpecSource(module.id(), entity, fields, table, dataScope)));
        files.add(new GenericModuleGenerator.GeneratedFile("frontend/tests/" + module.id() + "-route.spec.ts", routeSpecSource(module.id(), entity, route, table)));
        files.add(new GenericModuleGenerator.GeneratedFile("frontend/tests/" + module.id() + "-list.spec.ts", listSpecSource(module.id(), entity, fields, table, title, dataScope)));
        files.add(new GenericModuleGenerator.GeneratedFile("frontend/tests/" + module.id() + "-detail.spec.ts", detailSpecSource(module.id(), entity, table, title)));
        return files;
    }

    private String typesSource(String moduleId, String entity, List<BusinessEntityField> fields, boolean dataScope) {
        StringBuilder sb = new StringBuilder();
        sb.append("// ").append(entity).append(" types (generated by engineering-platform Generic Module Generator)\n");
        sb.append("// API Boundary ID String Contract: Snowflake IDs cross as strings (EntityId).\n");
        sb.append("import type { PageResult, EntityId } from './enterprise';\n\n");
        sb.append("export type { PageResult, EntityId };\n\n");
        sb.append("export interface ").append(entity).append(" {\n");
        sb.append("  id: EntityId;\n");
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            sb.append("  ").append(f.name()).append(": ").append(tsType(f)).append(";\n");
        }
        if (dataScope) sb.append("  departmentId: EntityId | null;\n");
        sb.append("  createdBy: EntityId | null;\n");
        sb.append("  createdAt: string;\n");
        sb.append("  updatedAt: string;\n");
        sb.append("}\n\n");
        sb.append("export interface ").append(entity).append("CreateRequest {\n");
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            sb.append("  ").append(f.name()).append(": ").append(tsType(f)).append(";\n");
        }
        sb.append("}\n\n");
        sb.append("export interface ").append(entity).append("UpdateRequest {\n");
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            sb.append("  ").append(f.name()).append(": ").append(tsType(f)).append(";\n");
        }
        sb.append("}\n\n");
        sb.append("export interface ").append(entity).append("Query {\n");
        sb.append("  page?: number;\n  size?: number;\n  keyword?: string;\n");
        if (hasSemantic(fields, "dictionary")) sb.append("  status?: string;\n");
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            if (Boolean.TRUE.equals(f.frontend().get("searchable"))) {
                sb.append("  ").append(f.name()).append("?: string;\n");
            }
        }
        sb.append("}\n\n");
        sb.append("export type ").append(entity).append("PageResponse = PageResult<").append(entity).append(">;\n");
        return sb.toString();
    }

    private String apiSource(String moduleId, String entity, List<BusinessEntityField> fields,
                             List<String> features, String table) {
        String entityVar = decapitalize(entity);
        StringBuilder sb = new StringBuilder();
        sb.append("// ").append(entity).append(" API service (generated by engineering-platform Generic Module Generator)\n");
        sb.append("// All HTTP through the Platform Request Client — no raw axios/fetch.\n");
        sb.append("import { http } from './request';\n");
        sb.append("import type { ").append(entity).append(", ").append(entity).append("CreateRequest, ").append(entity)
                .append("UpdateRequest, ").append(entity).append("Query, ").append(entity).append("PageResponse } from '../types/").append(moduleId).append("';\n");
        sb.append("import type { EntityId } from '../types/enterprise';\n\n");
        sb.append("export const ").append(entityVar).append("Api = {\n");
        if (features.contains("list")) {
            sb.append("  page: (query: ").append(entity).append("Query = {}) =>\n");
            sb.append("    http.get<").append(entity).append("PageResponse>('/").append(table).append("' + queryString(query as unknown as Record<string, unknown>)),\n");
        }
        if (features.contains("detail")) {
            sb.append("  detail: (id: EntityId) => http.get<").append(entity).append(">('/").append(table).append("/' + id),\n");
        }
        if (features.contains("create")) {
            sb.append("  create: (body: ").append(entity).append("CreateRequest) => http.post<").append(entity).append(">('/").append(table).append("', body),\n");
        }
        if (features.contains("edit")) {
            sb.append("  update: (id: EntityId, body: ").append(entity).append("UpdateRequest) => http.put<").append(entity).append(">('/").append(table).append("/' + id, body),\n");
        }
        if (features.contains("disable")) {
            sb.append("  disable: (id: EntityId) => http.post<").append(entity).append(">('/").append(table).append("/' + id + '/disable', {}),\n");
        }
        sb.append("};\n\n");
        sb.append("function queryString(params: Record<string, unknown>): string {\n");
        sb.append("  const entries = Object.entries(params).filter(([, v]) => v !== undefined && v !== null && v !== '');\n");
        sb.append("  if (entries.length === 0) return '';\n");
        sb.append("  return '?' + entries.map(([k, v]) => encodeURIComponent(k) + '=' + encodeURIComponent(String(v))).join('&');\n");
        sb.append("}\n");
        return sb.toString();
    }

    private String routerSource(String moduleId, String entity, String route, String table, List<String> features) {
        StringBuilder sb = new StringBuilder();
        sb.append("// ").append(entity).append(" routes (generated by engineering-platform Generic Module Generator)\n");
        sb.append("// Generic business-module route module: frontend-auth aggregates ALL files under\n");
        sb.append("// ../router/business/*.ts via glob — no module name is hardcoded in frontend-auth.\n");
        sb.append("import type { RouteRecordRaw } from 'vue-router';\n\n");
        sb.append("export const businessRoutes: RouteRecordRaw[] = [\n");
        sb.append("  {\n    path: '").append(route).append("',\n    name: '").append(moduleId).append("',\n");
        sb.append("    component: () => import('../../views/").append(moduleId.replace("-", "")).append("/").append(entity).append("ListView.vue'),\n");
        sb.append("    meta: { title: '").append(entity).append("s', permission: '").append(table).append(":item:read' },\n  },\n");
        if (features.contains("detail")) {
            sb.append("  {\n    path: '").append(route).append("/:id',\n    name: '").append(moduleId).append("-detail',\n");
            sb.append("    component: () => import('../../views/").append(moduleId.replace("-", "")).append("/").append(entity).append("DetailView.vue'),\n");
            sb.append("    meta: { title: '").append(entity).append(" Detail', permission: '").append(table).append(":item:read' },\n  },\n");
        }
        if (features.contains("edit")) {
            sb.append("  {\n    path: '").append(route).append("/:id/edit',\n    name: '").append(moduleId).append("-edit',\n");
            sb.append("    component: () => import('../../views/").append(moduleId.replace("-", "")).append("/").append(entity).append("EditView.vue'),\n");
            sb.append("    meta: { title: 'Edit ").append(entity).append("', permission: '").append(table).append(":item:update' },\n  },\n");
        }
        sb.append("];\n");
        return sb.toString();
    }

    private String listViewSource(String moduleId, String entity, String entityVar,
                                  List<BusinessEntityField> fields, List<String> features,
                                  boolean dataScope, boolean permissions, boolean dictionary,
                                  String route, String table, String title, String label) {
        StringBuilder sb = new StringBuilder();
        sb.append("<script setup lang=\"ts\">\n");
        sb.append("// ").append(entity).append(" List (generated by engineering-platform Generic Module Generator)\n");
        sb.append("// EP UI 2.0 generic list: header + optional stats + search panel + data card.\n");
        sb.append("import { computed, onMounted, reactive, ref } from 'vue';\n");
        sb.append("import { useRouter } from 'vue-router';\n");
        sb.append("import PageHeader from '../../components/PageHeader.vue';\n");
        sb.append("import PageContainer from '../../components/PageContainer.vue';\n");
        sb.append("import SearchForm from '../../components/SearchForm.vue';\n");
        sb.append("import AppTable from '../../components/AppTable.vue';\n");
        // V06-FINAL: StatusTag/DictionarySelect only imported when actually used
        // (a module without semantic:dictionary fields must not import them —
        // otherwise the generated frontend fails `vue-tsc` with TS6133).
        if (hasSemantic(fields, "dictionary")) {
            sb.append("import StatusTag from '../../components/StatusTag.vue';\n");
        }
        sb.append("import StatCard from '../../components/StatCard.vue';\n");
        sb.append("import ConfirmAction from '../../components/ConfirmAction.vue';\n");
        sb.append("import FormDrawer from '../../components/FormDrawer.vue';\n");
        sb.append("import AppForm from '../../components/AppForm.vue';\n");
        if (hasSemantic(fields, "dictionary")) sb.append("import DictionarySelect from '../../components/DictionarySelect.vue';\n");
        if (permissions) sb.append("import PermissionButton from '../../permission/PermissionButton.vue';\n");
        sb.append("import { ").append(entityVar).append("Api } from '../../api/").append(moduleId).append("';\n");
        sb.append("import type { ").append(entity).append(" } from '../../types/").append(moduleId).append("';\n");
        sb.append("import { errorMessage, notifySuccess, toastSuccess } from '../../utils/feedback';\n\n");
        sb.append("const router = useRouter();\n");
        sb.append("const loading = ref(false);\n");
        sb.append("const listError = ref<string | null>(null);\n");
        sb.append("const rows = ref<").append(entity).append("[]>([]);\n");
        sb.append("const total = ref(0);\n");
        sb.append("const page = ref(1);\n");
        sb.append("const size = ref(20);\n");
        sb.append("const filters = reactive({ keyword: ''");
        if (hasSemantic(fields, "dictionary")) sb.append(", status: ''");
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            if (Boolean.TRUE.equals(f.frontend().get("searchable"))) {
                sb.append(", ").append(f.name()).append(": ''");
            }
        }
        sb.append(" });\n\n");
        sb.append("const drawerOpen = ref(false);\n");
        sb.append("const editing = ref<").append(entity).append(" | null>(null);\n");
        sb.append("const submitting = ref(false);\n");
        sb.append("const formError = ref<string | null>(null);\n");
        sb.append("const form = reactive({");
        boolean first = true;
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            if (!first) sb.append(", ");
            first = false;
            sb.append(f.name()).append(": ").append(tsDefault(f));
        }
        sb.append(" });\n\n");
        // stats derived from current page (deterministic, no backend needed)
        sb.append("const enabledCount = computed(() => rows.value.filter(r => ");
        String statusField = statusField(fields);
        if (statusField != null) {
            sb.append("r.").append(statusField).append(" === 'ENABLED'");
        } else {
            sb.append("true");
        }
        sb.append(").length);\n");
        sb.append("const disabledCount = computed(() => rows.value.length - enabledCount.value);\n\n");
        sb.append("async function load(): Promise<void> {\n");
        sb.append("  loading.value = true;\n  listError.value = null;\n  try {\n");
        sb.append("    const result = await ").append(entityVar).append("Api.page({\n");
        sb.append("      page: page.value,\n      size: size.value,\n");
        sb.append("      keyword: filters.keyword || undefined");
        if (hasSemantic(fields, "dictionary")) sb.append(",\n      status: filters.status || undefined");
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            if (Boolean.TRUE.equals(f.frontend().get("searchable"))) {
                sb.append(",\n      ").append(f.name()).append(": filters.").append(f.name()).append(" || undefined");
            }
        }
        sb.append(",\n    });\n");
        sb.append("    rows.value = result.items;\n    total.value = result.total;\n");
        sb.append("  } catch (e) { listError.value = errorMessage(e); } finally { loading.value = false; }\n");
        sb.append("}\n\n");
        sb.append("function resetFilters(): void {\n");
        sb.append("  filters.keyword = ''");
        if (hasSemantic(fields, "dictionary")) sb.append(";\n  filters.status = ''");
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            if (Boolean.TRUE.equals(f.frontend().get("searchable"))) {
                sb.append(";\n  filters.").append(f.name()).append(" = ''");
            }
        }
        sb.append(";\n  page.value = 1;\n  load();\n}\n\n");
        sb.append("function openCreate(): void {\n");
        sb.append("  editing.value = null;\n  formError.value = null;\n");
        sb.append("  Object.assign(form, {");
        first = true;
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            if (!first) sb.append(", ");
            first = false;
            sb.append(f.name()).append(": ").append(tsDefault(f));
        }
        sb.append(" });\n  drawerOpen.value = true;\n}\n\n");
        sb.append("function openEdit(p: ").append(entity).append("): void {\n");
        sb.append("  editing.value = p;\n  formError.value = null;\n");
        sb.append("  Object.assign(form, {");
        first = true;
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            if (!first) sb.append(", ");
            first = false;
            sb.append(f.name()).append(": p.").append(f.name());
        }
        sb.append(" });\n  drawerOpen.value = true;\n}\n\n");
        sb.append("async function submit(): Promise<void> {\n");
        sb.append("  submitting.value = true;\n  formError.value = null;\n");
        sb.append("  const body = {");
        first = true;
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            if (!first) sb.append(", ");
            first = false;
            sb.append(f.name()).append(": form.").append(f.name());
        }
        sb.append(" };\n  try {\n");
        sb.append("    if (editing.value) { await ").append(entityVar).append("Api.update(editing.value.id, body); notifySuccess('").append(label).append(" updated'); }\n");
        sb.append("    else { await ").append(entityVar).append("Api.create(body); notifySuccess('").append(label).append(" created'); }\n");
        sb.append("    drawerOpen.value = false;\n    await load();\n");
        sb.append("  } catch (e) { formError.value = errorMessage(e); } finally { submitting.value = false; }\n");
        sb.append("}\n\n");
        sb.append("async function doDisable(p: ").append(entity).append("): Promise<void> {\n");
        sb.append("  try { await ").append(entityVar).append("Api.disable(p.id); toastSuccess('").append(label).append(" disabled'); await load(); }\n");
        sb.append("  catch (e) { toastSuccess(errorMessage(e)); }\n}\n\n");
        sb.append("onMounted(load);\n");
        sb.append("</script>\n\n<template>\n");
        sb.append("  <PageContainer full-width>\n");
        sb.append("    <PageHeader title=\"").append(title).append("\" description=\"Generic business module — ").append(moduleId).append(".\" eyebrow=\"").append(entity).append("\">\n");
        sb.append("      <template #actions>\n");
        if (permissions && features.contains("create")) {
            sb.append("        <PermissionButton permission=\"").append(table).append(":item:create\" type=\"primary\" data-testid=\"create-").append(moduleId).append("\" @click=\"openCreate\">Create ").append(label).append("</PermissionButton>\n");
        }
        sb.append("      </template>\n    </PageHeader>\n\n");
        // stats row (EP UI 2.0: colorful KPI strip; only when data is present)
        sb.append("    <div v-if=\"total > 0\" class=\"list-stats\" data-testid=\"list-stats\">\n");
        sb.append("      <StatCard label=\"Total\" :value=\"total\" accent=\"indigo\" marker=\"T\" />\n");
        if (statusField != null) {
            sb.append("      <StatCard label=\"Enabled\" :value=\"enabledCount\" accent=\"emerald\" marker=\"E\" />\n");
            sb.append("      <StatCard label=\"Disabled\" :value=\"disabledCount\" accent=\"rose\" marker=\"D\" />\n");
        } else {
            sb.append("      <StatCard label=\"Current page\" :value=\"rows.length\" accent=\"sky\" marker=\"P\" />\n");
        }
        sb.append("    </div>\n\n");
        sb.append("    <SearchForm more @search=\"load\" @reset=\"resetFilters\">\n");
        sb.append("      <el-input v-model=\"filters.keyword\" placeholder=\"Search\" clearable style=\"width: 240px\" data-testid=\"").append(moduleId).append("-search-keyword\" />\n");
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            if (Boolean.TRUE.equals(f.frontend().get("searchable"))) {
                sb.append("      <el-input v-model=\"filters.").append(f.name()).append("\" placeholder=\"").append(labelOf(f)).append("\" clearable style=\"width: 200px\" data-testid=\"").append(moduleId).append("-search-").append(f.name()).append("\" />\n");
            }
        }
        if (dictionary) {
            for (BusinessEntityField f : fields) {
                if ("dictionary".equals(f.semantic()) && f.dictionary() != null) {
                    sb.append("      <DictionarySelect v-model=\"filters.status\" code=\"").append(f.dictionary()).append("\" placeholder=\"").append(capitalize(f.name())).append("\" clearable data-testid=\"").append(moduleId).append("-filter-").append(f.name()).append("\" />\n");
                }
            }
        }
        sb.append("    </SearchForm>\n\n");
        sb.append("    <AppTable :loading=\"loading\" :error=\"listError\" :data=\"rows\" :total=\"total\" :page=\"page\" :size=\"size\" @refresh=\"load\" @update:page=\"(p: number) => { page = p; load(); }\" @update:size=\"(s: number) => { size = s; page = 1; load(); }\">\n");
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            if (Boolean.FALSE.equals(f.frontend().get("listVisible"))) continue;
            if ("dictionary".equals(f.semantic())) {
                sb.append("      <el-table-column prop=\"").append(f.name()).append("\" label=\"").append(labelOf(f)).append("\" min-width=\"120\">\n");
                sb.append("        <template #default=\"{ row }\"><StatusTag :enabled=\"row.").append(f.name()).append(" === 'ENABLED'\" active-text=\"Enabled\" inactive-text=\"Disabled\" /></template>\n");
                sb.append("      </el-table-column>\n");
            } else {
                sb.append("      <el-table-column prop=\"").append(f.name()).append("\" label=\"").append(labelOf(f)).append("\" min-width=\"130\" />\n");
            }
        }
        if (dataScope) {
            sb.append("      <el-table-column prop=\"departmentId\" label=\"Department\" width=\"120\"><template #default=\"{ row }\">{{ row.departmentId ?? '—' }}</template></el-table-column>\n");
        }
        sb.append("      <el-table-column label=\"Actions\" width=\"180\" fixed=\"right\">\n");
        sb.append("        <template #default=\"{ row }\">\n");
        if (features.contains("detail")) {
            sb.append("          <el-button size=\"small\" type=\"primary\" link data-testid=\"").append(moduleId).append("-detail-open\" @click=\"router.push({ path: '").append(route).append("/' + row.id })\">Detail</el-button>\n");
        }
        if (features.contains("edit")) {
            sb.append("          <el-button size=\"small\" link data-testid=\"").append(moduleId).append("-open\" @click=\"openEdit(row)\">Edit</el-button>\n");
        }
        if (features.contains("disable")) {
            sb.append("          <ConfirmAction v-if=\"row.").append(statusField != null ? statusField : "status").append(" === 'ENABLED'\" :title=\"'Disable ' + row.id + '?'\" @confirm=\"doDisable(row)\">\n");
            if (permissions) {
                sb.append("            <PermissionButton permission=\"").append(table).append(":item:disable\" size=\"small\" type=\"danger\" link data-testid=\"").append(moduleId).append("-disable-trigger\">Disable</PermissionButton>\n");
            } else {
                sb.append("            <el-button size=\"small\" type=\"danger\" link data-testid=\"").append(moduleId).append("-disable-trigger\">Disable</el-button>\n");
            }
            sb.append("          </ConfirmAction>\n");
        }
        sb.append("        </template>\n      </el-table-column>\n");
        sb.append("    </AppTable>\n\n");
        if (features.contains("create") || features.contains("edit")) {
            sb.append("    <FormDrawer v-model=\"drawerOpen\" :title=\"editing ? 'Edit ").append(label).append("' : 'Create ").append(label).append("'\">\n");
            sb.append("      <AppForm :model=\"form as unknown as Record<string, unknown>\" :submitting=\"submitting\" :error=\"formError\" :submit-text=\"editing ? 'Save' : 'Create'\" compact @submit=\"submit\" @cancel=\"drawerOpen = false\">\n");
            for (BusinessEntityField f : fields) {
                if (isSystemField(f)) continue;
                if (Boolean.FALSE.equals(f.frontend().get("formVisible"))) continue;
                sb.append("        <el-form-item label=\"").append(labelOf(f)).append("\"");
                if (f.required()) sb.append(" :rules=\"[{ required: true, message: '").append(labelOf(f)).append(" is required' }]\"");
                sb.append(">\n");
                if ("dictionary".equals(f.semantic()) && f.dictionary() != null) {
                    sb.append("          <DictionarySelect v-model=\"form.").append(f.name()).append("\" code=\"").append(f.dictionary()).append("\" style=\"width: 100%\" data-testid=\"").append(moduleId).append("-form-").append(f.name()).append("\" />\n");
                } else if ("boolean".equals(f.type())) {
                    sb.append("          <el-switch v-model=\"form.").append(f.name()).append("\" data-testid=\"").append(moduleId).append("-form-").append(f.name()).append("\" />\n");
                } else {
                    sb.append("          <el-input v-model=\"form.").append(f.name()).append("\" data-testid=\"").append(moduleId).append("-form-").append(f.name()).append("\" />\n");
                }
                sb.append("        </el-form-item>\n");
            }
            sb.append("        <div class=\"form-hint\">Department and creator are set by the server from your session — never from the client.</div>\n");
            sb.append("      </AppForm>\n    </FormDrawer>\n");
        }
        sb.append("  </PageContainer>\n</template>\n\n<style scoped>\n.list-stats {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));\n  gap: var(--ep-space-4);\n  margin-bottom: var(--ep-space-5);\n}\n.form-hint { font-size: var(--ep-font-size-sm); color: var(--ep-color-info); padding: 0 var(--ep-space-2); }\n</style>\n");
        return sb.toString();
    }

    private String detailViewSource(String moduleId, String entity, String entityVar,
                                    List<BusinessEntityField> fields, boolean dataScope,
                                    boolean permissions, String route, String title) {
        StringBuilder sb = new StringBuilder();
        sb.append("<script setup lang=\"ts\">\n");
        sb.append("// ").append(entity).append(" Detail (generated by engineering-platform Generic Module Generator)\n");
        sb.append("// EP UI 2.0 detail: overview header + structured sections + audit.\n");
        sb.append("import { computed, onMounted, ref } from 'vue';\n");
        sb.append("import { useRoute, useRouter } from 'vue-router';\n");
        sb.append("import PageHeader from '../../components/PageHeader.vue';\n");
        sb.append("import PageContainer from '../../components/PageContainer.vue';\n");
        // V06-FINAL: StatusTag only imported when this module actually renders it
        // (status field or semantic:dictionary fields) — avoids TS6133 on modules
        // without dictionary/status fields.
        if (statusField(fields) != null || hasSemantic(fields, "dictionary")) {
            sb.append("import StatusTag from '../../components/StatusTag.vue';\n");
        }
        if (permissions) sb.append("import PermissionButton from '../../permission/PermissionButton.vue';\n");
        sb.append("import { ").append(entityVar).append("Api } from '../../api/").append(moduleId).append("';\n");
        sb.append("import type { ").append(entity).append(" } from '../../types/").append(moduleId).append("';\n");
        sb.append("import { errorMessage } from '../../utils/feedback';\n\n");
        sb.append("const route = useRoute();\nconst router = useRouter();\n");
        sb.append("const row = ref<").append(entity).append(" | null>(null);\n");
        sb.append("const loading = ref(false);\nconst error = ref<string | null>(null);\nconst notFound = ref(false);\n\n");
        sb.append("const titleField = computed(() => ");
        String titleField = detailTitleField(fields);
        if (titleField != null) {
            sb.append("row.value ? String(row.value.").append(titleField).append(" ?? row.value.id) : '").append(title).append(" Detail'");
        } else {
            sb.append("row.value ? String(row.value.id) : '").append(title).append(" Detail'");
        }
        sb.append(");\n");
        sb.append("const subtitleField = computed(() => row.value ? 'ID ' + String(row.value.id) : '');\n\n");
        sb.append("async function load(): Promise<void> {\n");
        sb.append("  loading.value = true; error.value = null; notFound.value = false;\n");
        sb.append("  try { row.value = await ").append(entityVar).append("Api.detail(route.params.id as string); }\n");
        sb.append("  catch (e) { error.value = errorMessage(e); if (e instanceof Error && 'status' in e && (e as { status: number }).status === 404) { notFound.value = true; } }\n");
        sb.append("  finally { loading.value = false; }\n}\n\n");
        sb.append("function goBack(): void { router.push({ path: '").append(route).append("' }); }\n");
        sb.append("onMounted(load);\n");
        sb.append("</script>\n\n<template>\n");
        sb.append("  <PageContainer>\n");
        sb.append("    <PageHeader :title=\"titleField\" :description=\"subtitleField\" eyebrow=\"").append(entity).append("\">\n");
        sb.append("      <template #actions>\n");
        sb.append("        <el-button data-testid=\"").append(moduleId).append("-detail-back\" @click=\"goBack\">Back</el-button>\n");
        if (permissions) {
            sb.append("        <PermissionButton v-if=\"row\" permission=\"").append(moduleId.replace("-", "_")).append(":item:update\" data-testid=\"").append(moduleId).append("-detail-edit\" @click=\"router.push({ path: '").append(route).append("/' + row.id + '/edit' })\">Edit</PermissionButton>\n");
        }
        sb.append("      </template>\n    </PageHeader>\n\n");
        sb.append("    <div v-if=\"loading\" class=\"detail-state\" data-testid=\"").append(moduleId).append("-detail-loading\">Loading…</div>\n");
        sb.append("    <el-result v-else-if=\"notFound\" icon=\"warning\" title=\"").append(title).append(" not found\" sub-title=\"It may have been removed or is outside your data scope.\" data-testid=\"").append(moduleId).append("-detail-notfound\"><template #extra><el-button type=\"primary\" @click=\"goBack\">Back to list</el-button></template></el-result>\n");
        sb.append("    <el-result v-else-if=\"error\" icon=\"error\" :title=\"error\" data-testid=\"").append(moduleId).append("-detail-error\"><template #extra><el-button type=\"primary\" data-testid=\"").append(moduleId).append("-detail-retry\" @click=\"load\">Retry</el-button></template></el-result>\n");
        sb.append("    <div v-else-if=\"row\" class=\"detail\" data-testid=\"").append(moduleId).append("-detail\">\n");
        sb.append("      <section class=\"detail-section detail-overview\">\n");
        sb.append("        <h3 class=\"detail-section-title\">Overview</h3><div class=\"detail-overview-grid\">\n");
        sb.append("        <div class=\"overview-metric\"><span class=\"overview-metric-label\">Status</span><span class=\"overview-metric-value\">");
        String statusF = statusField(fields);
        if (statusF != null) {
            sb.append("<StatusTag :enabled=\"row.").append(statusF).append(" === 'ENABLED'\" active-text=\"Enabled\" inactive-text=\"Disabled\" />");
        } else {
            sb.append("—");
        }
        sb.append("</span></div>\n");
        sb.append("        <div class=\"overview-metric\"><span class=\"overview-metric-label\">Created</span><span class=\"overview-metric-value\">{{ new Date(row.createdAt).toLocaleDateString() }}</span></div>\n");
        sb.append("        <div class=\"overview-metric\"><span class=\"overview-metric-label\">Updated</span><span class=\"overview-metric-value\">{{ new Date(row.updatedAt).toLocaleDateString() }}</span></div>\n");
        sb.append("        </div></section>\n");
        sb.append("      <section class=\"detail-section\"><h3 class=\"detail-section-title\">Basic information</h3><dl class=\"detail-grid\">\n");
        boolean anyBasic = false;
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            if ("dictionary".equals(f.semantic())) continue;
            if (Boolean.FALSE.equals(f.frontend().get("detailVisible"))) continue;
            anyBasic = true;
            sb.append("        <div class=\"detail-item\"><dt>").append(labelOf(f)).append("</dt><dd data-testid=\"detail-").append(f.name()).append("\">");
            sb.append("{{ row.").append(f.name()).append(" ?? '—' }}");
            sb.append("</dd></div>\n");
        }
        if (!anyBasic) sb.append("        <div class=\"detail-item\"><dt>Record</dt><dd>—</dd></div>\n");
        sb.append("      </dl></section>\n");
        boolean anyBiz = false;
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            if (!"dictionary".equals(f.semantic())) continue;
            anyBiz = true;
            break;
        }
        if (anyBiz) {
            sb.append("      <section class=\"detail-section\"><h3 class=\"detail-section-title\">Business information</h3><dl class=\"detail-grid\">\n");
            for (BusinessEntityField f : fields) {
                if (isSystemField(f)) continue;
                if (!"dictionary".equals(f.semantic())) continue;
                if (Boolean.FALSE.equals(f.frontend().get("detailVisible"))) continue;
                sb.append("        <div class=\"detail-item\"><dt>").append(labelOf(f)).append("</dt><dd data-testid=\"detail-").append(f.name()).append("\">");
                sb.append("<StatusTag :enabled=\"row.").append(f.name()).append(" === 'ENABLED'\" active-text=\"Enabled\" inactive-text=\"Disabled\" />");
                sb.append("</dd></div>\n");
            }
            sb.append("      </dl></section>\n");
        }
        sb.append("      <section class=\"detail-section\"><h3 class=\"detail-section-title\">Audit</h3><dl class=\"detail-grid\">\n");
        if (dataScope) sb.append("        <div class=\"detail-item\"><dt>Department</dt><dd>{{ row.departmentId ?? '—' }}</dd></div>\n");
        sb.append("        <div class=\"detail-item\"><dt>Created at</dt><dd>{{ new Date(row.createdAt).toLocaleString() }}</dd></div>\n");
        sb.append("        <div class=\"detail-item\"><dt>Updated at</dt><dd>{{ new Date(row.updatedAt).toLocaleString() }}</dd></div>\n");
        sb.append("      </dl></section>\n");
        sb.append("    </div>\n  </PageContainer>\n</template>\n\n<style scoped>\n.detail-state { padding: var(--ep-space-6); color: var(--ep-color-info); }\n.detail { display: grid; gap: var(--ep-space-5); }\n.detail-section { background: var(--ep-color-surface); border-radius: var(--ep-radius-xl); box-shadow: var(--ep-shadow-sm); padding: var(--ep-space-5); }\n.detail-overview { background: linear-gradient(120deg, var(--ep-accent-indigo-soft) 0%, var(--ep-accent-sky-soft) 100%); }\n.detail-section-title { margin: 0 0 var(--ep-space-4); font-size: var(--ep-font-size-section); font-weight: var(--ep-font-weight-semibold); }\n.detail-overview-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: var(--ep-space-4); }\n.overview-metric { display: flex; flex-direction: column; gap: var(--ep-space-1); }\n.overview-metric-label { font-size: var(--ep-font-size-xs); color: var(--ep-color-text-secondary); font-weight: var(--ep-font-weight-medium); }\n.overview-metric-value { font-size: var(--ep-font-size-lg); font-weight: var(--ep-font-weight-semibold); color: var(--ep-color-text); }\n.detail-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: var(--ep-space-4); margin: 0; }\n.detail-item dt { font-size: var(--ep-font-size-sm); color: var(--ep-color-text-secondary); margin-bottom: var(--ep-space-1); }\n.detail-item dd { margin: 0; font-size: var(--ep-font-size-base); }\n</style>\n");
        return sb.toString();
    }

    private String editViewSource(String moduleId, String entity, String entityVar,
                                  List<BusinessEntityField> fields, boolean permissions,
                                  String route, String title) {
        StringBuilder sb = new StringBuilder();
        sb.append("<script setup lang=\"ts\">\n");
        sb.append("// ").append(entity).append(" Edit (generated by engineering-platform Generic Module Generator)\n");
        sb.append("// EP UI 2.0 edit: white form card + consistent action area.\n");
        sb.append("import { onMounted, reactive, ref } from 'vue';\n");
        sb.append("import { useRoute, useRouter } from 'vue-router';\n");
        sb.append("import PageHeader from '../../components/PageHeader.vue';\n");
        sb.append("import PageContainer from '../../components/PageContainer.vue';\n");
        sb.append("import AppForm from '../../components/AppForm.vue';\n");
        // V06-FINAL: DictionarySelect only imported when dictionary fields exist.
        if (hasSemantic(fields, "dictionary")) {
            sb.append("import DictionarySelect from '../../components/DictionarySelect.vue';\n");
        }
        sb.append("import { ").append(entityVar).append("Api } from '../../api/").append(moduleId).append("';\n");
        sb.append("import type { ").append(entity).append(" } from '../../types/").append(moduleId).append("';\n");
        sb.append("import { errorMessage, notifySuccess } from '../../utils/feedback';\n\n");
        sb.append("const route = useRoute();\nconst router = useRouter();\n");
        sb.append("const row = ref<").append(entity).append(" | null>(null);\n");
        sb.append("const loading = ref(false);\nconst error = ref<string | null>(null);\nconst notFound = ref(false);\n");
        sb.append("const submitting = ref(false);\nconst formError = ref<string | null>(null);\n");
        sb.append("const form = reactive({");
        boolean first = true;
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            if (!first) sb.append(", ");
            first = false;
            sb.append(f.name()).append(": ").append(tsDefault(f));
        }
        sb.append(" });\n\n");
        sb.append("async function load(): Promise<void> {\n");
        sb.append("  loading.value = true; error.value = null; notFound.value = false;\n");
        sb.append("  try { const p = await ").append(entityVar).append("Api.detail(route.params.id as string); row.value = p; Object.assign(form, {");
        first = true;
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            if (!first) sb.append(", ");
            first = false;
            sb.append(f.name()).append(": p.").append(f.name());
        }
        sb.append(" }); }\n");
        sb.append("  catch (e) { error.value = errorMessage(e); if (e instanceof Error && 'status' in e && (e as { status: number }).status === 404) { notFound.value = true; } }\n");
        sb.append("  finally { loading.value = false; }\n}\n\n");
        sb.append("async function submit(): Promise<void> {\n");
        sb.append("  if (!row.value) return;\n  submitting.value = true; formError.value = null;\n");
        sb.append("  try { await ").append(entityVar).append("Api.update(row.value.id, {");
        first = true;
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            if (!first) sb.append(", ");
            first = false;
            sb.append(f.name()).append(": form.").append(f.name());
        }
        sb.append(" }); notifySuccess('").append(title).append(" updated'); router.push({ path: '").append(route).append("/' + row.value.id }); }\n");
        sb.append("  catch (e) { formError.value = errorMessage(e); } finally { submitting.value = false; }\n}\n\n");
        sb.append("onMounted(load);\n");
        sb.append("</script>\n\n<template>\n");
        sb.append("  <PageContainer>\n");
        sb.append("    <PageHeader title=\"Edit ").append(title).append("\" :description=\"row ? String(row.id) : undefined\" eyebrow=\"").append(entity).append("\">\n");
        sb.append("      <template #actions><el-button data-testid=\"").append(moduleId).append("-edit-cancel\" @click=\"router.push({ path: '").append(route).append("' })\">Cancel</el-button></template>\n");
        sb.append("    </PageHeader>\n\n");
        sb.append("    <div v-if=\"loading\" class=\"edit-state\" data-testid=\"").append(moduleId).append("-edit-loading\">Loading…</div>\n");
        sb.append("    <el-result v-else-if=\"notFound\" icon=\"warning\" title=\"").append(title).append(" not found\" sub-title=\"It may have been removed or is outside your data scope.\" data-testid=\"").append(moduleId).append("-edit-notfound\" />\n");
        sb.append("    <el-result v-else-if=\"error\" icon=\"error\" :title=\"error\" data-testid=\"").append(moduleId).append("-edit-error\" />\n");
        sb.append("    <div v-else-if=\"row\" class=\"edit\" data-testid=\"").append(moduleId).append("-edit\">\n");
        sb.append("      <AppForm :model=\"form as unknown as Record<string, unknown>\" :submitting=\"submitting\" :error=\"formError\" submit-text=\"Save\" two-column @submit=\"submit\" @cancel=\"router.push({ path: '").append(route).append("/' + row.id })\">\n");
        // Section 1: Basic information (non-dictionary editable fields)
        boolean anyBasic = false;
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            if ("dictionary".equals(f.semantic())) continue;
            anyBasic = true;
            sb.append("        <el-form-item label=\"").append(labelOf(f)).append("\"");
            if (f.required()) sb.append(" :rules=\"[{ required: true, message: '").append(labelOf(f)).append(" is required' }]\"");
            sb.append(">\n");
            if ("boolean".equals(f.type())) {
                sb.append("          <el-switch v-model=\"form.").append(f.name()).append("\" data-testid=\"").append(moduleId).append("-edit-").append(f.name()).append("\" />\n");
            } else {
                sb.append("          <el-input v-model=\"form.").append(f.name()).append("\" data-testid=\"").append(moduleId).append("-edit-").append(f.name()).append("\" />\n");
            }
            sb.append("        </el-form-item>\n");
        }
        if (!anyBasic) {
            sb.append("        <el-form-item label=\"Record\"><el-input disabled model-value=\"—\" /></el-form-item>\n");
        }
        // Section 2: Business information (dictionary fields)
        boolean anyBiz = false;
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            if (!"dictionary".equals(f.semantic())) continue;
            anyBiz = true;
            sb.append("        <el-form-item label=\"").append(labelOf(f)).append("\"");
            if (f.required()) sb.append(" :rules=\"[{ required: true, message: '").append(labelOf(f)).append(" is required' }]\"");
            sb.append(">\n");
            sb.append("          <DictionarySelect v-model=\"form.").append(f.name()).append("\" code=\"").append(f.dictionary()).append("\" style=\"width: 100%\" data-testid=\"").append(moduleId).append("-edit-").append(f.name()).append("\" />\n");
            sb.append("        </el-form-item>\n");
        }
        sb.append("        <div class=\"edit-meta\"><span>Ownership is server-managed and cannot be changed here.</span></div>\n");
        sb.append("      </AppForm>\n");
        sb.append("    </div>\n  </PageContainer>\n</template>\n\n<style scoped>\n.edit-state { padding: var(--ep-space-6); color: var(--ep-color-info); }\n.edit { max-width: 860px; }\n.edit-meta { font-size: var(--ep-font-size-sm); color: var(--ep-color-info); padding: 0 var(--ep-space-2); }\n</style>\n");
        return sb.toString();
    }

    private String apiSpecSource(String moduleId, String entity, List<BusinessEntityField> fields, String table, boolean dataScope) {
        String entityVar = decapitalize(entity);
        StringBuilder sample = new StringBuilder();
        sample.append("{ id: '1'");
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            sample.append(", ").append(f.name()).append(": ").append(tsSample(f));
        }
        if (dataScope) sample.append(", departmentId: '1'");
        sample.append(", createdBy: '1', createdAt: '2026-08-16T00:00:00', updatedAt: '2026-08-16T00:00:00' }");
        StringBuilder sb = new StringBuilder();
        sb.append("// ").append(entity).append(" API service tests (generated by engineering-platform Generic Module Generator)\n");
        sb.append("import { describe, it, expect, vi, beforeEach } from 'vitest';\n");
        sb.append("import { http } from '../src/api/request';\n");
        sb.append("import { ").append(entityVar).append("Api } from '../src/api/").append(moduleId).append("';\n");
        sb.append("import type { ").append(entity).append(" } from '../src/types/").append(moduleId).append("';\n\n");
        sb.append("const row: ").append(entity).append(" = ").append(sample).append(";\n\n");
        sb.append("describe('").append(entityVar).append("Api', () => {\n");
        sb.append("  beforeEach(() => { vi.restoreAllMocks(); });\n\n");
        sb.append("  it('page builds query string', async () => {\n");
        sb.append("    const spy = vi.spyOn(http, 'get').mockResolvedValue({ items: [row], total: 1, page: 1, size: 20 });\n");
        sb.append("    await ").append(entityVar).append("Api.page({ page: 1, size: 20, keyword: 'x' });\n");
        sb.append("    const [path] = spy.mock.calls[0] as [string];\n");
        sb.append("    expect(path).toContain('page=1');\n");
        sb.append("    expect(path).toContain('keyword=x');\n  });\n\n");
        sb.append("  it('detail/create/update/disable route to the right paths', async () => {\n");
        sb.append("    const get = vi.spyOn(http, 'get').mockResolvedValue(row);\n");
        sb.append("    const post = vi.spyOn(http, 'post').mockResolvedValue(row);\n");
        sb.append("    const put = vi.spyOn(http, 'put').mockResolvedValue(row);\n");
        sb.append("    await ").append(entityVar).append("Api.detail('5');\n");
        sb.append("    expect((get.mock.calls[0] as [string])[0]).toBe('/").append(table).append("/5');\n");
        sb.append("    await ").append(entityVar).append("Api.create({ id: '0' } as never);\n");
        sb.append("    expect((post.mock.calls[0] as [string])[0]).toBe('/").append(table).append("');\n");
        sb.append("    await ").append(entityVar).append("Api.update('5', { id: '0' } as never);\n");
        sb.append("    expect((put.mock.calls[0] as [string])[0]).toBe('/").append(table).append("/5');\n");
        sb.append("    await ").append(entityVar).append("Api.disable('5');\n");
        sb.append("    expect((post.mock.calls[1] as [string])[0]).toBe('/").append(table).append("/5/disable');\n");
        sb.append("  });\n");
        sb.append("});\n");
        return sb.toString();
    }

    private String routeSpecSource(String moduleId, String entity, String route, String table) {
        String entityVar = decapitalize(entity);
        StringBuilder sb = new StringBuilder();
        sb.append("// ").append(entity).append(" route registration (generated by engineering-platform Generic Module Generator)\n");
        sb.append("// Route module must be picked up by the frontend-auth router via business/*.ts glob.\n");
        sb.append("import { describe, it, expect } from 'vitest';\n");
        sb.append("import { businessRoutes } from '../src/router/business/").append(moduleId).append("';\n\n");
        sb.append("describe('").append(moduleId).append(" routes', () => {\n");
        sb.append("  it('registers list/detail/edit routes with permission meta', () => {\n");
        sb.append("    const paths = businessRoutes.map((r) => r.path);\n");
        sb.append("    expect(paths).toContain('").append(route).append("');\n");
        sb.append("    const list = businessRoutes.find((r) => r.path === '").append(route).append("')!;\n");
        sb.append("    expect(list.meta).toMatchObject({ permission: '").append(table).append(":item:read' });\n");
        sb.append("  });\n\n");
        sb.append("  it('routes are static imports (no dynamic component from backend path)', () => {\n");
        sb.append("    for (const r of businessRoutes) { expect(typeof r.component).toBe('function'); }\n");
        sb.append("  });\n");
        sb.append("});\n");
        return sb.toString();
    }

    private String listSpecSource(String moduleId, String entity, List<BusinessEntityField> fields,
                                  String table, String title, boolean dataScope) {
        String entityVar = decapitalize(entity);
        StringBuilder sample = new StringBuilder();
        sample.append("{ id: '1'");
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            sample.append(", ").append(f.name()).append(": ").append(tsSample(f));
        }
        if (dataScope) sample.append(", departmentId: '1'");
        sample.append(", createdBy: '1', createdAt: '2026-08-16T00:00:00', updatedAt: '2026-08-16T00:00:00' }");
        StringBuilder sb = new StringBuilder();
        sb.append("// ").append(entity).append(" List view tests (generated by engineering-platform Generic Module Generator)\n");
        sb.append("import { describe, it, expect, vi, beforeEach } from 'vitest';\n");
        sb.append("import { mount, flushPromises } from '@vue/test-utils';\n");
        sb.append("import { createPinia, setActivePinia } from 'pinia';\n");
        sb.append("import { useAuthStore } from '../src/stores/auth';\n");
        sb.append("import ").append(entity).append("ListView from '../src/views/").append(moduleId.replace("-", "")).append("/").append(entity).append("ListView.vue';\n");
        sb.append("import { ").append(entityVar).append("Api } from '../src/api/").append(moduleId).append("';\n");
        sb.append("import { dictionaryApi } from '../src/api/enterprise';\n");
        sb.append("import type { ").append(entity).append(" } from '../src/types/").append(moduleId).append("';\n");
        sb.append("import { epStubs, platformStubs } from './stubs';\n\n");
        sb.append("const stubs = { ...epStubs(), ...platformStubs() };\n\n");
        sb.append("const rows: ").append(entity).append("[] = [ ").append(sample).append(" ];\n\n");
        sb.append("function seed(permissions: string[]): void {\n");
        sb.append("  const pinia = createPinia();\n  setActivePinia(pinia);\n");
        sb.append("  const auth = useAuthStore(pinia);\n");
        sb.append("  auth.$patch({ currentUser: { id: '1', username: 'u', departmentId: null, permissions } });\n");
        sb.append("  localStorage.clear();\n}\n\n");
        sb.append("function mockApis(): void {\n");
        sb.append("  vi.spyOn(").append(entityVar).append("Api, 'page').mockResolvedValue({ items: rows, total: 1, page: 1, size: 20 });\n");
        sb.append("  vi.spyOn(dictionaryApi, 'itemsByCode').mockResolvedValue([]);\n}\n\n");
        sb.append("describe('").append(entity).append("ListView', () => {\n");
        sb.append("  beforeEach(() => { vi.restoreAllMocks(); });\n\n");
        sb.append("  it('loads rows via the API', async () => {\n");
        sb.append("    seed(['").append(table).append(":item:read']);\n");
        sb.append("    mockApis();\n");
        sb.append("    await mount(").append(entity).append("ListView, { global: { stubs } });\n");
        sb.append("    await flushPromises();\n");
        sb.append("    expect(").append(entityVar).append("Api.page).toHaveBeenCalled();\n  });\n\n");
        sb.append("  it('shows error state when list fails (no white screen)', async () => {\n");
        sb.append("    seed(['").append(table).append(":item:read']);\n");
        sb.append("    vi.spyOn(").append(entityVar).append("Api, 'page').mockRejectedValue(new Error('boom'));\n");
        sb.append("    vi.spyOn(dictionaryApi, 'itemsByCode').mockResolvedValue([]);\n");
        sb.append("    const wrapper = await mount(").append(entity).append("ListView, { global: { stubs } });\n");
        sb.append("    await flushPromises();\n");
        sb.append("    expect(wrapper.html().length).toBeGreaterThan(0);\n  });\n");
        sb.append("});\n");
        return sb.toString();
    }

    private String detailSpecSource(String moduleId, String entity, String table, String title) {
        String entityVar = decapitalize(entity);
        StringBuilder sb = new StringBuilder();
        sb.append("// ").append(entity).append(" Detail view tests (generated by engineering-platform Generic Module Generator)\n");
        sb.append("import { describe, it, expect, vi, beforeEach } from 'vitest';\n");
        sb.append("import { mount, flushPromises } from '@vue/test-utils';\n");
        sb.append("import { createPinia, setActivePinia } from 'pinia';\n");
        sb.append("import { useAuthStore } from '../src/stores/auth';\n");
        sb.append("import ").append(entity).append("DetailView from '../src/views/").append(moduleId.replace("-", "")).append("/").append(entity).append("DetailView.vue';\n");
        sb.append("import { ").append(entityVar).append("Api } from '../src/api/").append(moduleId).append("';\n");
        sb.append("import { epStubs, platformStubs } from './stubs';\n\n");
        sb.append("const stubs = { ...epStubs(), ...platformStubs() };\n\n");
        sb.append("function seed(permissions: string[]): void {\n");
        sb.append("  const pinia = createPinia();\n  setActivePinia(pinia);\n");
        sb.append("  const auth = useAuthStore(pinia);\n");
        sb.append("  auth.$patch({ currentUser: { id: '1', username: 'u', departmentId: null, permissions } });\n");
        sb.append("  localStorage.clear();\n}\n\n");
        sb.append("describe('").append(entity).append("DetailView', () => {\n");
        sb.append("  beforeEach(() => { vi.restoreAllMocks(); });\n\n");
        sb.append("  it('renders not-found state for a missing row (no white screen)', async () => {\n");
        sb.append("    seed(['").append(table).append(":item:read']);\n");
        sb.append("    vi.spyOn(").append(entityVar).append("Api, 'detail').mockRejectedValue(Object.assign(new Error('404'), { status: 404 }));\n");
        sb.append("    const wrapper = await mount(").append(entity).append("DetailView, {\n");
        sb.append("      global: { stubs, mocks: { $route: { params: { id: '999' } } } },\n");
        sb.append("    });\n");
        sb.append("    await flushPromises();\n");
        sb.append("    expect(wrapper.html().length).toBeGreaterThan(0);\n  });\n");
        sb.append("});\n");
        return sb.toString();
    }

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------


    // ---- frontend helpers (V06-WORK-003: split out of GenericModuleGenerator) ----

    private static String frontendRoute(ResolvedBusinessModule module) {
        Object route = module.frontend().get("route");
        if (route != null) return String.valueOf(route);
        return "/" + module.id().replace("-", "");
    }

    private static boolean bool(Map<String, Object> map, String key) {
        return Boolean.TRUE.equals(map.get(key));
    }

    private static String str(Map<String, Object> map, String key, String dflt) {
        Object v = map.get(key);
        return v == null ? dflt : String.valueOf(v);
    }

    private static boolean isSystemField(BusinessEntityField f) {
        return f.semantic() != null && ("system".equals(f.semantic()) || "ownership".equals(f.semantic())
                || "currentUser".equals(f.semantic()));
    }

    private static String tsType(BusinessEntityField f) {
        return switch (f.type() == null ? "string" : f.type()) {
            case "integer", "number", "decimal" -> "number";
            case "boolean" -> "boolean";
            default -> "string";
        };
    }

    private static String tsDefault(BusinessEntityField f) {
        return switch (f.type() == null ? "string" : f.type()) {
            case "boolean" -> "false";
            case "integer" -> "0";
            default -> "''";
        };
    }

    private static String tsSample(BusinessEntityField f) {
        return switch (f.type() == null ? "string" : f.type()) {
            case "boolean" -> "true";
            case "integer" -> "1";
            default -> "'v'";
        };
    }

    private static boolean hasType(List<BusinessEntityField> fields, String type) {
        return fields.stream().anyMatch(f -> type.equals(f.type()));
    }

    private static boolean hasSemantic(List<BusinessEntityField> fields, String semantic) {
        return fields.stream().anyMatch(f -> semantic.equals(f.semantic()));
    }

    private static String statusField(List<BusinessEntityField> fields) {
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            if ("status".equals(f.name()) || "state".equals(f.name())) return f.name();
        }
        return null;
    }

    /** First meaningful display field for detail header (name/code/title-like). */
    private static String detailTitleField(List<BusinessEntityField> fields) {
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            if ("dictionary".equals(f.semantic())) continue;
            String n = f.name();
            if ("name".equals(n) || "code".equals(n) || "title".equals(n) || "label".equals(n)) return n;
        }
        for (BusinessEntityField f : fields) {
            if (isSystemField(f)) continue;
            if ("dictionary".equals(f.semantic())) continue;
            return f.name();
        }
        return null;
    }

    private static String labelOf(BusinessEntityField f) {
        Object label = f.frontend().get("label");
        return label == null ? capitalize(f.name()) : String.valueOf(label);
    }

    private static String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    private static String decapitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toLowerCase(s.charAt(0)) + s.substring(1);
    }

    private static String upper(String s) {
        return s.replaceAll("([a-z])([A-Z])", "$1_$2").toUpperCase(java.util.Locale.ROOT);
    }
}
