package com.engineeringplatform.generator.core;

import com.engineeringplatform.generator.contracts.BusinessEntityField;
import com.engineeringplatform.generator.contracts.ResolvedBusinessModule;
import com.engineeringplatform.generator.contracts.ResolvedRelation;

import java.util.List;
import java.util.Map;

/**
 * V07-WORK-002 — Master/Detail backend rendering.
 *
 * Renders the master-detail semantics of composition ONE_TO_MANY relations on
 * top of the existing GenericModuleGenerator output:
 *   - master DTOs carry {@code items[]} (never the persistence entity)
 *   - create runs in ONE transaction (validate refs -> insert parent ->
 *     insert children -> rollback all on failure)
 *   - detail returns parent + items
 *   - update reconciliation is deterministic (existing+present -> update,
 *     existing+missing -> delete, new -> insert; never DELETE ALL -> INSERT ALL)
 *   - composition children get a scoped findByParent + deleteById (physical
 *     delete LIMITED to composition children — no general cascade engine)
 *
 * This renderer produces CODE FRAGMENTS for GenericModuleGenerator; it is not
 * a second generator/executor.
 */
public final class MasterDetailBackendRenderer {

    /** True when the module is a master: has a composition ONE_TO_MANY relation. */
    public static boolean isMaster(ResolvedBusinessModule module) {
        return compositionOneToMany(module) != null;
    }

    /** The composition ONE_TO_MANY relation of a master module, or null. */
    public static ResolvedRelation compositionOneToMany(ResolvedBusinessModule module) {
        for (ResolvedRelation r : module.relations()) {
            if ("ONE_TO_MANY".equals(r.type()) && r.composition()) {
                return r;
            }
        }
        return null;
    }

    /** The ONE_TO_MANY relation declaring this module as composition child, or null. */
    public static ResolvedRelation childOf(ResolvedBusinessModule module, List<ResolvedBusinessModule> allModules) {
        for (ResolvedBusinessModule m : allModules) {
            if (m == module) continue;
            for (ResolvedRelation r : m.relations()) {
                if ("ONE_TO_MANY".equals(r.type()) && r.composition() && r.target().equals(module.id())) {
                    return r;
                }
            }
        }
        return null;
    }

    /**
     * ItemInput record for a composition child (used in master items[]).
     * Carries an optional id (null = new child on update) + all non-system
     * fields except the parent FK field (set by the master Service).
     */
    public String itemInputSource(ResolvedBusinessModule master, ResolvedBusinessModule child,
                                  ResolvedRelation relation, String pkg) {
        String childEntity = child.entity().name();
        String modPkg = child.id().replace("-", "");
        StringBuilder params = new StringBuilder();
        boolean first = true;
        for (BusinessEntityField f : child.entity().fields()) {
            if (GenericModuleGenerator.isSystemField(f)) continue;
            if (f.name().equals(relation.mappedBy())) continue; // parent FK owned by master Service
            if (!first) params.append(",\n        ");
            first = false;
            params.append(javaType(f)).append(" ").append(f.name());
        }
        String req = params.length() == 0 ? "" : ",\n        " + params;
        return "package " + pkg + ".application." + modPkg + ";\n\n"
                + "/**\n * " + childEntity + " item input (generated by engineering-platform Generic Module Generator).\n"
                + " * Used inside " + master.entity().name() + " create/update items[] — the parent FK is set by the master Service.\n */\n"
                + "public record " + childEntity + "ItemInput(\n        Long id" + req + ") {\n}\n";
    }

    /**
     * The extra Port methods a composition child needs for master
     * reconciliation: findByParent + deleteById (physical delete limited to
     * composition children).
     */
    public String childPortMethods(ResolvedBusinessModule child, ResolvedRelation parentRelation) {
        String entity = child.entity().name();
        String parentField = parentRelation.mappedBy();
        String parentFieldCap = GenericModuleGenerator.capitalize(parentField);
        return "    List<" + entity + "> findBy" + parentFieldCap + "(Long " + parentField + ");\n\n"
                + "    void deleteById(Long id);\n";
    }

    /** Repository implementation of the child findByParent + deleteById. */
    public String childRepositoryMethods(ResolvedBusinessModule child, ResolvedRelation parentRelation,
                                         String entityVar, String table) {
        String entity = child.entity().name();
        String parentField = parentRelation.mappedBy();
        String parentFieldCap = GenericModuleGenerator.capitalize(parentField);
        return "    @Override\n    public List<" + entity + "> findBy" + parentFieldCap + "(Long " + parentField + ") {\n"
                + "        QueryWrapper<" + entity + "> wrapper = new QueryWrapper<>();\n"
                + "        wrapper.eq(\"" + snake(parentField) + "\", " + parentField + ");\n"
                + "        wrapper.orderByAsc(\"id\");\n"
                + "        return " + entityVar + "Mapper.selectList(wrapper);\n    }\n\n"
                + "    @Override\n    public void deleteById(Long id) {\n"
                + "        " + entityVar + "Mapper.deleteById(id);\n    }\n";
    }

    /**
     * ONE_TO_ONE / MANY_TO_ONE relation on THIS module with a localField:
     * rendered as an FK + reference-existence validation (target-exists on
     * write), mirroring semantic=reference handling.
     */
    public static ResolvedRelation owningRelation(ResolvedBusinessModule module) {
        for (ResolvedRelation r : module.relations()) {
            if (("MANY_TO_ONE".equals(r.type()) || "ONE_TO_ONE".equals(r.type()))
                    && r.localField() != null && !r.localField().isBlank()) {
                return r;
            }
        }
        return null;
    }

    private static String javaType(BusinessEntityField f) {
        return switch (f.type() == null ? "string" : f.type()) {
            case "integer", "long" -> "Long";
            case "number", "decimal", "money" -> "java.math.BigDecimal";
            case "boolean" -> "Boolean";
            case "date" -> "java.time.LocalDate";
            case "datetime" -> "java.time.LocalDateTime";
            default -> "String";
        };
    }
    /** camelCase → snake_case (MyBatis-Plus default column-underline mapping). */
    private static String snake(String s) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (Character.isUpperCase(c)) {
                if (i > 0) sb.append('_');
                sb.append(Character.toLowerCase(c));
            } else {
                sb.append(c);
            }
        }
        return sb.toString();
    }

}
