<?xml version="1.0" encoding="UTF-8"?>
<!-- Logging baseline (generated by engineering-platform ${asset.version}) -->
<configuration>
    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="${logging.level.root!'INFO'}">
        <appender-ref ref="CONSOLE"/>
    </root>
</configuration>
