package ${package}.api.dictionary;

import ${package}.application.dictionary.DictionaryItemDto;
import ${package}.application.dictionary.DictionaryService;
import ${package}.common.core.ApiResponse;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * Dictionary API (generated by engineering-platform ${asset.version}).
 * GET /api/dictionaries/{code}/items returns enabled items with stable ordering.
 */
@RestController
@RequestMapping("/api/dictionaries")
public class DictionaryController {

    private final DictionaryService dictionaryService;

    public DictionaryController(DictionaryService dictionaryService) {
        this.dictionaryService = dictionaryService;
    }

    @GetMapping("/{code}/items")
    public ApiResponse<List<DictionaryItemDto>> items(@PathVariable String code) {
        return ApiResponse.ofSuccess(dictionaryService.itemsOf(code));
    }
}
