package ${package}.application.dictionary;

import ${package}.common.core.ErrorCode;
import ${package}.common.core.PlatformException;
import ${package}.domain.entity.DictionaryItem;
import ${package}.domain.entity.DictionaryType;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * Dictionary management application service (generated by engineering-platform ${asset.version}).
 *
 * Orchestration, business validation and transaction boundaries live here, in
 * the application layer. Persistence goes through {@link DictionaryManagementPort} —
 * no MyBatis types appear in this class.
 *
 * Type + Item create/update/enable/disable/sort. Stable codes: type.code is
 * immutable once created (business references like product_status stay valid);
 * only label/name/description/enabled are updatable.
 */
public class DictionaryManagementService {

    private final DictionaryManagementPort managementPort;

    public DictionaryManagementService(DictionaryManagementPort managementPort) {
        this.managementPort = managementPort;
    }

    // ---- type ------------------------------------------------------------

    public List<DictionaryType> types() {
        return managementPort.findAllTypes();
    }

    public DictionaryType typeDetail(Long id) {
        Optional<DictionaryType> type = managementPort.findTypeById(id);
        if (type.isEmpty()) {
            throw new PlatformException(ErrorCode.of("DICTIONARY_TYPE_NOT_FOUND",
                    "dictionary type not found: " + id));
        }
        return type.get();
    }

    @Transactional
    public DictionaryType createType(String code, String name, String description) {
        if (code == null || code.isBlank()) {
            throw new PlatformException(ErrorCode.of("DICTIONARY_TYPE_CODE_REQUIRED",
                    "dictionary type code is required"));
        }
        String normalizedCode = code.trim();
        if (managementPort.findTypeByCode(normalizedCode).isPresent()) {
            throw new PlatformException(ErrorCode.of("DICTIONARY_TYPE_CODE_DUPLICATE",
                    "dictionary type code already exists: " + normalizedCode));
        }
        DictionaryType type = new DictionaryType();
        type.setCode(normalizedCode);
        type.setName(name == null || name.isBlank() ? normalizedCode : name.trim());
        type.setEnabled(true);
        type.setDescription(description);
        LocalDateTime now = LocalDateTime.now();
        type.setCreatedAt(now);
        type.setUpdatedAt(now);
        managementPort.insertType(type);
        return type;
    }

    @Transactional
    public DictionaryType updateType(Long id, String name, String description) {
        DictionaryType type = requireType(id);
        // code immutable (stable code governance)
        if (name != null && !name.isBlank()) {
            type.setName(name.trim());
        }
        if (description != null) {
            type.setDescription(description);
        }
        type.setUpdatedAt(LocalDateTime.now());
        managementPort.updateType(type);
        return type;
    }

    @Transactional
    public DictionaryType setTypeEnabled(Long id, boolean enabled) {
        DictionaryType type = requireType(id);
        type.setEnabled(enabled);
        type.setUpdatedAt(LocalDateTime.now());
        managementPort.updateType(type);
        return type;
    }

    // ---- item ------------------------------------------------------------

    public List<DictionaryItem> itemsOfType(Long typeId) {
        requireType(typeId);
        return managementPort.findItemsByTypeId(typeId);
    }

    @Transactional
    public DictionaryItem createItem(Long typeId, String value, String label, Integer sort,
                                     String description) {
        requireType(typeId);
        if (value == null || value.isBlank()) {
            throw new PlatformException(ErrorCode.of("DICTIONARY_ITEM_VALUE_REQUIRED",
                    "dictionary item value is required"));
        }
        String normalizedValue = value.trim();
        if (managementPort.countItemsByTypeAndValue(typeId, normalizedValue) > 0) {
            throw new PlatformException(ErrorCode.of("DICTIONARY_ITEM_DUPLICATE",
                    "dictionary item value already exists: " + normalizedValue));
        }
        DictionaryItem item = new DictionaryItem();
        item.setTypeId(typeId);
        item.setValue(normalizedValue);
        item.setLabel(label == null || label.isBlank() ? normalizedValue : label.trim());
        item.setEnabled(true);
        item.setSort(sort == null ? 0 : sort);
        item.setDescription(description);
        LocalDateTime now = LocalDateTime.now();
        item.setCreatedAt(now);
        item.setUpdatedAt(now);
        managementPort.insertItem(item);
        return item;
    }

    @Transactional
    public DictionaryItem updateItem(Long id, String label, Integer sort, String description) {
        DictionaryItem item = requireItem(id);
        // value immutable (stable)
        if (label != null && !label.isBlank()) {
            item.setLabel(label.trim());
        }
        if (sort != null) {
            item.setSort(sort);
        }
        if (description != null) {
            item.setDescription(description);
        }
        item.setUpdatedAt(LocalDateTime.now());
        managementPort.updateItem(item);
        return item;
    }

    @Transactional
    public DictionaryItem setItemEnabled(Long id, boolean enabled) {
        DictionaryItem item = requireItem(id);
        item.setEnabled(enabled);
        item.setUpdatedAt(LocalDateTime.now());
        managementPort.updateItem(item);
        return item;
    }

    // ---- helpers ------------------------------------------------------------

    private DictionaryType requireType(Long id) {
        Optional<DictionaryType> type = managementPort.findTypeById(id);
        if (type.isEmpty()) {
            throw new PlatformException(ErrorCode.of("DICTIONARY_TYPE_NOT_FOUND",
                    "dictionary type not found: " + id));
        }
        return type.get();
    }

    private DictionaryItem requireItem(Long id) {
        Optional<DictionaryItem> item = managementPort.findItemById(id);
        if (item.isEmpty()) {
            throw new PlatformException(ErrorCode.of("DICTIONARY_ITEM_NOT_FOUND",
                    "dictionary item not found: " + id));
        }
        return item.get();
    }
}
