package ${package}.application.dictionary;

/**
 * Dictionary item DTO (generated by engineering-platform ${asset.version}).
 * API payload — never exposes the DictionaryItem entity directly.
 */
public record DictionaryItemDto(String value, String label, Integer sort, String description) {
}
