package ${package}.api.dictionary;

import ${package}.application.dictionary.DictionaryManagementService;
import ${package}.application.dictionary.DictionaryItemDto;
import ${package}.application.dictionary.DictionaryService;
import ${package}.common.core.ApiResponse;
import ${package}.common.security.OperationLog;
import ${package}.common.security.RequirePermission;
import ${package}.domain.entity.DictionaryItem;
import ${package}.domain.entity.DictionaryType;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;
import java.util.Map;

/**
 * Dictionary management API (generated by engineering-platform ${asset.version}).
 * Read endpoints stay public/read (existing contract); management writes are
 * permission-protected. Type code and item value are immutable once created
 * (stable codes like product_status must not break).
 */
@RestController
@RequestMapping("/api/dictionaries")
public class DictionaryManagementController {

    private final DictionaryManagementService managementService;
    private final DictionaryService dictionaryService;

    public DictionaryManagementController(DictionaryManagementService managementService,
                                          DictionaryService dictionaryService) {
        this.managementService = managementService;
        this.dictionaryService = dictionaryService;
    }

    // existing public read contract
    @GetMapping("/{code}/items")
    public ApiResponse<List<DictionaryItemDto>> items(@PathVariable String code) {
        return ApiResponse.ofSuccess(dictionaryService.itemsOf(code));
    }

    @GetMapping("/types")
    @RequirePermission("system:dictionary:read")
    public ApiResponse<List<DictionaryType>> types() {
        return ApiResponse.ofSuccess(managementService.types());
    }

    @GetMapping("/types/{id}")
    @RequirePermission("system:dictionary:read")
    public ApiResponse<DictionaryType> typeDetail(@PathVariable Long id) {
        return ApiResponse.ofSuccess(managementService.typeDetail(id));
    }

    @GetMapping("/types/{id}/items")
    @RequirePermission("system:dictionary:read")
    public ApiResponse<List<DictionaryItem>> typeItems(@PathVariable Long id) {
        return ApiResponse.ofSuccess(managementService.itemsOfType(id));
    }

    @PostMapping("/types")
    @RequirePermission("system:dictionary:create")
    @OperationLog(operation = "DICTIONARY_TYPE_CREATE", resourceType = "DICTIONARY")
    public ApiResponse<DictionaryType> createType(@RequestBody Map<String, Object> body) {
        return ApiResponse.ofSuccess(managementService.createType(
                str(body.get("code")), str(body.get("name")), str(body.get("description"))));
    }

    @PutMapping("/types/{id}")
    @RequirePermission("system:dictionary:update")
    @OperationLog(operation = "DICTIONARY_TYPE_UPDATE", resourceType = "DICTIONARY")
    public ApiResponse<DictionaryType> updateType(@PathVariable Long id,
                                                  @RequestBody Map<String, Object> body) {
        return ApiResponse.ofSuccess(managementService.updateType(
                id, str(body.get("name")), str(body.get("description"))));
    }

    @PostMapping("/types/{id}/enable")
    @RequirePermission("system:dictionary:update")
    @OperationLog(operation = "DICTIONARY_TYPE_ENABLE", resourceType = "DICTIONARY")
    public ApiResponse<DictionaryType> enableType(@PathVariable Long id) {
        return ApiResponse.ofSuccess(managementService.setTypeEnabled(id, true));
    }

    @PostMapping("/types/{id}/disable")
    @RequirePermission("system:dictionary:disable")
    @OperationLog(operation = "DICTIONARY_TYPE_DISABLE", resourceType = "DICTIONARY")
    public ApiResponse<DictionaryType> disableType(@PathVariable Long id) {
        return ApiResponse.ofSuccess(managementService.setTypeEnabled(id, false));
    }

    @PostMapping("/types/{id}/items")
    @RequirePermission("system:dictionary:create")
    @OperationLog(operation = "DICTIONARY_ITEM_CREATE", resourceType = "DICTIONARY")
    public ApiResponse<DictionaryItem> createItem(@PathVariable Long id,
                                                  @RequestBody Map<String, Object> body) {
        return ApiResponse.ofSuccess(managementService.createItem(id,
                str(body.get("value")), str(body.get("label")),
                intOrNull(body.get("sort")), str(body.get("description"))));
    }

    @PutMapping("/items/{itemId}")
    @RequirePermission("system:dictionary:update")
    @OperationLog(operation = "DICTIONARY_ITEM_UPDATE", resourceType = "DICTIONARY")
    public ApiResponse<DictionaryItem> updateItem(@PathVariable Long itemId,
                                                  @RequestBody Map<String, Object> body) {
        return ApiResponse.ofSuccess(managementService.updateItem(itemId,
                str(body.get("label")), intOrNull(body.get("sort")), str(body.get("description"))));
    }

    @PostMapping("/items/{itemId}/enable")
    @RequirePermission("system:dictionary:update")
    @OperationLog(operation = "DICTIONARY_ITEM_ENABLE", resourceType = "DICTIONARY")
    public ApiResponse<DictionaryItem> enableItem(@PathVariable Long itemId) {
        return ApiResponse.ofSuccess(managementService.setItemEnabled(itemId, true));
    }

    @PostMapping("/items/{itemId}/disable")
    @RequirePermission("system:dictionary:disable")
    @OperationLog(operation = "DICTIONARY_ITEM_DISABLE", resourceType = "DICTIONARY")
    public ApiResponse<DictionaryItem> disableItem(@PathVariable Long itemId) {
        return ApiResponse.ofSuccess(managementService.setItemEnabled(itemId, false));
    }

    private static String str(Object o) {
        return o == null ? null : String.valueOf(o);
    }

    private static Integer intOrNull(Object o) {
        if (o == null) {
            return null;
        }
        return o instanceof Number n ? n.intValue() : Integer.valueOf(String.valueOf(o));
    }
}
