package ${package}.infrastructure.persistence;

import ${package}.application.dictionary.DictionaryPort;
import ${package}.application.dictionary.DictionaryService;
import ${package}.infrastructure.persistence.mapper.DictionaryItemMapper;
import ${package}.infrastructure.persistence.mapper.DictionaryTypeMapper;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Dictionary bean wiring (generated by engineering-platform ${asset.version}).
 */
@Configuration
public class DictionaryBeansConfig {

    @Bean
    public DictionaryPort dictionaryPort(DictionaryTypeMapper typeMapper, DictionaryItemMapper itemMapper) {
        return new MybatisDictionaryRepository(typeMapper, itemMapper);
    }

    @Bean
    public DictionaryService dictionaryService(DictionaryPort dictionaryPort) {
        return new DictionaryService(dictionaryPort);
    }
}
