package ${package};

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.ActiveProfiles;

import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Real HTTP Dictionary E2E (generated by engineering-platform ${asset.version}).
 *
 * Seed layout (see seed-zz-dictionary.sql):
 *   gender       → M(1) F(2) X(disabled)          -> 2 items, order M,F
 *   order_status → CREATED(1) PAID(2) SHIPPED(3) CANCELLED(4) -> 4 items, stable order
 *   retired      → type disabled                  -> DICTIONARY_TYPE_DISABLED
 *   missing      → no such type                   -> DICTIONARY_TYPE_NOT_FOUND
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
class DictionaryE2ETest {

    @LocalServerPort
    private int port;

    @Autowired
    private TestRestTemplate rest;

    private String url(String path) {
        return "http://localhost:" + port + path;
    }

    @SuppressWarnings("unchecked")
    private List<Map> items(String code) {
        ResponseEntity<Map> response = rest.getForEntity(url("/api/dictionaries/" + code + "/items"), Map.class);
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        return (List<Map>) response.getBody().get("data");
    }

    // A. enabled query: gender returns only enabled items (X filtered)
    @Test
    void genderEnabledItems() {
        List<Map> data = items("gender");
        assertThat(data).hasSize(2);
        assertThat(data.get(0).get("value")).isEqualTo("M");
        assertThat(data.get(1).get("value")).isEqualTo("F");
    }

    // B. stable ordering: order_status sorted by sort then id, not insertion order
    @Test
    void orderStatusStableOrdering() {
        List<Map> data = items("order_status");
        assertThat(data).hasSize(4);
        assertThat(data.get(0).get("value")).isEqualTo("CREATED");
        assertThat(data.get(1).get("value")).isEqualTo("PAID");
        assertThat(data.get(2).get("value")).isEqualTo("SHIPPED");
        assertThat(data.get(3).get("value")).isEqualTo("CANCELLED");
    }

    // C. disabled type -> DICTIONARY_TYPE_DISABLED
    @Test
    void disabledTypeRejected() {
        ResponseEntity<Map> response = rest.getForEntity(url("/api/dictionaries/retired/items"), Map.class);
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.BAD_REQUEST);
        Map body = response.getBody();
        Map error = (Map) body.get("error");
        assertThat(String.valueOf(error.get("code"))).isEqualTo("DICTIONARY_TYPE_DISABLED");
    }

    // D. missing type -> DICTIONARY_TYPE_NOT_FOUND
    @Test
    void missingTypeRejected() {
        ResponseEntity<Map> response = rest.getForEntity(url("/api/dictionaries/missing/items"), Map.class);
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.BAD_REQUEST);
        Map body = response.getBody();
        Map error = (Map) body.get("error");
        assertThat(String.valueOf(error.get("code"))).isEqualTo("DICTIONARY_TYPE_NOT_FOUND");
    }
}
