package ${package}.application.dictionary;

import ${package}.common.core.ErrorCode;
import ${package}.common.core.PlatformException;
import ${package}.domain.entity.DictionaryItem;
import ${package}.domain.entity.DictionaryType;

import java.util.ArrayList;
import java.util.List;

/**
 * Dictionary application service (generated by engineering-platform ${asset.version}).
 *
 * Rules:
 *   - type missing        → DICTIONARY_TYPE_NOT_FOUND
 *   - type disabled       → DICTIONARY_TYPE_DISABLED
 *   - item disabled       → filtered out (never returned)
 *   - stable ordering     → sort then id (repository already orders)
 *   - DTO boundary        → API returns DictionaryItemDto, never the entity
 */
public class DictionaryService {

    private final DictionaryPort dictionaryPort;

    public DictionaryService(DictionaryPort dictionaryPort) {
        this.dictionaryPort = dictionaryPort;
    }

    public List<DictionaryItemDto> itemsOf(String code) {
        DictionaryType type = dictionaryPort.findTypeByCode(code)
                .orElseThrow(() -> new PlatformException(ErrorCode.of(
                        "DICTIONARY_TYPE_NOT_FOUND", "dictionary type not found: " + code)));
        if (!Boolean.TRUE.equals(type.getEnabled())) {
            throw new PlatformException(ErrorCode.of(
                    "DICTIONARY_TYPE_DISABLED", "dictionary type disabled: " + code));
        }
        List<DictionaryItemDto> result = new ArrayList<>();
        // stable ordering: sort asc then id asc (spec point: sort stable)
        List<DictionaryItem> items = new ArrayList<>(
                dictionaryPort.findItemsByTypeId(type.getId()));
        items.sort(java.util.Comparator
                .comparingInt(DictionaryItem::getSort)
                .thenComparingLong(DictionaryItem::getId));
        for (DictionaryItem item : items) {
            if (!Boolean.TRUE.equals(item.getEnabled())) {
                continue;
            }
            result.add(new DictionaryItemDto(
                    item.getValue(), item.getLabel(), item.getSort(), item.getDescription()));
        }
        return result;
    }
}
