package ${package}.application.dictionary;

import ${package}.domain.entity.DictionaryItem;
import ${package}.domain.entity.DictionaryType;

import java.util.List;
import java.util.Optional;

/**
 * Dictionary read contract (generated by engineering-platform ${asset.version}).
 *
 * Stable application-level query contract. The implementation lives in the
 * infrastructure layer (MyBatis-Plus); application/business code depends only
 * on this interface — never on MyBatis persistence types.
 */
public interface DictionaryPort {

    Optional<DictionaryType> findTypeByCode(String code);

    /** Items of a type ordered by sort then id (stable ordering). */
    List<DictionaryItem> findItemsByTypeId(Long typeId);
}
