package ${package}.infrastructure.persistence.mapper;

import ${package}.domain.entity.DictionaryType;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

/**
 * MyBatis mapper for DictionaryType (generated by engineering-platform ${asset.version}).
 * Persistence implementation only — never leaks into business/API layers.
 * Hand-written SQL keeps the domain entity annotation-free (MyBatis leakage gate).
 */
@Mapper
public interface DictionaryTypeMapper {

    @Select("SELECT id, code, name, enabled, description, created_at, updated_at "
            + "FROM sys_dictionary_type WHERE code = #{code}")
    DictionaryType findByCode(@Param("code") String code);

    @Select("SELECT id, code, name, enabled, description, created_at, updated_at "
            + "FROM sys_dictionary_type ORDER BY id ASC")
    List<DictionaryType> findAll();

    @Select("SELECT id, code, name, enabled, description, created_at, updated_at "
            + "FROM sys_dictionary_type WHERE id = #{id}")
    DictionaryType findById(@Param("id") Long id);

    @Insert("INSERT INTO sys_dictionary_type (code, name, enabled, description, created_at, updated_at) "
            + "VALUES (#{code}, #{name}, #{enabled}, #{description}, #{createdAt}, #{updatedAt})")
    @Options(useGeneratedKeys = true, keyProperty = "id")
    int insert(DictionaryType type);

    @Update("UPDATE sys_dictionary_type SET name = #{name}, enabled = #{enabled}, "
            + "description = #{description}, updated_at = #{updatedAt} WHERE id = #{id}")
    int update(DictionaryType type);
}
