package ${package}.infrastructure.persistence.mapper;

import ${package}.domain.entity.DictionaryItem;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

/**
 * MyBatis mapper for DictionaryItem (generated by engineering-platform ${asset.version}).
 * Persistence implementation only — never leaks into business/API layers.
 * Hand-written SQL keeps the domain entity annotation-free (MyBatis leakage gate);
 * `value` is a reserved word, so the column is backtick-quoted here.
 */
@Mapper
public interface DictionaryItemMapper {

    @Select("SELECT id, type_id, `value`, label, enabled, sort, description, created_at, updated_at "
            + "FROM sys_dictionary_item WHERE type_id = #{typeId} "
            + "ORDER BY sort ASC, id ASC")
    List<DictionaryItem> findByTypeId(@Param("typeId") Long typeId);
}
