package ${package}.infrastructure.persistence;

import ${package}.application.dictionary.DictionaryPort;
import ${package}.domain.entity.DictionaryItem;
import ${package}.domain.entity.DictionaryType;
import ${package}.infrastructure.persistence.mapper.DictionaryItemMapper;
import ${package}.infrastructure.persistence.mapper.DictionaryTypeMapper;

import java.util.List;
import java.util.Optional;

/**
 * MyBatis implementation of {@link DictionaryPort} (generated by engineering-platform ${asset.version}).
 * All MyBatis types stay confined here, in the infrastructure layer.
 */
public class MybatisDictionaryRepository implements DictionaryPort {

    private final DictionaryTypeMapper typeMapper;
    private final DictionaryItemMapper itemMapper;

    public MybatisDictionaryRepository(DictionaryTypeMapper typeMapper, DictionaryItemMapper itemMapper) {
        this.typeMapper = typeMapper;
        this.itemMapper = itemMapper;
    }

    @Override
    public Optional<DictionaryType> findTypeByCode(String code) {
        return Optional.ofNullable(typeMapper.findByCode(code));
    }

    @Override
    public List<DictionaryItem> findItemsByTypeId(Long typeId) {
        return itemMapper.findByTypeId(typeId);
    }
}
