package ${package}.infrastructure.persistence;

import ${package}.application.dictionary.DictionaryManagementPort;
import ${package}.domain.entity.DictionaryItem;
import ${package}.domain.entity.DictionaryType;
import ${package}.infrastructure.persistence.mapper.DictionaryItemMapper;
import ${package}.infrastructure.persistence.mapper.DictionaryTypeMapper;

import java.util.List;
import java.util.Optional;

/**
 * MyBatis implementation of {@link DictionaryManagementPort} (generated by engineering-platform ${asset.version}).
 *
 * Persistence implementation only — MyBatis mapper usage stays confined here,
 * in the infrastructure layer. Uses hand-written SQL mappers so the domain
 * entity stays annotation-free (MyBatis leakage gate).
 */
public class MybatisDictionaryManagementRepository implements DictionaryManagementPort {

    private final DictionaryTypeMapper typeMapper;
    private final DictionaryItemMapper itemMapper;

    public MybatisDictionaryManagementRepository(DictionaryTypeMapper typeMapper,
                                                 DictionaryItemMapper itemMapper) {
        this.typeMapper = typeMapper;
        this.itemMapper = itemMapper;
    }

    // ---- type ----

    @Override
    public List<DictionaryType> findAllTypes() {
        return typeMapper.findAll();
    }

    @Override
    public Optional<DictionaryType> findTypeById(Long typeId) {
        return Optional.ofNullable(typeMapper.findById(typeId));
    }

    @Override
    public Optional<DictionaryType> findTypeByCode(String code) {
        return Optional.ofNullable(typeMapper.findByCode(code));
    }

    @Override
    public void insertType(DictionaryType type) {
        typeMapper.insert(type);
    }

    @Override
    public void updateType(DictionaryType type) {
        typeMapper.update(type);
    }

    // ---- item ----

    @Override
    public List<DictionaryItem> findItemsByTypeId(Long typeId) {
        return itemMapper.findByTypeId(typeId);
    }

    @Override
    public Optional<DictionaryItem> findItemById(Long itemId) {
        return Optional.ofNullable(itemMapper.findById(itemId));
    }

    @Override
    public long countItemsByTypeAndValue(Long typeId, String value) {
        return itemMapper.countByTypeAndValue(typeId, value);
    }

    @Override
    public void insertItem(DictionaryItem item) {
        itemMapper.insert(item);
    }

    @Override
    public void updateItem(DictionaryItem item) {
        itemMapper.update(item);
    }
}
