-- Audit log table (generated by engineering-platform ${asset.version})
CREATE TABLE IF NOT EXISTS audit_log (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    actor       VARCHAR(100) NOT NULL,
    action      VARCHAR(200) NOT NULL,
    target      VARCHAR(500),
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
