package ${package}.common.audit;

import org.aspectj.lang.JoinPoint;
import org.aspectj.lang.annotation.AfterReturning;
import org.aspectj.lang.annotation.Aspect;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 * Audit baseline (generated by engineering-platform ${asset.version}).
 * V1: structured audit log via logging; persistence-backed audit store follows.
 */
@Aspect
@Component
public class AuditLogAspect {

    private static final Logger log = LoggerFactory.getLogger(AuditLogAspect.class);

    @AfterReturning(pointcut = "execution(* ${package}..api.controller..*(..))", returning = "result")
    public void auditControllerCall(JoinPoint joinPoint, Object result) {
        log.info("AUDIT controller={} method={} result={}",
                joinPoint.getTarget().getClass().getSimpleName(),
                joinPoint.getSignature().getName(),
                result == null ? "void" : result.getClass().getSimpleName());
    }
}
