// Enterprise management API services (generated by engineering-platform frontend-enterprise-management asset)
// All HTTP goes through the Platform Request Client (src/api/request.ts). No raw axios/fetch.
import { http } from './request';
import type {
  PageResult,
  User,
  UserCreateRequest,
  UserCreateResult,
  UserUpdateRequest,
  Role,
  RoleCreateRequest,
  RoleUpdateRequest,
  Permission,
  Department,
  DepartmentNode,
  Menu,
  MenuNode,
  DictionaryType,
  DictionaryItem,
  OperationLog,
} from '../types/enterprise';

export const userApi = {
  page: (params: { page?: number; size?: number; username?: string; enabled?: boolean; departmentId?: number }) =>
    http.get<PageResult<User>>('/users' + queryString(params)),
  detail: (id: number) => http.get<User>('/users/' + (id)),
  create: (body: UserCreateRequest) => http.post<UserCreateResult>('/users', body),
  update: (id: number, body: UserUpdateRequest) => http.put<User>('/users/' + (id), body),
  enable: (id: number) => http.post<User>('/users/' + (id) + '/enable', {}),
  disable: (id: number) => http.post<User>('/users/' + (id) + '/disable', {}),
  assignRoles: (id: number, roleIds: number[]) => http.post<User>('/users/' + (id) + '/roles', roleIds),
  assignDepartment: (id: number, departmentId: number | null) =>
    http.post<User>('/users/' + (id) + '/department', { departmentId }),
};

export const roleApi = {
  page: (params: { page?: number; size?: number; keyword?: string; enabled?: boolean }) =>
    http.get<PageResult<Role>>('/roles' + queryString(params)),
  detail: (id: number) => http.get<Role>('/roles/' + (id)),
  create: (body: RoleCreateRequest) => http.post<Role>('/roles', body),
  update: (id: number, body: RoleUpdateRequest) => http.put<Role>('/roles/' + (id), body),
  enable: (id: number) => http.post<Role>('/roles/' + (id) + '/enable', {}),
  disable: (id: number) => http.post<Role>('/roles/' + (id) + '/disable', {}),
  assignPermissions: (id: number, permissionIds: number[]) =>
    http.post<Role>('/roles/' + (id) + '/permissions', permissionIds),
};

export const permissionApi = {
  list: (params: { code?: string } = {}) => http.get<Permission[]>('/permissions' + queryString(params)),
  detail: (id: number) => http.get<Permission>('/permissions/' + (id)),
};

export const departmentApi = {
  tree: () => http.get<DepartmentNode[]>('/departments/tree'),
  detail: (id: number) => http.get<Department>('/departments/' + (id)),
  create: (body: { code: string; name?: string; parentId?: number | null; sort?: number }) =>
    http.post<Department>('/departments', body),
  update: (id: number, body: { name?: string; parentId?: number | null; sort?: number }) =>
    http.put<Department>('/departments/' + (id), body),
  enable: (id: number) => http.post<Department>('/departments/' + (id) + '/enable', {}),
  disable: (id: number) => http.post<Department>('/departments/' + (id) + '/disable', {}),
};

export const menuApi = {
  tree: () => http.get<MenuNode[]>('/menus/tree'),
  detail: (id: number) => http.get<Menu>('/menus/' + (id)),
  create: (body: {
    parentId?: number | null;
    code: string;
    name?: string;
    type?: string;
    path?: string | null;
    permissionCode?: string | null;
    sort?: number;
  }) => http.post<Menu>('/menus', body),
  update: (
    id: number,
    body: { parentId?: number | null; name?: string; path?: string | null; permissionCode?: string | null; sort?: number },
  ) => http.put<Menu>('/menus/' + (id), body),
  enable: (id: number) => http.post<Menu>('/menus/' + (id) + '/enable', {}),
  disable: (id: number) => http.post<Menu>('/menus/' + (id) + '/disable', {}),
};

export const dictionaryApi = {
  types: () => http.get<DictionaryType[]>('/dictionaries/types'),
  typeDetail: (id: number) => http.get<DictionaryType>('/dictionaries/types/' + (id)),
  createType: (body: { code: string; name?: string; description?: string | null }) =>
    http.post<DictionaryType>('/dictionaries/types', body),
  updateType: (id: number, body: { name?: string; description?: string | null }) =>
    http.put<DictionaryType>('/dictionaries/types/' + (id), body),
  enableType: (id: number) => http.post<DictionaryType>('/dictionaries/types/' + (id) + '/enable', {}),
  disableType: (id: number) => http.post<DictionaryType>('/dictionaries/types/' + (id) + '/disable', {}),
  itemsOfType: (typeId: number) => http.get<DictionaryItem[]>('/dictionaries/types/' + (typeId) + '/items'),
  itemsByCode: (code: string) => http.get<DictionaryItem[]>('/dictionaries/' + (code) + '/items'),
  createItem: (typeId: number, body: { value: string; label?: string; sort?: number; description?: string | null }) =>
    http.post<DictionaryItem>('/dictionaries/types/' + (typeId) + '/items', body),
  updateItem: (itemId: number, body: { label?: string; sort?: number; description?: string | null }) =>
    http.put<DictionaryItem>('/dictionaries/items/' + (itemId), body),
  enableItem: (itemId: number) => http.post<DictionaryItem>('/dictionaries/items/' + (itemId) + '/enable', {}),
  disableItem: (itemId: number) => http.post<DictionaryItem>('/dictionaries/items/' + (itemId) + '/disable', {}),
};

export const operationLogApi = {
  page: (params: {
    page?: number;
    size?: number;
    userId?: string;
    operation?: string;
    resourceType?: string;
    result?: string;
    from?: string;
    to?: string;
  }) => http.get<PageResult<OperationLog>>('/operation-logs' + queryString(params)),
};

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined && v !== null && v !== '');
  if (entries.length === 0) {
    return '';
  }
  return '?' + entries.map(([k, v]) => (encodeURIComponent(k)) + '=' + (encodeURIComponent(String(v)))).join('&');
}
