// Supplier API service (generated by engineering-platform frontend-supplier-reference asset)
// All HTTP through the Platform Request Client — no raw axios/fetch.
import { http } from './request';
import type { Supplier, SupplierCreateRequest, SupplierUpdateRequest, SupplierQuery, SupplierPageResponse } from '../types/supplier';
import type { EntityId } from '../types/enterprise';

export const supplierApi = {
  page: (query: SupplierQuery = {}) =>
    http.get<SupplierPageResponse>('/suppliers' + queryString(query as unknown as Record<string, unknown>)),
  detail: (id: EntityId) => http.get<Supplier>('/suppliers/' + id),
  create: (body: SupplierCreateRequest) => http.post<Supplier>('/suppliers', body),
  update: (id: EntityId, body: SupplierUpdateRequest) => http.put<Supplier>('/suppliers/' + id, body),
  disable: (id: EntityId) => http.post<Supplier>('/suppliers/' + id + '/disable', {}),
};

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined && v !== null && v !== '');
  if (entries.length === 0) {
    return '';
  }
  return '?' + entries
    .map(([k, v]) => encodeURIComponent(k) + '=' + encodeURIComponent(String(v)))
    .join('&');
}
