<script setup lang="ts">
// PageHeader (generated by engineering-platform frontend-permission asset)
// UX baseline: title + optional description + primary action area.
withDefaults(defineProps<{ title: string; description?: string }>(), {});
</script>

<template>
  <div class="page-header" data-testid="page-header">
    <div class="page-header-text">
      <h2 class="page-title">{{ title }}</h2>
      <p v-if="description" class="page-description">{{ description }}</p>
    </div>
    <div class="page-actions">
      <slot name="actions" />
    </div>
  </div>
</template>

<style scoped>
.page-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: var(--ep-space-4);
  margin-bottom: var(--ep-space-5);
}
.page-title {
  margin: 0;
  font-size: var(--ep-font-size-xl);
}
.page-description {
  margin: var(--ep-space-1) 0 0;
  color: var(--ep-color-info);
  font-size: var(--ep-font-size-base);
}
</style>
