<script setup lang="ts">
// PageContainer (generated by engineering-platform frontend-permission asset)
// UX baseline: content area with consistent max-width + spacing.
withDefaults(defineProps<{ fullWidth?: boolean }>(), { fullWidth: false });
</script>

<template>
  <div class="page-container" :class="{ 'page-container--full': fullWidth }" data-testid="page-container">
    <slot />
  </div>
</template>

<style scoped>
.page-container {
  max-width: var(--ep-content-max-width);
  margin: 0 auto;
  padding: var(--ep-space-4);
}
.page-container--full {
  max-width: none;
}
</style>
