package ${package}.infrastructure.persistence;

import ${package}.application.datascope.DataPermissionContext;
import ${package}.application.organization.DepartmentPort;
import ${package}.application.supplier.SupplierPort;
import ${package}.common.core.PageQuery;
import ${package}.common.core.PageResult;
import ${package}.common.security.DataScope;
import ${package}.domain.entity.Supplier;
import ${package}.infrastructure.persistence.mapper.SupplierMapper;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;

import java.util.List;
import java.util.Optional;
import java.util.Set;

/**
 * MyBatis-Plus implementation of {@link SupplierPort} with real data-permission
 * enforcement (generated by engineering-platform ${asset.version}).
 *
 * Data scope enforcement happens HERE, at the query boundary:
 *   ALL                    → no restriction
 *   DEPARTMENT             → department_id = context.departmentId
 *   DEPARTMENT_AND_CHILDREN→ department_id IN (department + descendants)
 *   SELF                   → created_by = current user
 *
 * Fail-safe: missing department with a department-dependent scope denies (empty),
 * never upgrades to ALL. All MyBatis types stay confined to infrastructure.
 */
public class MybatisSupplierRepository implements SupplierPort {

    private final SupplierMapper supplierMapper;
    private final DepartmentPort departmentPort;

    public MybatisSupplierRepository(SupplierMapper supplierMapper, DepartmentPort departmentPort) {
        this.supplierMapper = supplierMapper;
        this.departmentPort = departmentPort;
    }

    @Override
    public Optional<Supplier> findById(Long id) {
        return Optional.ofNullable(supplierMapper.selectById(id));
    }

    @Override
    public Optional<Supplier> findByIdInScope(Long id, DataPermissionContext context) {
        return findByScope(context).stream().filter(p -> p.getId().equals(id)).findFirst();
    }

    @Override
    public List<Supplier> findByScope(DataPermissionContext context) {
        QueryWrapper<Supplier> wrapper = scopeWrapper(context);
        wrapper.orderByAsc("id");
        return supplierMapper.selectList(wrapper);
    }

    @Override
    public PageResult<Supplier> findPageByScope(DataPermissionContext context, PageQuery query) {
        QueryWrapper<Supplier> countWrapper = scopeWrapper(context);
        long total = supplierMapper.selectCount(countWrapper);
        QueryWrapper<Supplier> pageWrapper = scopeWrapper(context);
        pageWrapper.orderByAsc("id");
        pageWrapper.last("LIMIT " + query.size() + " OFFSET " + query.offset());
        List<Supplier> items = supplierMapper.selectList(pageWrapper);
        return PageResult.of(items, total, query.page(), query.size());
    }

    @Override
    public PageResult<Supplier> findPageByScopeFiltered(DataPermissionContext context, PageQuery query,
                                                       String keyword, String status, String category) {
        QueryWrapper<Supplier> countWrapper = scopeWrapper(context);
        applyFilters(countWrapper, keyword, status, category);
        long total = supplierMapper.selectCount(countWrapper);
        QueryWrapper<Supplier> pageWrapper = scopeWrapper(context);
        applyFilters(pageWrapper, keyword, status, category);
        pageWrapper.orderByAsc("id");
        pageWrapper.last("LIMIT " + query.size() + " OFFSET " + query.offset());
        List<Supplier> items = supplierMapper.selectList(pageWrapper);
        return PageResult.of(items, total, query.page(), query.size());
    }

    private void applyFilters(QueryWrapper<Supplier> wrapper, String keyword, String status, String category) {
        if (keyword != null && !keyword.isBlank()) {
            wrapper.and(w -> w.like("code", keyword).or().like("name", keyword));
        }
        if (status != null && !status.isBlank()) {
            wrapper.eq("status", status);
        }
        if (category != null && !category.isBlank()) {
            wrapper.eq("category", category);
        }
    }

    private QueryWrapper<Supplier> scopeWrapper(DataPermissionContext context) {
        QueryWrapper<Supplier> wrapper = new QueryWrapper<>();
        DataScope scope = context.scope() == null ? DataScope.SELF : context.scope();
        switch (scope) {
            case ALL -> {
                // no restriction
            }
            case DEPARTMENT -> {
                if (context.departmentId() == null) {
                    wrapper.eq("id", -1L); // fail-safe deny
                } else {
                    wrapper.eq("department_id", context.departmentId());
                }
            }
            case DEPARTMENT_AND_CHILDREN -> {
                if (context.departmentId() == null) {
                    wrapper.eq("id", -1L); // fail-safe deny
                } else {
                    Set<Long> ids = departmentPort.descendantIds(context.departmentId());
                    ids.add(context.departmentId());
                    wrapper.in("department_id", ids);
                }
            }
            case SELF -> {
                if (context.userId() == null) {
                    wrapper.eq("id", -1L); // fail-safe deny
                } else {
                    wrapper.eq("created_by", String.valueOf(context.userId()));
                }
            }
        }
        return wrapper;
    }

    @Override
    public boolean existsByCode(String code, Long excludeId) {
        QueryWrapper<Supplier> wrapper = new QueryWrapper<>();
        wrapper.eq("code", code);
        if (excludeId != null) {
            wrapper.ne("id", excludeId);
        }
        return supplierMapper.selectCount(wrapper) > 0;
    }

    @Override
    public Supplier insert(Supplier supplier) {
        supplierMapper.insert(supplier);
        return supplier;
    }

    @Override
    public int update(Supplier supplier) {
        return supplierMapper.updateById(supplier);
    }
}
