-- TEST-ONLY supplier-reference seed (generated by engineering-platform ${asset.version})
-- Loaded only by the test profile. Extends data-permission seed (departments/users/roles).
-- Filename keeps alphabetical order AFTER seed-zz-menu.sql.
-- ID space: sys_permission 31-34 / sys_role_permission 200+ / sys_dictionary_type 6-7 /
-- sys_dictionary_item 14-18 / sys_menu 12-14 — avoids collision with rbac (1,7-30),
-- data-permission (2), product-reference (4-6, 8-13, dict 4-5, items 9-13, menus 9-11).

-- Permissions: supplier CRUD (read 31; create/update/disable 32-34)
INSERT INTO sys_permission (id, code, name, created_at, updated_at) VALUES
  (31, 'supplier:item:read', 'Read suppliers', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (32, 'supplier:item:create', 'Create suppliers', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (33, 'supplier:item:update', 'Update suppliers', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (34, 'supplier:item:disable', 'Disable suppliers', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Role-Permission: admin gets full CRUD; sales-manager gets create+update
-- (partial); finance-user gets disable (partial); sales-user remains read-only;
-- viewer has no supplier permissions (403)
INSERT INTO sys_role_permission (id, role_id, permission_id, created_at) VALUES
  (200, 1, 31, CURRENT_TIMESTAMP),   -- admin read
  (201, 1, 32, CURRENT_TIMESTAMP),   -- admin create
  (202, 1, 33, CURRENT_TIMESTAMP),   -- admin update
  (203, 1, 34, CURRENT_TIMESTAMP),   -- admin disable
  (204, 3, 31, CURRENT_TIMESTAMP),   -- sales-manager read
  (205, 3, 32, CURRENT_TIMESTAMP),   -- sales-manager create
  (206, 3, 33, CURRENT_TIMESTAMP),   -- sales-manager update (partial)
  (207, 4, 31, CURRENT_TIMESTAMP),   -- sales-user read
  (208, 5, 31, CURRENT_TIMESTAMP),   -- finance-user read
  (209, 5, 34, CURRENT_TIMESTAMP),   -- finance-user disable (partial)
  (210, 6, 31, CURRENT_TIMESTAMP);   -- self read

-- Suppliers: reference data spread across departments/creators/status/category
INSERT INTO supplier (id, code, name, status, category, department_id, created_by, created_at, updated_at) VALUES
  (1, 'SUP-001', 'S-HQ-1', 'ENABLED', 'ELECTRONIC', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (2, 'SUP-002', 'S-SALES-1', 'ENABLED', 'ELECTRONIC', 2, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (3, 'SUP-003', 'S-SALES-2', 'DISABLED', 'MECHANICAL', 2, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (4, 'SUP-004', 'S-SALES-EAST-1', 'ENABLED', 'ELECTRONIC', 3, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (5, 'SUP-005', 'S-FINANCE-1', 'ENABLED', 'PACKAGING', 4, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (6, 'SUP-006', 'S-SELF-1', 'ENABLED', 'ELECTRONIC', 1, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Dictionary: supplier_status type (dictionary seed: 1=gender 2=order_status 3=retired;
-- product-reference: 4=product_status 5=product_category)
INSERT INTO sys_dictionary_type (id, code, name, enabled, description, created_at, updated_at) VALUES
  (6, 'supplier_status', 'Supplier Status', 1, 'Supplier lifecycle states', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys_dictionary_item (id, type_id, `value`, label, enabled, sort, description, created_at, updated_at) VALUES
  (14, 6, 'ENABLED', 'Enabled', 1, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (15, 6, 'DISABLED', 'Disabled', 1, 2, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_dictionary_type (id, code, name, enabled, description, created_at, updated_at) VALUES
  (7, 'supplier_category', 'Supplier category', 1, 'Supplier categories', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys_dictionary_item (id, type_id, `value`, label, enabled, sort, description, created_at, updated_at) VALUES
  (16, 7, 'ELECTRONIC', 'Electronic', 1, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (17, 7, 'MECHANICAL', 'Mechanical', 1, 2, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (18, 7, 'PACKAGING', 'Packaging', 1, 3, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Menus: Suppliers directory + list (menu seed: 1-11 system/product; supplier uses 12-14)
INSERT INTO sys_menu (id, parent_id, code, name, type, path, permission_code, enabled, sort, created_at, updated_at) VALUES
  (12, NULL, 'supplier', 'Suppliers', 'DIRECTORY', '/supplier', NULL, 1, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (13, 12, 'supplier-list', 'Supplier list', 'MENU', '/suppliers', 'supplier:item:read', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (14, 12, 'supplier-disabled', 'Disabled', 'MENU', '/supplier/disabled', 'supplier:item:read', 0, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
