package ${package}.application.supplier;

import ${package}.application.datascope.DataPermissionContext;
import ${package}.common.core.PageQuery;
import ${package}.common.core.PageResult;
import ${package}.domain.entity.Supplier;

import java.util.List;
import java.util.Optional;

/**
 * Supplier persistence contract (generated by engineering-platform ${asset.version}).
 *
 * Stable application-level query contract. The implementation lives in the
 * infrastructure layer (MyBatis-Plus); application/business code depends only
 * on this interface — never on MyBatis persistence types.
 */
public interface SupplierPort {

    /** Supplier by id without data-scope filtering (caller enforces scope). */
    Optional<Supplier> findById(Long id);

    /** Supplier by id visible under the given data permission context. */
    Optional<Supplier> findByIdInScope(Long id, DataPermissionContext context);

    /** All suppliers visible under the given data permission context. */
    List<Supplier> findByScope(DataPermissionContext context);

    /** Paged suppliers visible under the given data permission context. */
    PageResult<Supplier> findPageByScope(DataPermissionContext context, PageQuery query);

    /** Paged suppliers visible under the given data permission context, with keyword/status/category filters (V05-WORK-005). */
    PageResult<Supplier> findPageByScopeFiltered(DataPermissionContext context, PageQuery query,
                                               String keyword, String status, String category);

    /** True when a supplier with the code exists (excluding the given id for update). */
    boolean existsByCode(String code, Long excludeId);

    /** Insert a new supplier; returns the persisted supplier (with generated id). */
    Supplier insert(Supplier supplier);

    /** Update a supplier; returns rows affected. */
    int update(Supplier supplier);
}
