package ${package}.application.supplier;

import ${package}.application.datascope.DataPermissionContext;
import ${package}.application.dictionary.DictionaryPort;
import ${package}.common.core.ErrorCode;
import ${package}.common.core.PageQuery;
import ${package}.common.core.PageResult;
import ${package}.common.core.PlatformException;
import ${package}.domain.entity.DictionaryItem;
import ${package}.domain.entity.Supplier;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Set;

/**
 * Supplier application service (generated by engineering-platform ${asset.version}).
 *
 * Consumes Platform Core (ApiResponse via controller, PageQuery/PageResult,
 * PlatformException/ErrorCode), Dictionary (status/category validation),
 * Data Permission (detail/update/list all enforce scope), and Operation Log
 * (write operations are annotated at the controller boundary).
 *
 * Client never supplies createdBy/departmentId: they come from the
 * authenticated RequestContext (current user / their department).
 */
public class SupplierService {

    private static final Set<String> KNOWN_STATUS = Set.of("ENABLED", "DISABLED");

    private final SupplierPort supplierPort;
    private final DictionaryPort dictionaryPort;

    public SupplierService(SupplierPort supplierPort, DictionaryPort dictionaryPort) {
        this.supplierPort = supplierPort;
        this.dictionaryPort = dictionaryPort;
    }

    // ---- create ----------------------------------------------------------

    public SupplierResponse create(SupplierCreateRequest request, Long userId, Long departmentId) {
        validateCode(request.code());
        validateName(request.name());
        String status = normalizeStatus(request.status());
        String category = normalizeCategory(request.category());
        if (supplierPort.existsByCode(request.code(), null)) {
            throw new PlatformException(ErrorCode.of("SUPPLIER_CODE_DUPLICATE",
                    "supplier code already exists: " + request.code()));
        }
        Supplier supplier = new Supplier();
        supplier.setCode(request.code());
        supplier.setName(request.name().trim());
        supplier.setStatus(status);
        supplier.setCategory(category);
        supplier.setDepartmentId(departmentId);
        supplier.setCreatedBy(userId);
        LocalDateTime now = LocalDateTime.now();
        supplier.setCreatedAt(now);
        supplier.setUpdatedAt(now);
        supplierPort.insert(supplier);
        return toResponse(supplier);
    }

    // ---- detail ----------------------------------------------------------

    public SupplierResponse get(Long id, DataPermissionContext context) {
        Supplier supplier = supplierPort.findByIdInScope(id, context)
                .orElseThrow(() -> new PlatformException(ErrorCode.of("SUPPLIER_NOT_FOUND",
                        "supplier not found: " + id)));
        return toResponse(supplier);
    }

    // ---- list / page ------------------------------------------------------

    public List<SupplierResponse> list(DataPermissionContext context) {
        return supplierPort.findByScope(context).stream().map(this::toResponse).toList();
    }

    public PageResult<SupplierResponse> page(PageQuery query, DataPermissionContext context) {
        PageResult<Supplier> result = supplierPort.findPageByScope(context, query);
        List<SupplierResponse> items = result.items().stream().map(this::toResponse).toList();
        return PageResult.of(items, result.total(), result.page(), result.size());
    }

    /** Paged query with keyword/status/category filters (V05-WORK-005 frontend search/filter). */
    public PageResult<SupplierResponse> pageFiltered(PageQuery query, DataPermissionContext context,
                                                    String keyword, String status, String category) {
        PageResult<Supplier> result = supplierPort.findPageByScopeFiltered(context, query, keyword, status, category);
        List<SupplierResponse> items = result.items().stream().map(this::toResponse).toList();
        return PageResult.of(items, result.total(), result.page(), result.size());
    }

    // ---- update ----------------------------------------------------------

    public SupplierResponse update(Long id, SupplierUpdateRequest request, DataPermissionContext context) {
        Supplier supplier = supplierPort.findByIdInScope(id, context)
                .orElseThrow(() -> new PlatformException(ErrorCode.of("SUPPLIER_NOT_FOUND",
                        "supplier not found: " + id)));
        validateCode(request.code());
        validateName(request.name());
        String status = normalizeStatus(request.status());
        String category = normalizeCategory(request.category());
        if (supplierPort.existsByCode(request.code(), id)) {
            throw new PlatformException(ErrorCode.of("SUPPLIER_CODE_DUPLICATE",
                    "supplier code already exists: " + request.code()));
        }
        supplier.setCode(request.code());
        supplier.setName(request.name().trim());
        supplier.setStatus(status);
        supplier.setCategory(category);
        supplier.setUpdatedAt(LocalDateTime.now());
        // createdBy/createdAt/departmentId are immutable (never updated)
        supplierPort.update(supplier);
        return toResponse(supplier);
    }

    // ---- disable ----------------------------------------------------------

    public SupplierResponse disable(Long id, DataPermissionContext context) {
        Supplier supplier = supplierPort.findByIdInScope(id, context)
                .orElseThrow(() -> new PlatformException(ErrorCode.of("SUPPLIER_NOT_FOUND",
                        "supplier not found: " + id)));
        supplier.setStatus("DISABLED");
        supplier.setUpdatedAt(LocalDateTime.now());
        supplierPort.update(supplier);
        return toResponse(supplier);
    }

    // ---- validation helpers --------------------------------------------------

    private void validateCode(String code) {
        if (code == null || code.isBlank()) {
            throw new PlatformException(ErrorCode.of("SUPPLIER_CODE_REQUIRED", "supplier code is required"));
        }
        if (code.trim().length() > 64) {
            throw new PlatformException(ErrorCode.of("SUPPLIER_CODE_INVALID", "supplier code too long"));
        }
        if (!code.trim().matches("[A-Za-z0-9._-]+")) {
            throw new PlatformException(ErrorCode.of("SUPPLIER_CODE_INVALID", "supplier code format invalid"));
        }
    }

    private void validateName(String name) {
        if (name == null || name.isBlank()) {
            throw new PlatformException(ErrorCode.of("SUPPLIER_NAME_REQUIRED", "supplier name is required"));
        }
        if (name.trim().length() > 128) {
            throw new PlatformException(ErrorCode.of("SUPPLIER_NAME_INVALID", "supplier name too long"));
        }
    }

    /** Status validated against the supplier_status dictionary when available; falls back to stable set. */
    private String normalizeStatus(String status) {
        if (status == null || status.isBlank()) {
            return "ENABLED";
        }
        String normalized = status.trim().toUpperCase();
        if (!KNOWN_STATUS.contains(normalized)) {
            throw new PlatformException(ErrorCode.of("SUPPLIER_STATUS_INVALID",
                    "invalid supplier status: " + status));
        }
        // consume dictionary: supplier_status type must expose the value (or be absent)
        dictionaryPort.findTypeByCode("supplier_status").ifPresent(type -> {
            Set<String> values = dictionaryPort.findItemsByTypeId(type.getId()).stream()
                    .map(DictionaryItem::getValue).collect(java.util.stream.Collectors.toSet());
            if (!values.isEmpty() && !values.contains(normalized)) {
                throw new PlatformException(ErrorCode.of("SUPPLIER_STATUS_INVALID",
                        "supplier status not in dictionary: " + status));
            }
        });
        return normalized;
    }

    private String normalizeCategory(String category) {
        if (category == null || category.isBlank()) {
            return null;
        }
        return category.trim();
    }

    private SupplierResponse toResponse(Supplier supplier) {
        return SupplierResponse.of(
                supplier.getId(), supplier.getCode(), supplier.getName(), supplier.getStatus(),
                supplier.getCategory(), supplier.getDepartmentId(), supplier.getCreatedBy(),
                supplier.getCreatedAt(), supplier.getUpdatedAt());
    }
}
