package ${package}.application.supplier;

/**
 * Supplier update request (generated by engineering-platform ${asset.version}).
 * createdBy/createdAt/departmentId are immutable — never accepted from client.
 */
public record SupplierUpdateRequest(String code, String name, String status, String category) {
}
