package ${package}.infrastructure.persistence;

import ${package}.application.dictionary.DictionaryPort;
import ${package}.application.organization.DepartmentPort;
import ${package}.application.supplier.SupplierPort;
import ${package}.application.supplier.SupplierService;
import ${package}.infrastructure.persistence.mapper.SupplierMapper;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Supplier reference bean wiring (generated by engineering-platform ${asset.version}).
 */
@Configuration
public class SupplierBeansConfig {

    @Bean
    public SupplierPort supplierPort(SupplierMapper supplierMapper, DepartmentPort departmentPort) {
        return new MybatisSupplierRepository(supplierMapper, departmentPort);
    }

    @Bean
    public SupplierService supplierService(SupplierPort supplierPort, DictionaryPort dictionaryPort) {
        return new SupplierService(supplierPort, dictionaryPort);
    }
}
