package ${package}.application.supplier;

/**
 * Supplier create request (generated by engineering-platform ${asset.version}).
 * Client never supplies createdBy/departmentId — they are derived from the
 * authenticated RequestContext server-side.
 */
public record SupplierCreateRequest(String code, String name, String status, String category) {
}
