package ${package}.api.supplier;

import ${package}.application.datascope.DataPermissionContext;
import ${package}.application.datascope.DataScopeResolver;
import ${package}.application.supplier.SupplierCreateRequest;
import ${package}.application.supplier.SupplierResponse;
import ${package}.application.supplier.SupplierService;
import ${package}.application.supplier.SupplierUpdateRequest;
import ${package}.common.core.ApiResponse;
import ${package}.common.core.PageQuery;
import ${package}.common.core.PageResult;
import ${package}.common.core.PlatformException;
import ${package}.common.core.RequestContext;
import ${package}.common.security.OperationLog;
import ${package}.common.security.RequirePermission;
import ${package}.common.security.SecurityErrorCodes;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * Reference Supplier CRUD API (generated by engineering-platform ${asset.version}).
 *
 * Validation host consuming the whole V0.4 Enterprise Foundation:
 *   Platform Core (ApiResponse/PageQuery/PageResult/RequestContext)
 *   Authentication (AuthInterceptor fills RequestContext)
 *   RBAC (@RequirePermission)
 *   Organization/Data Permission (DataScopeResolver per request)
 *   Operation Log (@OperationLog on write operations)
 */
@RestController
@RequestMapping("/api/suppliers")
public class SupplierController {

    private final SupplierService supplierService;
    private final DataScopeResolver dataScopeResolver;

    public SupplierController(SupplierService supplierService, DataScopeResolver dataScopeResolver) {
        this.supplierService = supplierService;
        this.dataScopeResolver = dataScopeResolver;
    }

    private Long currentUserId() {
        return Long.valueOf(RequestContext.currentUserId()
                .orElseThrow(() -> new PlatformException(SecurityErrorCodes.UNAUTHENTICATED)));
    }

    private DataPermissionContext scope() {
        return dataScopeResolver.resolve(currentUserId());
    }

    @PostMapping
    @RequirePermission("supplier:item:create")
    @OperationLog(operation = "SUPPLIER_CREATE", resourceType = "SUPPLIER")
    public ApiResponse<SupplierResponse> create(@RequestBody SupplierCreateRequest request) {
        Long userId = currentUserId();
        Long departmentId = RequestContext.currentDepartmentId()
                .map(Long::valueOf).orElse(null);
        return ApiResponse.ofSuccess(supplierService.create(request, userId, departmentId));
    }

    @GetMapping("/{id}")
    @RequirePermission("supplier:item:read")
    public ApiResponse<SupplierResponse> detail(@PathVariable Long id) {
        return ApiResponse.ofSuccess(supplierService.get(id, scope()));
    }

    @GetMapping
    @RequirePermission("supplier:item:read")
    public ApiResponse<PageResult<SupplierResponse>> list(
            @RequestParam(defaultValue = "1") int page,
            @RequestParam(defaultValue = "20") int size,
            @RequestParam(required = false) String keyword,
            @RequestParam(required = false) String status,
            @RequestParam(required = false) String category) {
        if (keyword == null && status == null && category == null) {
            return ApiResponse.ofSuccess(supplierService.page(PageQuery.of(page, size), scope()));
        }
        return ApiResponse.ofSuccess(supplierService.pageFiltered(PageQuery.of(page, size), scope(),
                keyword, status, category));
    }

    @PutMapping("/{id}")
    @RequirePermission("supplier:item:update")
    @OperationLog(operation = "SUPPLIER_UPDATE", resourceType = "SUPPLIER")
    public ApiResponse<SupplierResponse> update(@PathVariable Long id,
                                               @RequestBody SupplierUpdateRequest request) {
        return ApiResponse.ofSuccess(supplierService.update(id, request, scope()));
    }

    @PostMapping("/{id}/disable")
    @RequirePermission("supplier:item:disable")
    @OperationLog(operation = "SUPPLIER_DISABLE", resourceType = "SUPPLIER")
    public ApiResponse<SupplierResponse> disable(@PathVariable Long id) {
        return ApiResponse.ofSuccess(supplierService.disable(id, scope()));
    }
}
