package ${package}.infrastructure.persistence.mapper;

import ${package}.domain.entity.Supplier;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;

/**
 * MyBatis-Plus mapper for Supplier (generated by engineering-platform ${asset.version}).
 * Persistence implementation only — never leaks into business/API layers.
 */
@Mapper
public interface SupplierMapper extends BaseMapper<Supplier> {
}
