package ${package};

import ${package}.api.auth.LoginRequest;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.ActiveProfiles;

import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Real HTTP Supplier DataScope E2E (generated by engineering-platform ${asset.version}).
 *
 * Proves data permission also protects detail/update (not just list):
 *   detail out of scope -> not exposed (SUPPLIER_NOT_FOUND)
 *   update out of scope -> denied (SUPPLIER_NOT_FOUND)
 *   detail in scope -> OK
 * Seed suppliers: 1=HQ/admin, 2+3=Sales, 4=Sales-East, 5=Finance, 6=self-user.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
class SupplierDataScopeE2ETest {

    @LocalServerPort
    private int port;

    @Autowired
    private TestRestTemplate rest;

    private String url(String path) {
        return "http://localhost:" + port + path;
    }

    private ResponseEntity<Map> login(String username, String password) {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        HttpEntity<LoginRequest> body = new HttpEntity<>(new LoginRequest(username, password), headers);
        return rest.postForEntity(url("/api/auth/login"), body, Map.class);
    }

    private String token(String username, String password) {
        ResponseEntity<Map> response = login(username, password);
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        Map data = (Map) response.getBody().get("data");
        return (String) data.get("token");
    }

    private HttpEntity<String> json(String token, String body) {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        headers.setBearerAuth(token);
        return new HttpEntity<>(body, headers);
    }

    private ResponseEntity<Map> get(String token, String path) {
        HttpHeaders headers = new HttpHeaders();
        headers.setBearerAuth(token);
        return rest.exchange(url(path), HttpMethod.GET, new HttpEntity<>(headers), Map.class);
    }

    // admin (ALL) can read every supplier detail
    @Test
    void adminReadsAllDetails() {
        String token = token("admin", "admin123");
        for (long id = 1; id <= 6; id++) {
            ResponseEntity<Map> detail = get(token, "/api/suppliers/" + id);
            assertThat(detail.getStatusCode()).isEqualTo(HttpStatus.OK);
        }
    }

    // finance-user (DEPARTMENT, dept 4) can read supplier 5 but NOT supplier 2 (Sales)
    @Test
    void departmentUserSeesOwnDetailOnly() {
        String token = token("finance-user", "admin123");
        ResponseEntity<Map> own = get(token, "/api/suppliers/5");
        assertThat(own.getStatusCode()).isEqualTo(HttpStatus.OK);
        ResponseEntity<Map> other = get(token, "/api/suppliers/2");
        assertThat(other.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
        Map error = (Map) other.getBody().get("error");
        assertThat(String.valueOf(error.get("code"))).isEqualTo("SUPPLIER_NOT_FOUND");
    }

    // self-user (SELF) can read own supplier 6 but NOT supplier 1 (HQ/admin)
    @Test
    void selfUserSeesOwnDetailOnly() {
        String token = token("self-user", "admin123");
        ResponseEntity<Map> own = get(token, "/api/suppliers/6");
        assertThat(own.getStatusCode()).isEqualTo(HttpStatus.OK);
        ResponseEntity<Map> other = get(token, "/api/suppliers/1");
        assertThat(other.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
        Map error = (Map) other.getBody().get("error");
        assertThat(String.valueOf(error.get("code"))).isEqualTo("SUPPLIER_NOT_FOUND");
    }

    // update out of scope -> denied (SUPPLIER_NOT_FOUND), row unchanged
    // sales-manager has update permission but scope = Sales+Sales-East (2,3);
    // supplier 5 is Finance (dept 4) -> out of scope
    @Test
    void updateOutOfScopeDenied() {
        String token = token("sales-manager", "admin123");
        ResponseEntity<Map> update = rest.exchange(url("/api/suppliers/5"),
                HttpMethod.PUT, json(token, "{\"code\":\"SUP-005\",\"name\":\"Hacked\"}"), Map.class);
        assertThat(update.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
        Map error = (Map) update.getBody().get("error");
        assertThat(String.valueOf(error.get("code"))).isEqualTo("SUPPLIER_NOT_FOUND");
        // supplier 5 unchanged
        String adminToken = token("admin", "admin123");
        Map detail = (Map) get(adminToken, "/api/suppliers/5").getBody().get("data");
        assertThat(detail.get("name")).isEqualTo("S-FINANCE-1");
    }

    // disable out of scope -> denied (finance-user has disable permission but
    // scope = Finance (dept 4); supplier 2 is Sales -> out of scope)
    @Test
    void disableOutOfScopeDenied() {
        String token = token("finance-user", "admin123");
        ResponseEntity<Map> disable = rest.exchange(url("/api/suppliers/2/disable"),
                HttpMethod.POST, json(token, "{}"), Map.class);
        assertThat(disable.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
        Map error = (Map) disable.getBody().get("error");
        assertThat(String.valueOf(error.get("code"))).isEqualTo("SUPPLIER_NOT_FOUND");
    }

    // update in scope -> OK (sales-manager, scope Sales+Sales-East, supplier 2)
    @Test
    void updateInScopeOk() {
        String token = token("sales-manager", "admin123");
        ResponseEntity<Map> update = rest.exchange(url("/api/suppliers/2"),
                HttpMethod.PUT, json(token, "{\"code\":\"SUP-002\",\"name\":\"S-SALES-1-renamed\"}"), Map.class);
        assertThat(update.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(((Map) update.getBody().get("data")).get("name")).isEqualTo("S-SALES-1-renamed");
    }
}
