-- Supplier reference schema (generated by engineering-platform ${asset.version})
-- V009: creates the supplier table (V0.6 generic module proof domain).
-- MySQL-compatible baseline (H2 MODE=MySQL for tests).

CREATE TABLE IF NOT EXISTS supplier (
    id            BIGINT       NOT NULL AUTO_INCREMENT,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(128) NOT NULL,
    status        VARCHAR(32)  NOT NULL DEFAULT 'ENABLED',
    category      VARCHAR(64)  NULL,
    department_id BIGINT       NULL,
    created_by    VARCHAR(64)  NULL,
    created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_supplier_code (code),
    KEY idx_supplier_department (department_id),
    KEY idx_supplier_created_by (created_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
