// Product route registration + DataScope UI evidence (generated by engineering-platform frontend-product-reference asset)
// Route module must be picked up by the frontend-auth router via glob.
import { describe, it, expect } from 'vitest';
import { productRoutes } from '../src/router/product';

describe('product routes', () => {
  it('registers /products, detail and edit routes with permission meta', () => {
    const paths = productRoutes.map((r) => r.path);
    expect(paths).toContain('/products');
    expect(paths).toContain('/products/:id');
    expect(paths).toContain('/products/:id/edit');

    const list = productRoutes.find((r) => r.path === '/products')!;
    expect(list.meta).toMatchObject({ permission: 'product:item:read' });
    const edit = productRoutes.find((r) => r.path === '/products/:id/edit')!;
    expect(edit.meta).toMatchObject({ permission: 'product:item:update' });
  });

  it('routes are static imports (no dynamic component from backend path)', () => {
    for (const r of productRoutes) {
      expect(typeof r.component).toBe('function'); // lazy import fn, not a backend-derived string
    }
  });
});
